### ISSUE TITLE
dump1090 errors not logged

### ISSUE THREAD

**Issue by bradanlane** [cyoung/stratux#102]
If dump1090 generates any error messages that do not abort the process, they are lost.

This is not a problem under normal operations but users who may experience power related oddities (and we have seen them) will not get any evidence in the log files.

The only way to detect the errors are by killing off the stratux process and then manually starting dump1090 manually. This is difficult now that  dump1090 is started inside of the main gen_gdl90 code.

**Comment by jpoirier** [comment]
We can grab stderr (and stdio ?) from the running process and pass it to the logger.

**Comment by bradanlane** [comment]
I attempted this but not being completely fluent with golang, I wasn't able to get the proper results.

I'll leave this open in the hopes someone can make the necessary changes.

**Comment by jpoirier** [comment]
Thanks for giving it a shot. I'll try to add this within the next few days.

**Comment by jpoirier** [comment]
It's simpler (five or six lines of code) to just pipe the dump1090 stdio and stderr to the current stratux log. My last commit is included in the pending push.
