### ISSUE TITLE
bugs related to unplugging SDRs

### ISSUE THREAD

**Issue by bradanlane** [cyoung/stratux#103]
I'm noticing a few things with the new code.

If the UAT dongle is disconnected, the ReadSync look goes crazy logging as fast as it possible can, saturating the log.

Here is the "sdr unplug" problem. In (UAT) read()
```
    for {
        select {
        default:
            nRead, err := u.dev.ReadSync(buffer, rtl.DefaultBufLength)
            if err != nil {
                log.Printf("\tReadSync Failed - error: %s\n", err)
                break
            }
            // log.Printf("\tReadSync %d\n", nRead)
            if nRead > 0 {
                buf := buffer[:nRead]
                godump978.InChan <- buf
            }
        case <-uat_shutdown:
            log.Println("UAT read(): shutdown msg received...")
            return
        }
    }
```

The `break` will only break from the `select` and not from the outer loop. Changing the `break` to a `return` solves this.

In testing, weird things happen with the two SDRs when one is unplugged.
1. When I unplug the UAT SDR, I see a set of ES related messages.
2. Plugging the UAT SDR back in seems to attempt a restart of dump1090.
3. I end us with a bunch of defunct processes.

**Comment by jpoirier** [comment]
The break should stay and and the log message should be commented out. The sdrWatcher will eventually signal the goroutine to exit when it figures out the dongle has been removed.

**Comment by bradanlane** [comment]
How long before the signal? I let it run for at least 15 seconds in one test. I also reconnected the SDR within about 5-10 seconds in a subsequent test. I continually saw the error message and it never restored operations.

**Comment by jpoirier** [comment]
I've not timed it but you shouldn't take more than a few seconds. Keep in mind that sdrWatcher has a 1 second heartbeat whereas the goroutine is open throttle.

**Comment by bradanlane** [comment]
OK, we need to test.

I definitely tested much more than "several seconds" in both scenarios.

**Comment by jpoirier** [comment]
Watch what the web interface is doing when dongle/s are inserted and extracted not the log; the logging is incidental and latent.

**Comment by jpoirier** [comment]
There's a pull request to s/return/break, which is what you want to test with.

**Comment by bradanlane** [comment]
I'm not going to be back at a computer for at least a day so this is an open request:

When I changed the "break" to a "return" and then tested unplugging the UAT SDR followed by plugging it back in, I saw dump1090 being restarted. I also saw multiple defunct dump1090 processes. 

In my tests, changing the "break" to a "return" was not a complete fix.

**Comment by bradanlane** [comment]
it seems we have addressed this issue so I will close it. I would like us to plan a "test cycle" when @cyoung plans the next "release".
