### ISSUE TITLE
New tuner code bails if frequency correction is set to 0

### ISSUE THREAD

**Issue by loather** [cyoung/stratux#113]
My tuners are accurate and don't require a ppm correction (verified with kalibrate-rtl) so I have mine set to 0. This makes stratux angry and the following message is repeated until I set the correction to != 0:

2015/11/01 15:46:34 ===== UAT Device name: Generic RTL2832U OEM =====
Found Rafael Micro R820T tuner
2015/11/01 15:46:34     GetTunerType: RTLSDR_TUNER_R820T
2015/11/01 15:46:34     SetTunerGainMode Successful
2015/11/01 15:46:34     SetTunerGain Successful
Exact sample rate is: 2083334.141630 Hz
[R82XX] PLL not locked!
2015/11/01 15:46:34     SetSampleRate - rate: 2083334
2015/11/01 15:46:34     GetSampleRate: 2083334
2015/11/01 15:46:34     GetXtalFreq - Rtl: 28800000, Tuner: 28800000
2015/11/01 15:46:34     SetXtalFreq - Center freq: 28800000, Tuner freq: 28800000
2015/11/01 15:46:35     SetCenterFreq 978MHz Successful
2015/11/01 15:46:35     GetCenterFreq: 978000000
2015/11/01 15:46:35     Setting Bandwidth: 1000000
2015/11/01 15:46:35     SetTunerBw 1000000 Successful
2015/11/01 15:46:35     ResetBuffer Successful
2015/11/01 15:46:35     GetFreqCorrection: 0
2015/11/01 15:46:35     SetFreqCorrection 0 Failed, error: invalid parameter(s)
2015/11/01 15:46:35 UATDev = &UAT{indexID: id} failed: invalid parameter(s)

if GetFreqCorrection == 0 && desiredFreqCorrection == 0 then there's no need to call SetFreqCorrection (especially if desiredFreqCorrection == 0, because apparently that's an invalid parameter for whatever reason).

**Comment by cyoung** [comment]
Look back on the commit comments. You need to run "go get -u all" and then rebuild.
