### ISSUE TITLE
Makefile changes with 9dda52d cause 'make install' to fail

### ISSUE THREAD

**Issue by loather** [cyoung/stratux#115]
The 'ln' commands at the end of the Makefile lack -f to clobber any existing symlinks.

**Comment by cyoung** [comment]
You should see about making pull requests :)

**Comment by loather** [comment]
I will do that :) I need to better learn how to use Github and Git in general.

**Comment by kdknigga** [comment]
This is a fun-ish way to learn:

http://
<http://www.google.com/url?q=http%3A%2F%2Fpcottle.github.io%2FlearnGitBranching%2F&sa=D&sntz=1&usg=AFQjCNHJITlkdUc2PkGUokzfIXWh76-r2w>
pcottle.github.io
<http://www.google.com/url?q=http%3A%2F%2Fpcottle.github.io%2FlearnGitBranching%2F&sa=D&sntz=1&usg=AFQjCNHJITlkdUc2PkGUokzfIXWh76-r2w>
/
<http://www.google.com/url?q=http%3A%2F%2Fpcottle.github.io%2FlearnGitBranching%2F&sa=D&sntz=1&usg=AFQjCNHJITlkdUc2PkGUokzfIXWh76-r2w>
learnGitBranching
<http://www.google.com/url?q=http%3A%2F%2Fpcottle.github.io%2FlearnGitBranching%2F&sa=D&sntz=1&usg=AFQjCNHJITlkdUc2PkGUokzfIXWh76-r2w>
/
<http://www.google.com/url?q=http%3A%2F%2Fpcottle.github.io%2FlearnGitBranching%2F&sa=D&sntz=1&usg=AFQjCNHJITlkdUc2PkGUokzfIXWh76-r2w>

**Comment by loather** [comment]
Thanks. i'll give those a look!
