### ISSUE TITLE
Ahrs doesn't work in flight. 

### ISSUE THREAD

**Issue by RobertGary1** [cyoung/stratux#149]
Is it an known issue that this doesn't work in flight? I set mine on the floor and did steep turns and the roll indication of the Stratux page didn't change by more than a degree. On the other hand if I wiggled it on the floor the wiggle showed up as rolling.  I'm running v5 with the RY835AI. I assume it's only detecting uncoordinated turns. 

-Robert

**Comment by ssokol** [comment]
Yep, that's a known issue. AHRS is still very much a work in progress.

On Wed, Dec 16, 2015 at 9:37 PM, RobertGary1 <notifications@github.com>
wrote:

> Is it an known issue that this doesn't work in flight? I set mine on the
> floor and did steep turns and the roll indication of the Stratux page
> didn't change by more than a degree On the other hand if I wiggled it on
> the floor the wiggle showed up as rolling I'm running v5 with the RY835AI I
> assume it's only detecting uncoordinated turns
>
> -Robert
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cyoung/stratux/issues/149>.
>



-- 
Steven Sokol
408 Camelot Drive
Liberty, MO 64068

mobile: +1 816-806-8844
fax: +1 816-817-0441
