### ISSUE TITLE
Webpage cache needs flushed

### ISSUE THREAD

**Issue by Nokomis449** [cyoung/stratux#164]
When running 2 different Stratuxes with 2 different versions and switching between the two, the version number does not update correctly when switching between the boxes.

**Comment by Ergonomicmike** [comment]
I don't know how to look at the Source for the UI on my tablet, and I don't have wi-fi on my desktop to look. But perhaps the source should have

Cache-Control: no-cache, no-store, must-revalidate
Pragma: no-cache
Expires: 0

If it doesn't already?

http://stackoverflow.com/questions/49547/making-sure-a-web-page-is-not-cached-across-all-browsers

**Comment by bradanlane** [comment]
We should test the performance impact of this. The total web resource download is not insignificant and "no-cache" is a bit like using a sledge hammer on a finish nail.

**Comment by cyoung** [comment]
I think the only thing we really needed to fix this was https://github.com/cyoung/stratux/commit/1c231dd301c48c579250097f219dff382b98ad32.
