### ISSUE TITLE
add mpu9250 support

### ISSUE THREAD

**Issue by LithuanianAmerican** [cyoung/stratux#187]
mpu9150 is being phased out for mpu9250. They are very similar except data resolution. It would be nice to have mpu9250 for the future hw support.

**Comment by cyoung** [comment]
Try out https://github.com/cyoung/linux-mpu9150 and see if it needs any mods, if you find there are some significant benefits we will revisit this. Going to stick with the current hardware while we work out the implementation.

**Comment by skypuppy** [comment]
someone has been BUSY!!!
