### ISSUE TITLE
No AHRS on v0.5b5

### ISSUE THREAD

**Issue by yasbean** [cyoung/stratux#194]
I know just enough to get myself in trouble, but I soldered jumpers to my RY835AI and hooked it up to the GPIOs.  On v0.5b4, I was able to get AHRS movement on the Web UI, but with the new image, I get now movement.  The Status page has a green check by AHRS, though.

**Comment by Nokomis449** [comment]
Try rebooting the Stratux a few times with GPS off and on, try cycling AHRS off and on and rebooting... I had the same issue and one of those actions fixed it.

**Comment by yasbean** [comment]
Roger!  That did it.
