### ISSUE TITLE
1090 "drop off" after 5 to 30 minutes

### ISSUE THREAD

**Issue by ssokol** [cyoung/stratux#202]
Running 0.5b5. Dual band system with NESDR nano 2s + Vk-172. dmurray14 antennas. Ground testing, so no UAT signals.

When I start the system I get a usual 1090-ES stream - typically 500 messages / minute. After some time, between 5 and 30 minutes, the 1090 stream tapers off to very low numbers. As few as 12 messages per second.

Give the box a hard reboot (the reboot button seems to cause it to hang - something we've seen before) and when it comes back up, we're back to 500+ messages / minute.

Any ideas?

**Comment by Axtel4** [comment]
I've been running for an hour or so.  Is this bad? I am not sure what the 7,640/10,178 signifies.

> 2016/01/11 21:42:54 stats [started: 1 hour ago]
2016/01/11 21:42:54  - CPUTemp=37.39 deg C, MemStats.Alloc=2.5 MB, MemStats.Sys=13 MB, totalNetworkMessagesSent=253,433
2016/01/11 21:42:54  - UAT/min 0/0 [maxSS=0.00%], ES/min 7,640/10,178
, Total traffic targets tracked=247

v0.5r5, Dual dongles, RY835, 1090 MHz collinear feeding 1090 dongle, L Band blade feeding 978 Dongle.  Outside MCI Mode C veil.

**Comment by cyoung** [comment]
7,640/10,178 means 7,640 messages last minute, 10,178 highest message/min.

**Comment by Axtel4** [comment]
Thanks.

**Comment by ssokol** [comment]
Wow. That's some serious reception. Best I've seen is in the 1300 messages
per minute range.

I'm based on the east edge of the MCI veil at 0N0. Are you local or just
passing through?

On Monday, January 11, 2016, cyoung <notifications@github.com> wrote:

> 7,640/10,178 means 7,640 messages last minute, 10,178 highest message/min.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cyoung/stratux/issues/202#issuecomment-170778862>.
>


-- 
Steven Sokol
408 Camelot Drive
Liberty, MO 64068

mobile: +1 816-806-8844
fax: +1 816-817-0441

**Comment by duecedriver** [comment]
I wrote up something similar last week over on one of the Reddit threads. Same behavior. Although putting an ice pack over the sdr increased traffic

When tuning the sdr with sdr sharp it drifts really badly on narrow band fm   

Can anyone see if something is actually getting jammed up in the code?

**Comment by Axtel4** [comment]
Local on the southwest side.

**Comment by Axtel4** [comment]
If it helps any, here is an ES range plot and the Stratux log for above.

![range plot](https://cloud.githubusercontent.com/assets/15059010/12254777/31213ce2-b8b2-11e5-8ee5-fe4ea92b8795.jpg)
[Stratux.txt](https://github.com/cyoung/stratux/files/86773/Stratux.txt)

**Comment by cyoung** [comment]
@ssokol - try with no cooling, let 'er get heated.

**Comment by Axtel4** [comment]
> I'm based on the east edge of the MCI veil at 0N0. 

Roosterville.  Always wanted to land there just to say I did.

**Comment by duecedriver** [comment]
Best I have gotten is like 30 miles.that sitting on the ground testing in the house. Is that in the air

**Comment by skypuppy** [comment]
Thermal drift of the rtlsdr?

**Comment by ssokol** [comment]
Will do.

On Mon, Jan 11, 2016 at 10:32 PM, cyoung <notifications@github.com> wrote:

> @ssokol <https://github.com/ssokol> - try with no cooling, let 'er get
> heated.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cyoung/stratux/issues/202#issuecomment-170786684>.
>



-- 
Steven Sokol
408 Camelot Drive
Liberty, MO 64068

mobile: +1 816-806-8844
fax: +1 816-817-0441

**Comment by ssokol** [comment]
Yep. 18' wide and 2700' long. I learned to fly here - lots of fun. You just
treat the asphalt as a centerline in the middle of a 50'-wide grass runway.

On Mon, Jan 11, 2016 at 10:42 PM, Axtel4 <notifications@github.com> wrote:

> I'm based on the east edge of the MCI veil at 0N0.
>
> Roosterville. Always wanted to land there just to say I did.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cyoung/stratux/issues/202#issuecomment-170787988>.
>



-- 
Steven Sokol
408 Camelot Drive
Liberty, MO 64068

mobile: +1 816-806-8844
fax: +1 816-817-0441

**Comment by ssokol** [comment]
Can't reproduce this at the moment, so closing. (But opening another ticket as I think I may have found a related bug.)
