### ISSUE TITLE
1090 does not gracefully restart

### ISSUE THREAD

**Issue by ssokol** [cyoung/stratux#204]
Running 0.5b4. Dual band w/ NooElec Nano 2 NESDRs. 

Tried restarting gen_gdl90 using 'service stratux restart' and found that after the restart I was unable to receive any 1090-ES messages. Message count remained at zero. Nothing in the log file. Tried killing dump1090 and it went [defunct]. Had to do a full power cycle before it resumed receiving.

Tested the "reboot" button and it that seems to work properly (i.e. it does not hang the reboot).

Anyone else seen this?

**Comment by cyoung** [comment]
"service stratux restart" doesn't restart until the latest commits.

**Comment by ssokol** [comment]
Oops - I left that out. I updated to the latest commit.

On Wed, Jan 13, 2016 at 2:27 PM, cyoung <notifications@github.com> wrote:

> "service stratux restart" doesn't restart until the latest commits.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cyoung/stratux/issues/204#issuecomment-171422808>.
>



-- 
Steven Sokol
408 Camelot Drive
Liberty, MO 64068

mobile: +1 816-806-8844
fax: +1 816-817-0441

**Comment by cyoung** [comment]
Hmm, and you were sure to do a "make install"?

I know that it's not exiting dump1090 cleanly when gen_gdl90 is killed - need to add some signal handlers. Try adding "pkill dump1090" before "pkill gen_gdl90" in the init script and see how it does.

**Comment by ssokol** [comment]
No luck. I don't seem to be getting the [defunct] at this point, but if
regardless of the order of the killing, 1090 fails to restart cleanly. I
seem to always get one 1090 message and that's it.

On Wed, Jan 13, 2016 at 3:04 PM, cyoung <notifications@github.com> wrote:

> Hmm, and you were sure to do a "make install"?
>
> I know that it's not exiting dump1090 cleanly when gen_gdl90 is killed -
> need to add some signal handlers. Try adding "pkill dump1090" before "pkill
> gen_gdl90" in the init script and see how it does.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cyoung/stratux/issues/204#issuecomment-171432007>.
>



-- 
Steven Sokol
408 Camelot Drive
Liberty, MO 64068

mobile: +1 816-806-8844
fax: +1 816-817-0441
