### ISSUE TITLE
FWIW, SkyRadar AHRS info

### ISSUE THREAD

**Issue by Nokomis449** [cyoung/stratux#206]
For the people working on AHRS code - I started toying around with the AHRS on my SkyRadar DX, and noticed that the AHRS does not move at all (it indicates level flight) UNTIL its GPS light comes on.  At that point, the AHRS comes alive and will indicate correctly.  This is true in the moving plane and on the kitchen table.  At the table I can then disconnect the GPS antenna, and the AHRS continues to function correctly.  So the GPS seems to be providing something to the AHRS code that is needed for initial startup.  Just thought I'd pass this along.

**Comment by duecedriver** [comment]
gps data is probably being fed to a kalman filter with the magnetometer data to provide heading 

in garmin logic, if the gps signal to the ahrs is down but the magnetometer is working, you will just get a gps degrade flag.. if the magnetometer is also down, you will get no heading

**Comment by ssokol** [comment]
From what I remember from Samuel Cowan's articles on inertial compensation,
you can use rate-of-turn data from either a magnetometer or a GPS. Mag is
closer to real-time. GPS is less given to errors.

On Thursday, January 14, 2016, duecedriver <notifications@github.com> wrote:

> gps data is probably being fed to a kalman filter with the magnetometer
> data to provide heading
>
> in garmin logic, if the gps signal to the ahrs is down but the
> magnetometer is working, you will just get a gps degrade flag.. if the
> magnetometer is also down, you will get no heading
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cyoung/stratux/issues/206#issuecomment-171705239>.
>


-- 
Steven Sokol
408 Camelot Drive
Liberty, MO 64068

mobile: +1 816-806-8844
fax: +1 816-817-0441

**Comment by cyoung** [comment]
@Nokomis449 - thanks for the information.
