### ISSUE TITLE
WingX weirdness

### ISSUE THREAD

**Issue by duecedriver** [cyoung/stratux#209]
latest WingX release 5.5b

WingX will report say 9 1090 traffic but only be displaying 4

the stratus web page traffic pages generally shows what WingX is plotting say the 4... so where is the 9 coming from?

**Comment by egid** [comment]
Any chance it's filtering distant targets? I remember there's an option for this in the totally impenetrable WingX settings, but I can't recall where.

**Comment by duecedriver** [comment]
nope. I have the altitude filter turned off so it should be showing everything...

**Comment by egid** [comment]
Huh. I'd give it a shot, but my Stratux is in pieces and it's raining cats and dogs out here today!

**Comment by ScraboTower** [comment]
Same combo as the OP and not seeing the same issue.

**Comment by duecedriver** [comment]
So the number of 1090 traffic reported in the wingx stratux pull down tab always matches the number of targets displayed on screen? 

Huh... I wonde what's wrong with mine. 

I still don't get but a handful and only out to 40 miles I wonder if I have a mediocre sdr

**Comment by cyoung** [comment]
Reopen with more info to reproduce if still an issue.
