### ISSUE TITLE
WebUI shows Weather "Receiving" even on 1090 only

### ISSUE THREAD

**Issue by Ergonomicmike** [cyoung/stratux#210]
Small nit.

Single Dongle Plain Vanilla Stratux running v0.5b5. The weather page shows me "Receiving" weather (Green tag) even when on only 1090. This persists after a reboot. Of course, Watching and Reports are zero.

**Comment by cyoung** [comment]
The "Receiving" indicator is showing (correctly) that the web browser is receiving weather updates from the device - maybe the meaning of "Receiving" could be clearer or should be reevaluated.

**Comment by Ergonomicmike** [comment]
Perhaps eliminated then? I thought it was an Activity Checker, indicating that weather products were coming thru. Since we already have a "Connected" marker in the status page, what new info does "Receiving" indicate?

**Comment by Axtel4** [comment]
Maybe "Weather Connected / Not Receiving", "Weather Connected / Receiving"?

**Comment by cyoung** [comment]
Need: three state display. Connected, Disconnected, Receiving. Or clarify the current "Receiving". @bradanlane, let's go with what you think is best.

**Comment by bradanlane** [comment]
I'll normalize the messages to "connected"/"disconnected" and will verify it is logical an intuitive in all cases.

**Comment by cyoung** [comment]
https://github.com/cyoung/stratux/commit/bbbcd3bbe16f67febb9955ff7d92908b82d2fa24
