### ISSUE TITLE
v 0.5b5 info on object incorrect

### ISSUE THREAD

**Issue by rapgood** [cyoung/stratux#211]
Running v 0.5b5 on Raspberry Pi. Foreflight v. 7.5.1. When I interrogate the "Status" statistics on Stratux web page (@ 192.168.10.1) I note Zero messages on UAT and hundreds of messages on 1090. This is reasonable considering where I have the Pi located (not near any towers). However, when I tap on an aircraft object icon in Foreflight maps, it shows data on the aircraft in the balloon that indicates the data source is UAT (ADS-B 978). NB: aircraft are in numerous airspace spaces.

**Comment by kdknigga** [comment]
This is a known issue.  Stratux tells reports all traffic as coming from
UAT.  If you turn on traffic source identification in the settings tab it
will prepend call signs with either u or e depending on the source (UAT or
ES, respectively).
