### ISSUE TITLE
WebUI Discrepancies 0.5b5

### ISSUE THREAD

**Issue by kjablonski** [cyoung/stratux#219]
1. Stratux 0.5b5
2. Config:  2 SDR, RY835AI

Testing out the 0.5b5 build I noticed that there are differences between what i can see using a laptop connected to the Stratux and the link provided by Stratux on my cellphone for the favorite link.  My laptop will show the GPS constellation count and status where the mobile application only shows the number of satellites.
Mobile:
![screenshot_2016-01-25-12-44-22](https://cloud.githubusercontent.com/assets/648296/12560853/859ed580-c362-11e5-9ebc-47475957bbf6.png)

Laptop:
![image](https://cloud.githubusercontent.com/assets/648296/12560763/1729a3aa-c362-11e5-8697-3f4ed82edd4c.png)

**Comment by bradanlane** [comment]
looks like the mobile has cached some old[er] files. The best solution to this is to establish a "manifest" for the files so the browser knows when local cached copies are no longer current.

**Comment by kjablonski** [comment]
I'll clear my cache and recheck.  I was running 0.5b1

**Comment by braddward** [comment]
If you've saved it to your home screen on an Apple device I've found that
Apple stores that cache separately from the Safari cache.  The only way to
clear that sometimes is to delete the icon and reinstall it.   A manifest
file is probably a good idea.

**Comment by cyoung** [comment]
Need: cache manifest.

**Comment by bradanlane** [comment]
A manifest file have a version number to increment when files change. Is there an easy way to generate this number as part of the build? 

_I'm sure I could hack something wish bash scripting but im feeling lazy and hope there is a better way_

**Comment by cyoung** [comment]
Yes, in the Makefile:

```
www:
	echo "# " `git describe --tags --abbrev=0` >>/var/www/stratux.appcache
```

Or something similar. That would tag the file on install with the git commit hash.

**Comment by cyoung** [comment]
https://github.com/cyoung/stratux/commit/442e882646467bf6db9d7dd84dc0e8a5ddd527fa
