### ISSUE TITLE
1090ES Traffic on FltPlan go 0.5b6

### ISSUE THREAD

**Issue by jwp01** [cyoung/stratux#221]
Minor problem / observation: 1090ES traffic on Fltplan go now has a dark ring around each target.  This was not the case with 0.5b5.  WingX does not have the rings.
![img_0002](https://cloud.githubusercontent.com/assets/16507409/12599492/58edd8ac-c460-11e5-8c23-5862481dd347.PNG)

**Comment by cyoung** [comment]
I think this has more to do with a FltPlan Go change - how they're displaying traffic. Just tried it out and the ring doesn't seem proportional to speed or anything else that one might expect.

**Comment by cyoung** [comment]
One of the FltPlan Go devs responded to an email about this - they say the black circle is just for visibility. Their choice, not mine.
