### ISSUE TITLE
192.168.10.1/logs/startux sorting

### ISSUE THREAD

**Issue by peepsnet** [cyoung/stratux#232]
Can we sort this page alphabetically?? Its a PITA to find anything.

And some file details like size

**Comment by kjablonski** [comment]
+1 or sort by type (UAT, 1090, GPS)

**Comment by bkwny** [comment]
+1.  +100 if I could.  I just now pulled logs for @cyoung.  What a pain it was.

**Comment by peepsnet** [comment]
The only way I can see to get this going is json. 
Can we get a json array of files in the log folder.
we can parse with angularUI and list sort and filter. then we can build a link around each file .

I don't know how to do that in any timely manor but I know we could take that approach

Thoughts???

**Comment by cyoung** [comment]
Don't bother too much with it, in the next release we'll be using a webserver (not Go webserver) to serve the webui files + logs. What you are requesting is a fairly standard feature of most webservers.

**Comment by peepsnet** [comment]
Great.

**Comment by cyoung** [comment]
![stratux_logs](https://cloud.githubusercontent.com/assets/57193/13588938/0c25cc48-e4a2-11e5-90d1-f11d8c3a9b9a.png)


Any better?

**Comment by bkwny** [comment]
Oh yes!

**Comment by cyoung** [comment]
Accessible at http://192.168.10.1/view_logs. Linked also in the "Logs" tab of the main interface.

**Comment by bkwny** [comment]
I have 796d0a2 but my /logs/ tab does not link to /view_logs.  And in /logs/ when I click on "SDR, AHRS, and GPS logs" I see the old-style listing of log files.

**Comment by cyoung** [comment]
The first part is not intended behavior, the second part sounds like your browser may have cached the files.

Did you try going directly to the link? http://192.168.10.1/view_logs/

**Comment by bkwny** [comment]
Yes, when I tried to go directly to the link, the next thing I saw in the browser window was the Web UI's "Status" tab.
