### ISSUE TITLE
Web UI GPS Status not reporting loss of GPS

### ISSUE THREAD

**Issue by Ergonomicmike** [cyoung/stratux#235]
(I thought I saw a template for submitting New Issues, but I can't remember where. Am copying from a previous issue posted by Chris.)

  1. Stratux version: v0.6r1 (with modified ry385ai.go and powersave governor)
  2. Stratux config: dual SDR, GPS BU-353-S4, AHRS no, battery Anker E5, battery cable Anker 21 AWG
  3. EFB app and version NA. EFB platform NA. EFB hardware NA.
  4. Description of your issue. "When you unplug the GPS USB cable, the GPS information (solution & satellites) on the web UI Status page does not show the loss of GPS. (The information stays as it last was before GPS is lost.) Same comment for the GPS/AHRS page in the web UI. See https://www.reddit.com/r/stratux/comments/442lnn/please_pull_your_usb_gps_and_report_what_happens/  for more info."

**Comment by cyoung** [comment]
When you click "New Issue", you'll see "Please review the guidelines for contributing to this repository." There's a link to auto-fill the issue with that there.

**Comment by Ergonomicmike** [comment]
Ahh... okay. I saw the message about guidelines. But like most Americans, I didn't bother to read the instructions. :-(

**Comment by mooneyguy** [comment]
Just wanted to let you know I just read the "Statux ADS-B: DIY and Save Big". It was a good article supporting Stratux and a great reflection on the brains working on it.

 

Thanks for all of your work!

 

Mark

**Comment by AvSquirrel** [comment]
See #238.
