### ISSUE TITLE
Validate UBX messages for 3.01 firmware update

### ISSUE THREAD

**Issue by kjablonski** [cyoung/stratux#245]
Version: 0.6r1
GPS:  RY835AI
SDR: N/A

u-blox updated the NEO-M8N firmware to 3.01.  Major improvements include the ability to use the Galileo Constellation.  Possible issue:  [release notes](https://www.u-blox.com/sites/default/files/GNSS-FW3.01_ReleaseNotes_%28UBX-16000319%29_Public.pdf) state that navigation rate should be set to 3Hz when using Galileo.

**Comment by skypuppy** [comment]
how odd.

**Comment by cyoung** [comment]
Thanks for the report, we'll keep it in mind when/if we use Galileo ;)
