### ISSUE TITLE
v0.7b1 Question

### ISSUE THREAD

**Issue by Axtel4** [cyoung/stratux#252]
1. Stratux version: v0.7b1
2. Stratux config: single/dual SDR, GPS yes/no (type?), AHRS yes/no, battery, battery cable. N/A
3. EFB app and version (e.g., WingX Pro7 8.6.2). EFB platform (e.g., iOS 9.2). EFB hardware (e.g., iPad Mini 2). N/A
4. Description of your issue. If possible, enable "Replay Logs", reproduce the problem, and provide a copy of the logs in http://192.168.10.1/logs/stratux/ and http://192.168.10.1/logs/stratux.log. See below. . .

I want to see if I am doing this correctly.

The Web UI shows v0.7b1:

![v0 7b1](https://cloud.githubusercontent.com/assets/15059010/13066106/8c49f366-d428-11e5-9fa7-fea74f94a5df.JPG)

However in the Raspberry Pi git describe and git log show:
>root@raspberrypi:~/stratux# git describe --abbrev=0 --tags
>v0.6r1
>root@raspberrypi:~/stratux# git log -n 1 --pretty=%H
>a4f5696a297c818f3c572fb3fe0625c0b0119614
>root@raspberrypi:~/stratux#

Did Stratux move to some other place than /root/stratux?

Attached is a screen shot of the update sequence.
[v0.7b1_update.txt](https://github.com/cyoung/stratux/files/131821/v0.7b1_update.txt)
 
Also, in Chrome the "Choose File" button is truncated:
![choose file v0 7b1](https://cloud.githubusercontent.com/assets/15059010/13066224/73cf78b4-d429-11e5-9ffc-e6fbc4e8d73f.JPG)

Thanks in advance.

Edit: added template info.

**Comment by cyoung** [comment]
If it is showing v0.7b1 in the web interface then you've upgraded - so that seems OK.

The upgrade file just contains binaries and won't upgrade your source tree. You will have to maintain that separately - git pull, etc. Our source tree right now is about 95M uncompressed, 51M compressed. Without it, the update is 6.1M.

**Comment by Axtel4** [comment]
So, does it hurt anything to git pull / make / make install in parallel to keep the source tree up to date?

**Comment by cyoung** [comment]
No, it will not hurt. The "make install" method will keep you up-to-date with stratux software and related libraries. System settings aren't managed with the Makefile, so if you don't update via an image or the update files and we make system-wide changes (dhcp config, sysctl settings, etc) then you'll miss those changes.

**Comment by Ergonomicmike** [comment]
My "Choose File" button is cut off after the F.

**Comment by cyoung** [comment]
Sounds about right, that's my best interface work.

**Comment by cyoung** [comment]
Reopen if any further issue(s).
