### ISSUE TITLE
File system corruption on power down

### ISSUE THREAD

**Issue by jzeevi** [cyoung/stratux#256]
Using .7b1, I flew for .9 hours with no apparent issues (although ADS-B towers kept disappearing and re-appearing). When the flight completed, I simply removed power to the Stratux (as is usually what I do).

This morning, I wired up a fan to the case I built and when I attempted to restart the device, it would not boot (as evidenced by the green light on the RPi dropping much quicker than it does when the system boots and the lack of the SDR's or Wifi chip to come up).

After several restart attempts, I re-imaged my microSD card and things are back to normal.

Obviously, I can shutdown with the UI in the future, but agree with past posters that it might be wise to have an RO parition and a RW partition that can always be rebuilt if it is corrupted.

**Comment by cyoung** [comment]
>although ADS-B towers kept disappearing and re-appearing

Are you referring to the ForeFlight display? If so, that's an app issue - they changed the way they display towers a few versions ago.

**Comment by jzeevi** [comment]
Thanks - yes, I'm using FF. I forgot to mention that above. Do you have any insight as to why they now come and go?

And, FWIW - I wanted to justify this as a bug report as it actually crashed the RPi. I know there's an enhancement request but I wanted to track an actual failure. :-)

**Comment by cyoung** [comment]
No clue. Use our web interface to get accurate reception info.

**Comment by jzeevi** [comment]
LOL. Thanks. I'll ask (the QA manager is a friend)
