### ISSUE TITLE
Typos in WebUI

### ISSUE THREAD

**Issue by bkwny** [cyoung/stratux#258]
1. Stratux version: 0.7b1+14 commits
2. Stratux config: single/dual SDR, GPS yes/no (type?), AHRS yes/no, battery, battery cable.
Dual SDR Nano 2, RY835AI via GPIO, no AHRS, external power.
3. EFB app and version (e.g., WingX Pro7 8.6.2). EFB platform (e.g., iOS 9.2). EFB hardware (e.g., iPad Mini 2).  N/A for this issue.
4. Description of your issue. If possible, enable "Replay Logs", reproduce the problem, and provide a copy of the logs in http://192.168.10.1/logs/stratux/ and http://192.168.10.1/logs/stratux.log.

1.  In web/plates/logs-help.html: change "teh replay logs" to "the replay logs", and change "enalbve" to "enable".
2.  In web/plates/settings.html: change "space delimeted" to "space-delimited", and change "978MHz" to "978 MHz", and change "1090MHz" to "1090 MHz".
3.  In web/plates/status-help.html:  change "978MHz" to "978 MHz" and change "1090MHz" to "1090 MHz".

**Comment by cyoung** [comment]
Thank you!

**Comment by bkwny** [comment]
Check the repair in web/plates/settings.html - "delimited" is still not spelled correctly.  The placeholder text should say, "space-delimited identifiers".
