### ISSUE TITLE
Emails from stratux issue tracker

### ISSUE THREAD

**Issue by Bradan** [cyoung/stratux#260]
Hello,

@skypuppy Last night I've got many emails regarding an issue in your issue tracker, although I have nothing to do with stratux (yet). You've tagged me (bradan) instead of bradanlane. Please be more careful.

[Issue](https://github.com/cyoung/stratux/issues/254#issuecomment-185414366)

Kind regards,
Daniel

**Comment by skypuppy** [comment]
Please pardon me.  I will conform.
Skypuppy
