### ISSUE TITLE
support for wifi "profiles"

### ISSUE THREAD

**Issue by dickinsonmg** [cyoung/stratux#262]
Hi,

Wondering if it's possible to add the concept of "wifi profiles", with support of switching profile (and adding?) via the web-interface.

For example, one profile would be the standard "stratux" SSID as is default at present. A second profile that is creatable by the user would allow the unit to join a wifi network (like a home network or personal hotspot) to allow updating without opening cases/plugging in ethernet. Once an update is complete, then the user could switch profiles back to the default "stratux" profile.

thanks.

**Comment by bkwny** [comment]
+1.  SSID, whether hidden, channel number, encryption level, password, list of authorized MAC addresses.  Or, if client mode, a list of known SSIDs along with the credentials needed to connect to them.  IMHO the AP stuff is more important than the client stuff.

**Comment by cyoung** [comment]
Consolidating to #228.
