### ISSUE TITLE
v0.7b2 Web Interface Missing Time and 2nd SDR PPM Correction

### ISSUE THREAD

**Issue by pp4life** [cyoung/stratux#270]
1. Stratux version: 0.7b2
2. Stratux config: single/**dual** SDR, GPS yes/**no** (type?), AHRS yes/**no**, wall power
3.EFB app and version: Foreflight 7.5.2. EFB platform: iOS 8.3 on, EFB hardware: iPad Mini 2.
4. Description of your issue. I updated to 0.7b2 (with no commits) with the .sh method and I'm not seeing the "Stratux Clock" and "Device Clock" in the WebUI on Safari.  Is that normal without GPS? I've tried deleting the shortcut from my home page and clearing the cache and history for Safari on the iPad mini. I've also tried this from an Android phone with Chrome and from a desktop with Firefox. Same result. 

I am also not seeing anywhere to put in the 2nd SDR PPM correction.

Lastly, from the iPad (or I assume any iDevice) when you click on the "Click to select System Update file" button, it only lets you select from your photo album or to take a picture. Searching around, this seems like a limitation of iDevices. Super annoying. I did the *.sh update through my android. 

![img_0005](https://cloud.githubusercontent.com/assets/17072153/13186772/f7a7b376-d704-11e5-9d1c-cc41b2e7af04.PNG)
![img_0006](https://cloud.githubusercontent.com/assets/17072153/13186773/f7b8fb72-d704-11e5-80ec-eb46b5ec7416.PNG)

**Comment by Axtel4** [comment]
Did you clear the Browser cache and reload the and Stratux Web UI?

**Comment by ssokol** [comment]
I can confirm this. Flushed and I still get:

[image: Inline image 1]

[image: Inline image 2]

On Fri, Feb 19, 2016 at 1:45 PM, Axtel4 <notifications@github.com> wrote:

> Did you clear the Browser cache and reload the and Stratux Web UI?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cyoung/stratux/issues/270#issuecomment-186373958>.
>



-- 
Steven Sokol
408 Camelot Drive
Liberty, MO 64068

mobile: +1 816-806-8844
fax: +1 816-817-0441

**Comment by cyoung** [comment]
The feature was added by @yihchun in PR #248 for those that program their SDR strings for tuned antennas. No feature has been added to the web interface to make use of the functionality as yet.

**Comment by pp4life** [comment]
Ah OK. I have written strings to the SDRs for the dmurray antennas, but they are the standard "stratux:XXXX". I now see how @yihchun has implemented the tuning per SDR with the strings. I'll have to rewrite the strings to take advantage of the per SDR PPM settings.

**Comment by pp4life** [comment]
@sskol, your images didn't come through on the github site

**Comment by pp4life** [comment]
This is what it looks like after the 0.7b3 "sh" update. All looks good!

![file feb 22 12 42 16 pm](https://cloud.githubusercontent.com/assets/17072153/13230224/ccc46c6c-d961-11e5-9be2-c2cfa39bd2ce.png)

**Comment by cyoung** [comment]
Expecting feature that never existed.
