### ISSUE TITLE
Misspelling in default content of Settings->Configuration->Watch List

### ISSUE THREAD

**Issue by bjax** [cyoung/stratux#271]
1. Stratux version: 1.6r1
2. Stratux config: all (web interface)
3. EFB app and version: web interface
4. The default string loaded in the Settings->Configuration->Watch List field is "space delimeted identifiers"; should be "delimited"

**Comment by cyoung** [comment]
@bjax - thanks for creating a pull request to make this change. You created it on your own branch, so it's not mergeable into the main master branch. I made another one from your branch: https://github.com/cyoung/stratux/pull/272. Hope this helps if you plan to contribute further.
