### ISSUE TITLE
Not able to download  v0.7b3

### ISSUE THREAD

**Issue by mooneyguy** [cyoung/stratux#286]
I have download image updates just fine since v0.5b1. Now when I try to save v0.7b3 I get a quick blink and then a notice it is saved but when I go to my folder to find the usual zip file the file seems is just a small or corrupt looking white page instead of the usual yellow zip folder and no application I have opens it. How do I solve this problem?

**Comment by skypuppy** [comment]
Wait a few seconds after it says done before you try to open it. 
Sometimes it is still in the download buffer and not written fully to 
the file.  Other times the download gets corrupt so wait a minute and 
try to download it again.

**Comment by mooneyguy** [comment]
@skypuppy I have waited over night and it is still the same thing. Tried it all over today and got the same result.

**Comment by skypuppy** [comment]
Sounds like a corrupt file, then.

**Comment by mooneyguy** [comment]
It will usually take a few minutes to down load and then says the down load was successful but now it is all over in 3 seconds and says it was successful.

**Comment by peepsnet** [comment]
Try a different browser. My firefox doesnt like github and I have to use chrome...

**Comment by mooneyguy** [comment]
I have tried internet explorer and chrome and have the same results.

**Comment by wakkow** [comment]
I think you're downloading an update scripts. You'll need to download the last full release v0.7b1, then update it via the web interface with the update script. I haven't tried it yet, so I don't know if you hae to do b1 -> b2 -> b3 or if you can go b1 -> b3

**Comment by cyoung** [comment]
@wakkow is correct.

And v0.7b1 -> v0.7b3 is fine, you don't have to do one version at a time.
