### ISSUE TITLE
an interesting snipet from the new pi release article .. power issues ...

### ISSUE THREAD

**Issue by duecedriver** [cyoung/stratux#304]
"The camera-shy Raspberry Pi 2 suffered problems with the switched mode power supply (SMPS) chip on the board, which turned out to be photosensitive. Too much light, such as from flash photography, caused fluctuation in the power supply and made the board reset. "

possibly part of peoples power woes if used on the glarshield in a translucent case... 

only visible light or can it be affected by "other" radiated energy.. ie leaky sidelobe or transmitter power supplies.. etc..

thoughts..

**Comment by kdknigga** [comment]
https://www.raspberrypi.org/blog/xenon-death-flash-a-free-physics-lesson/

TL;DR: "the effect only happens under VERY specific circumstances. Flashes
of high-intensity, long-wave light"

**Comment by cyoung** [comment]
That's a good catch. Anyone have power issues that may be light exposure related?

**Comment by AvSquirrel** [comment]
To reempahsize @kdknigga  --
>I’ve said it above, but it bears repeating, because I’ve seen some of you mention this in the forums and in comments sections elsewhere: **common everyday light sources – e.g. bright sunlight, indoor lighting, angry cyclists* – don’t cause this to happen, so please don’t worry**

**Comment by peepsnet** [comment]
My few flashes of brilance while working on my ppl have not seemed to of affected the stratux at all. I guess its not the correct wavelength?!

**Comment by Axtel4** [comment]
Cross post from Reddit:

Mine has been running for hours sitting on a glare shield, in a translucent case, and with a DME and Mode S transponder running with no ill effects. Oh, and cruising altitude at 8k to 10k ft.

I have also run it for hours sitting on the dashboard of a vehicle with no ill effects.
