### ISSUE TITLE
AvSquirrel Fork: Service Just stops. No BLOD build - fd936e7e1b

### ISSUE THREAD

**Issue by peepsnet** [cyoung/stratux#318]
1. Stratux version: 0.8r1
2. Stratux config:

    SDR
      [ ] single
      [ X ] dual

    GPS
      [ X ] yes
      [ ] no
      type:

    AHRS
      [ X ] yes
      [ ] no

    power source: 2.1A Wall Plug

    usb cable: portapow 20awg

3. EFB 
N/A

4. Description of your issue:

Service just stops. 
[stratux (1).log.txt](https://github.com/cyoung/stratux/files/166476/stratux.1.log.txt)

This happened a few times. After the last I started a fresh log file. This is the log attached. just over 30min of time then the service stopped. 

SSH still works and my webmin interface still works.

This is a new issue for me since v0.8r1

What other system logs can I look at for any errors??

**Comment by Axtel4** [comment]
The next time it happens, try `service stratux status` to see what it says.  If it says, "[FAIL] stratux is not running ... failed!".  Try `service stratux start` to see if it restarts.

**Comment by peepsnet** [comment]
It says not running

but restarts just fine

**Comment by peepsnet** [comment]
Dump1090 is still running

**Comment by Axtel4** [comment]
> It says not running

I saw that yesterday on v0.7b3 right before I updated to v0.8r1, but I haven't see it since updating.  I don't know why Stratux just stopped, but I was able to restart it without rebooting Stratux.

**Comment by AvSquirrel** [comment]
For posterity, fd936e7e1b is the current commit on my experimental branch.

@peepsnet - can you just start `./gen_gdl90` from the command line and let it run until it crashes again? I'd like to capture a stack trace to see exactly what's causing it to crash.

Not that it's necessarily related, I was getting some intermittent out-of-bounds array indexes a few commits back due to unsafe array handling in my pseudoattitude code. I thought I got that fixed (haven't seen a crash in about a week) but I'd like to make sure you're not seeing that.

**Comment by Ergonomicmike** [comment]
@AvSquirrel I looked at the commit. The lines in the config in wheezy-stage-4

```
        echo "arm_freq=900" >>boot/config.txt
  	echo "sdram_freq=450" >>boot/config.txt
  	echo "core_freq=450" >>boot/config.txt
```

seem unnecessary, since we're running Powersave governor now. Yes?

**Comment by AvSquirrel** [comment]
@Ergonomicmike - Dunno. Chris put those in about six weeks ago (https://github.com/cyoung/stratux/commit/5aca8adea2b4f8c6fe7baf312088bafa152a73be). Must have come along for the ride at some point when I synced against master.

**Comment by Ergonomicmike** [comment]
@peepsnet I've had my Stratux running at home for 24 hrs now on v0.8r1 w/o problems. Trying to isolates the differences, what brand of GPS? And did you write to the SDR's? (@cyoung This might be useful info in the Issue Template, since there's a lot of extra (new) code that handles dedicated SDR's.) I have stock SDR's.

**Comment by peepsnet** [comment]
SDRs: 2 X Nano2+
(Serials: stx:978:5 / stx:0:0)
RY835AI
2 X Edimax

I added an app called wicd-curses, a few hours ago, to experiment with controlling my wlan1 . I uninstalled this and restarted the stratux service. I am now waiting for a failure.

**Comment by Ergonomicmike** [comment]
Oh, yeah, I forgot that you've two Edimax's going. So w/ those and your added app, your system is definitely not normative.

**Comment by peepsnet** [comment]
I have webmin
http://www.webmin.com/deb.html

htop
http://www.webhostingbuzz.com/wiki/install-htop-linux/

ntp
https://wiki.debian.org/NTP

and lighttpd w/php

but I have had them installed since v0.6

**Comment by Ergonomicmike** [comment]
So Chris should probably add another item to the template: non-standard software. (Although were it me, I would say it voids your warranty.)

**Comment by peepsnet** [comment]
So I am going to chalk this up to the wifi manager tool thing!!  I am not seeing a failure. I will leave it to run overnight

**Comment by Ergonomicmike** [comment]
I've thought of that too. I'm always typing the same thing into the template, I'm going to save it as a text file next time.

**Comment by peepsnet** [comment]
We should set the example... lol

**Comment by skypuppy** [comment]
Valgrind is your friend.

**Comment by peepsnet** [comment]
9hours up time! We can close it

**Comment by peepsnet** [comment]
@AvSquirrel 
Ok so the error is with gen_gdl90

`root@raspberrypi:~# /usr/bin/gen_gdl90
2016/03/10 15:37:16 Stratux v0.8r1 (fd936e7e1b71429abb4e853f8a7116078a3da718) starting.
2016/03/10 15:37:16 Entered uatReader() ...
2016/03/10 15:37:16 read in settings.
2016/03/10 15:37:16 lease expired for 192.168.10.18 (2016/02/16 03:22:36) - skipping.
2016/03/10 15:37:16 lease expired for 192.168.10.19 (2016/02/27 00:28:02) - skipping.
2016/03/10 15:37:16 lease expired for 192.168.10.10 (2016/03/08 21:52:32) - skipping.
2016/03/10 15:37:16 client connected: 192.168.10.12:4000 (android-a694dd93f3d60a75).
2016/03/10 15:37:16 client connected: 192.168.10.12:4001 (android-a694dd93f3d60a75).
2016/03/10 15:37:16 client connected: 192.168.10.12:4002 (android-a694dd93f3d60a75).
2016/03/10 15:37:16 client connected: 192.168.10.12:43211 (android-a694dd93f3d60a75).
2016/03/10 15:37:16 client connected: 192.168.10.13:4000 (android-495004c3ce8ba7d3).
2016/03/10 15:37:16 client connected: 192.168.10.13:4001 (android-495004c3ce8ba7d3).
2016/03/10 15:37:16 client connected: 192.168.10.13:4002 (android-495004c3ce8ba7d3).
2016/03/10 15:37:16 client connected: 192.168.10.13:43211 (android-495004c3ce8ba7d3).
2016/03/10 15:37:17 ===== UAT Device Name  : Generic RTL2832U OEM =====
2016/03/10 15:37:17 ===== UAT Device Serial: stx:978:8=====

Kernel driver is active, or device is claimed by second instance of librtlsdr.
In the first case, please either detach or blacklist the kernel module
(dvb_usb_rtl28xxu), or enable automatic detaching at compile time.

usb_claim_interface error -6
2016/03/10 15:37:17     UAT Open Failed...
2016/03/10 15:37:17 UATDev.sdrConfig() failed: resource busy
2016/03/10 15:37:17 ===== UAT Device Name  : Generic RTL2832U OEM =====
2016/03/10 15:37:17 ===== UAT Device Serial: stx:0:0=====

Kernel driver is active, or device is claimed by second instance of librtlsdr.
In the first case, please either detach or blacklist the kernel module
(dvb_usb_rtl28xxu), or enable automatic detaching at compile time.

usb_claim_interface error -6
2016/03/10 15:37:17     UAT Open Failed...
2016/03/10 15:37:17 UATDev.sdrConfig() failed: resource busy
2016/03/10 15:37:20 Configuring GPS
2016/03/10 15:37:20 Using /dev/ttyAMA0 for GPS
2016/03/10 15:37:20 Finished writing u-blox GPS config to /dev/ttyAMA0. Opening port to test connection.

Initializing IMU .2016/03/10 15:37:21 GPS dectected: NMEA messages seen.
2016/03/10 15:37:21 GPS detected: u-blox NMEA position message seen.
.2016/03/10 15:37:21 Average sendable queue is 0 messages. Changing queue timer to 0.100000 seconds
........ done

Default accelcal.txt not found
Default magcal.txt not found
2016/03/10 15:37:21 NMEA messages last minute. Valid: 9. Position: 9. Invalid: 0.
data_ready() - data not ready.
2016/03/10 15:37:24 NMEA messages last minute. Valid: 42. Position: 36. Invalid: 0.
2016/03/10 15:37:26 Average sendable queue is 0 messages. Changing queue timer to 0.100000 seconds
dmp_read_fifo() failed
2016/03/10 15:37:28 NMEA messages last minute. Valid: 94. Position: 80. Invalid: 0.
2016/03/10 15:37:28 gpsSerialReader() scanner loop iteration i=100
dmp_read_fifo() failed
2016/03/10 15:37:31 Average sendable queue is 0 messages. Changing queue timer to 0.100000 seconds
2016/03/10 15:37:32 NMEA messages last minute. Valid: 146. Position: 124. Invalid: 0.
dmp_read_fifo() failed
2016/03/10 15:37:36 Average sendable queue is 0 messages. Changing queue timer to 0.100000 seconds
2016/03/10 15:37:36 NMEA messages last minute. Valid: 197. Position: 167. Invalid: 0.
2016/03/10 15:37:36 gpsSerialReader() scanner loop iteration i=200
dmp_read_fifo() failed
2016/03/10 15:37:40 NMEA messages last minute. Valid: 249. Position: 211. Invalid: 0.
2016/03/10 15:37:41 Average sendable queue is 0 messages. Changing queue timer to 0.100000 seconds
2016/03/10 15:37:44 gpsSerialReader() scanner loop iteration i=300
dmp_read_fifo() failed
2016/03/10 15:37:44 NMEA messages last minute. Valid: 302. Position: 256. Invalid: 0.
2016/03/10 15:37:46 Average sendable queue is 0 messages. Changing queue timer to 0.100000 seconds
2016/03/10 15:37:46 stats [started: 30 seconds ago]
2016/03/10 15:37:46  - CPUTemp=38.47 deg C, MemStats.Alloc=6.3 MB, MemStats.Sys=13 MB, totalNetworkMessagesSent=10
2016/03/10 15:37:46  - UAT/min 0/0 [maxSS=0.00%], ES/min 415/415
, Total traffic targets tracked=7
2016/03/10 15:37:46  - Network data messages sent: 0 total, 0 nonqueueable.  Network data bytes sent: 0 total, 0 nonqueueable.
2016/03/10 15:37:46  - Last GPS fix: now, GPS solution type: 2 using 9 satellites (10/15 seen/tracked), NACp: 10, est accuracy 4.80 m
2016/03/10 15:37:46  - GPS vertical velocity: 0.08 ft/sec; GPS vertical accuracy: 8.2 m
2016/03/10 15:37:46 lease expired for 192.168.10.18 (2016/02/16 03:22:36) - skipping.
2016/03/10 15:37:46 lease expired for 192.168.10.19 (2016/02/27 00:28:02) - skipping.
2016/03/10 15:37:46 lease expired for 192.168.10.10 (2016/03/08 21:52:32) - skipping.
2016/03/10 15:37:48 NMEA messages last minute. Valid: 354. Position: 300. Invalid: 0.
dmp_read_fifo() failed
2016/03/10 15:37:51 Average sendable queue is 0 messages. Changing queue timer to 0.100000 seconds
2016/03/10 15:37:51 gpsSerialReader() scanner loop iteration i=400
2016/03/10 15:37:52 NMEA messages last minute. Valid: 406. Position: 344. Invalid: 0.
dmp_read_fifo() failed
2016/03/10 15:37:56 Average sendable queue is 0 messages. Changing queue timer to 0.100000 seconds
2016/03/10 15:37:56 NMEA messages last minute. Valid: 457. Position: 387. Invalid: 0.
dmp_read_fifo() failed
panic: runtime error: index out of range

goroutine 30 [running]:
main.processNMEALine(0x11006540, 0x6c, 0x6c)
        /root/stratux-dev/main/ry835ai.go:948 +0x1328
main.gpsSerialReader()
        /root/stratux-dev/main/ry835ai.go:1550 +0x2e0
created by main.pollRY835AI
        /root/stratux-dev/main/ry835ai.go:1791 +0xec

goroutine 1 [select (no cases)]:
main.main()
        /root/stratux-dev/main/gen_gdl90.go:1562 +0xedc

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
        /root/go/src/runtime/asm_arm.s:1036 +0x4

goroutine 5 [syscall]:
os/signal.loop()
        /root/go/src/os/signal/signal_unix.go:22 +0x14
created by os/signal.init.1
        /root/go/src/os/signal/signal_unix.go:28 +0x30

goroutine 6 [chan receive]:
github.com/golang/glog.(*loggingT).flushDaemon(0x5a7078)
        /root/go_path/src/github.com/golang/glog/glog.go:882 +0x60
created by github.com/golang/glog.init.1
        /root/go_path/src/github.com/golang/glog/glog.go:410 +0x2cc

goroutine 7 [select, locked to thread]:
runtime.gopark(0x485308, 0x1071ef8c, 0x3ed700, 0x6, 0x73118, 0x2)
        /root/go/src/runtime/proc.go:185 +0x148
runtime.selectgoImpl(0x1071ef8c, 0x0, 0xc)
        /root/go/src/runtime/select.go:392 +0x14d4
runtime.selectgo(0x1071ef8c)
        /root/go/src/runtime/select.go:212 +0x10
runtime.ensureSigM.func1()
        /root/go/src/runtime/signal1_unix.go:227 +0x400
runtime.goexit()
        /root/go/src/runtime/asm_arm.s:1036 +0x4

goroutine 8 [chan receive]:
main.signalWatcher()
        /root/stratux-dev/main/gen_gdl90.go:1373 +0x3c
created by main.main
        /root/stratux-dev/main/gen_gdl90.go:1381 +0x16c

goroutine 9 [chan receive]:
main.(*monotonic).Watcher(0x107116c0)
        /root/stratux-dev/main/monotonic.go:28 +0x34
created by main.NewMonotonic
        /root/stratux-dev/main/monotonic.go:48 +0x88

goroutine 10 [sleep]:
time.Sleep(0x3b9aca00, 0x0)
        /root/go/src/runtime/time.go:59 +0x104
main.sdrWatcher()
        /root/stratux-dev/main/sdr.go:441 +0x3c
created by main.sdrInit
        /root/stratux-dev/main/sdr.go:498 +0x24

goroutine 11 [chan receive]:
main.uatReader()
        /root/stratux-dev/main/sdr.go:280 +0xe0
created by main.sdrInit
        /root/stratux-dev/main/sdr.go:499 +0x38

goroutine 34 [chan receive]:
_/root/stratux-dev/godump978.ProcessDataFromChannel()
        /root/stratux-dev/godump978/godump978.go:59 +0x40
created by main.sdrInit
        /root/stratux-dev/main/sdr.go:501 +0x50

goroutine 19 [IO wait]:
net.runtime_pollWait(0x731e2e18, 0x72, 0x1070e0a0)
        /root/go/src/runtime/netpoll.go:157 +0x60
net.(*pollDesc).Wait(0x10752378, 0x72, 0x0, 0x0)
        /root/go/src/net/fd_poll_runtime.go:73 +0x34
net.(*pollDesc).WaitRead(0x10752378, 0x0, 0x0)
        /root/go/src/net/fd_poll_runtime.go:78 +0x30
net.(*netFD).Read(0x10752340, 0x10c96000, 0x1000, 0x1000, 0x0, 0x76272030, 0x1070e0a0)
        /root/go/src/net/fd_unix.go:232 +0x1c4
net.(*conn).Read(0x1070a2b0, 0x10c96000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /root/go/src/net/net.go:172 +0xc8
bufio.(*Reader).fill(0x10751d00)
        /root/go/src/bufio/bufio.go:97 +0x1c4
bufio.(*Reader).ReadSlice(0x10751d00, 0xa, 0x0, 0x0, 0x0, 0x0, 0x0)
        /root/go/src/bufio/bufio.go:328 +0x264
bufio.(*Reader).ReadBytes(0x10751d00, 0x17f30a, 0x0, 0x0, 0x0, 0x0, 0x0)
        /root/go/src/bufio/bufio.go:406 +0x7c
bufio.(*Reader).ReadString(0x10751d00, 0x107ce00a, 0x0, 0x0, 0x0, 0x0)
        /root/go/src/bufio/bufio.go:446 +0x44
main.esListen()
        /root/stratux-dev/main/traffic.go:816 +0x188
created by main.initTraffic
        /root/stratux-dev/main/traffic.go:1215 +0xe8

goroutine 22 [chan receive]:
main.pollRY835AI()
        /root/stratux-dev/main/ry835ai.go:1786 +0x88
created by main.initRY835AI
        /root/stratux-dev/main/ry835ai.go:1841 +0xc0

goroutine 23 [select]:
main.heartBeatSender()
        /root/stratux-dev/main/gen_gdl90.go:638 +0x538
created by main.main
        /root/stratux-dev/main/gen_gdl90.go:1518 +0xa34

goroutine 24 [IO wait]:
net.runtime_pollWait(0x731e34a8, 0x72, 0x1070e0a0)
        /root/go/src/runtime/netpoll.go:157 +0x60
net.(*pollDesc).Wait(0x1078c3b8, 0x72, 0x0, 0x0)
        /root/go/src/net/fd_poll_runtime.go:73 +0x34
net.(*pollDesc).WaitRead(0x1078c3b8, 0x0, 0x0)
        /root/go/src/net/fd_poll_runtime.go:78 +0x30
net.(*netFD).accept(0x1078c380, 0x0, 0x731e3540, 0x10d136d0)
        /root/go/src/net/fd_unix.go:408 +0x21c
net.(*TCPListener).AcceptTCP(0x107920f8, 0x1071b698, 0x0, 0x0)
        /root/go/src/net/tcpsock_posix.go:254 +0x4c
net/http.tcpKeepAliveListener.Accept(0x107920f8, 0x0, 0x0, 0x0, 0x0)
        /root/go/src/net/http/server.go:2135 +0x3c
net/http.(*Server).Serve(0x1078c340, 0x731e3520, 0x107920f8, 0x0, 0x0)
        /root/go/src/net/http/server.go:1887 +0x88
net/http.(*Server).ListenAndServe(0x1078c340, 0x0, 0x0)
        /root/go/src/net/http/server.go:1877 +0x124
net/http.ListenAndServe(0x3e8f90, 0x3, 0x0, 0x0, 0x0, 0x0)
        /root/go/src/net/http/server.go:1967 +0x90
main.managementInterface()
        /root/stratux-dev/main/managementinterface.go:456 +0x344
created by main.main
        /root/stratux-dev/main/gen_gdl90.go:1520 +0xa48

goroutine 35 [chan receive]:
main.gpsAttitudeSender()
        /root/stratux-dev/main/ry835ai.go:1671 +0x4c
created by main.pollRY835AI
        /root/stratux-dev/main/ry835ai.go:1784 +0x68

goroutine 25 [chan receive]:
main.(*uibroadcaster).writer(0x107ce8a0)
        /root/stratux-dev/main/uibroadcast.go:47 +0x48
created by main.NewUIBroadcaster
        /root/stratux-dev/main/uibroadcast.go:31 +0x13c

goroutine 26 [chan receive]:
main.(*uibroadcaster).writer(0x107ce8c0)
        /root/stratux-dev/main/uibroadcast.go:47 +0x48
created by main.NewUIBroadcaster
        /root/stratux-dev/main/uibroadcast.go:31 +0x13c

goroutine 36 [chan receive]:
main.monitorDHCPLeases()
        /root/stratux-dev/main/network.go:326 +0x60
created by main.initNetwork
        /root/stratux-dev/main/network.go:453 +0x124

goroutine 37 [select]:
main.messageQueueSender()
        /root/stratux-dev/main/network.go:236 +0x878
created by main.initNetwork
        /root/stratux-dev/main/network.go:454 +0x138

goroutine 38 [IO wait]:
net.runtime_pollWait(0x731e3070, 0x72, 0x1070e0a0)
        /root/go/src/runtime/netpoll.go:157 +0x60
net.(*pollDesc).Wait(0x1078c978, 0x72, 0x0, 0x0)
        /root/go/src/net/fd_poll_runtime.go:73 +0x34
net.(*pollDesc).WaitRead(0x1078c978, 0x0, 0x0)
        /root/go/src/net/fd_poll_runtime.go:78 +0x30
net.(*netFD).readFrom(0x1078c940, 0x10dac600, 0x5dc, 0x5dc, 0x0, 0x0, 0x0, 0x76272030, 0x1070e0a0)
        /root/go/src/net/fd_unix.go:259 +0x20c
net.(*IPConn).ReadFromIP(0x10792160, 0x10dac600, 0x5dc, 0x5dc, 0x51ce0, 0x1, 0x0, 0x0)
        /root/go/src/net/iprawsock_posix.go:75 +0xec
net.(*IPConn).ReadFrom(0x10792160, 0x10dac600, 0x5dc, 0x5dc, 0x348840, 0x0, 0x0, 0x0, 0x0)
        /root/go/src/net/iprawsock_posix.go:109 +0xe4
golang.org/x/net/icmp.(*PacketConn).ReadFrom(0x1078e690, 0x10dac600, 0x5dc, 0x5dc, 0x0, 0x0, 0x0, 0x0, 0x0)
        /root/go_path/src/golang.org/x/net/icmp/endpoint.go:59 +0xfc
main.sleepMonitor()
        /root/stratux-dev/main/network.go:376 +0x1c0
created by main.initNetwork
        /root/stratux-dev/main/network.go:455 +0x14c

goroutine 39 [chan receive]:
main.networkStatsCounter()
        /root/stratux-dev/main/network.go:429 +0x8c
created by main.initNetwork
        /root/stratux-dev/main/network.go:456 +0x160

goroutine 40 [chan receive]:
main.printStats()
        /root/stratux-dev/main/gen_gdl90.go:1260 +0x98
created by main.main
        /root/stratux-dev/main/gen_gdl90.go:1526 +0xa60

goroutine 41 [chan receive]:
main.cpuTempMonitor()
        /root/stratux-dev/main/gen_gdl90.go:779 +0x4c
created by main.main
        /root/stratux-dev/main/gen_gdl90.go:1529 +0xa74

goroutine 27 [chan receive]:
main.icmpEchoSender(0x1078e690)
        /root/stratux-dev/main/network.go:335 +0x70
created by main.sleepMonitor
        /root/stratux-dev/main/network.go:372 +0x134

goroutine 28 [IO wait]:
net.runtime_pollWait(0x731e2ff8, 0x72, 0x1070e0a0)
        /root/go/src/runtime/netpoll.go:157 +0x60
net.(*pollDesc).Wait(0x1078c078, 0x72, 0x0, 0x0)
        /root/go/src/net/fd_poll_runtime.go:73 +0x34
net.(*pollDesc).WaitRead(0x1078c078, 0x0, 0x0)
        /root/go/src/net/fd_poll_runtime.go:78 +0x30
net.(*netFD).Read(0x1078c040, 0x1075d000, 0x1000, 0x1000, 0x0, 0x76272030, 0x1070e0a0)
        /root/go/src/net/fd_unix.go:232 +0x1c4
net.(*conn).Read(0x10792000, 0x1075d000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /root/go/src/net/net.go:172 +0xc8
net/http.(*liveSwitchReader).Read(0x10776024, 0x1075d000, 0x1000, 0x1000, 0x348580, 0x0, 0x0)
        /root/go/src/net/http/server.go:219 +0x9c
io.(*LimitedReader).Read(0x1078e100, 0x1075d000, 0x1000, 0x1000, 0x10731bdc, 0x0, 0x0)
        /root/go/src/io/io.go:427 +0x104
bufio.(*Reader).fill(0x10790120)
        /root/go/src/bufio/bufio.go:97 +0x1c4
bufio.(*Reader).ReadSlice(0x10790120, 0xa, 0x0, 0x0, 0x0, 0x0, 0x0)
        /root/go/src/bufio/bufio.go:328 +0x264
bufio.(*Reader).ReadLine(0x10790120, 0x0, 0x0, 0x0, 0x3d8b00, 0x0, 0x0)
        /root/go/src/bufio/bufio.go:357 +0x60
net/textproto.(*Reader).readLineSlice(0x107cedc0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /root/go/src/net/textproto/reader.go:55 +0x58
net/textproto.(*Reader).ReadLine(0x107cedc0, 0x0, 0x0, 0x0, 0x0)
        /root/go/src/net/textproto/reader.go:36 +0x34
net/http.ReadRequest(0x10790120, 0x10f08e00, 0x0, 0x0)
        /root/go/src/net/http/request.go:653 +0x80
net/http.(*conn).readRequest(0x10776000, 0x0, 0x0, 0x0)
        /root/go/src/net/http/server.go:633 +0x3a8
net/http.(*conn).serve(0x10776000)
        /root/go/src/net/http/server.go:1319 +0x724
created by net/http.(*Server).Serve
        /root/go/src/net/http/server.go:1910 +0x360

goroutine 29 [IO wait]:
net.runtime_pollWait(0x731e2f80, 0x72, 0x1070e0a0)
        /root/go/src/runtime/netpoll.go:157 +0x60
net.(*pollDesc).Wait(0x1078ca78, 0x72, 0x0, 0x0)
        /root/go/src/net/fd_poll_runtime.go:73 +0x34
net.(*pollDesc).WaitRead(0x1078ca78, 0x0, 0x0)
        /root/go/src/net/fd_poll_runtime.go:78 +0x30
net.(*netFD).Read(0x1078ca40, 0x1078a000, 0x1000, 0x1000, 0x0, 0x76272030, 0x1070e0a0)
        /root/go/src/net/fd_unix.go:232 +0x1c4
net.(*conn).Read(0x10792210, 0x1078a000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /root/go/src/net/net.go:172 +0xc8
net/http.(*liveSwitchReader).Read(0x10776144, 0x1078a000, 0x1000, 0x1000, 0x1072bbf4, 0x0, 0x0)
        /root/go/src/net/http/server.go:219 +0x9c
io.(*LimitedReader).Read(0x1078ed40, 0x1078a000, 0x1000, 0x1000, 0x1, 0x0, 0x0)
        /root/go/src/io/io.go:427 +0x104
bufio.(*Reader).fill(0x10790420)
        /root/go/src/bufio/bufio.go:97 +0x1c4
bufio.(*Reader).ReadSlice(0x10790420, 0xa, 0x0, 0x0, 0x0, 0x0, 0x0)
        /root/go/src/bufio/bufio.go:328 +0x264
bufio.(*Reader).ReadLine(0x10790420, 0x0, 0x0, 0x0, 0x3d8b00, 0x0, 0x0)
        /root/go/src/bufio/bufio.go:357 +0x60
net/textproto.(*Reader).readLineSlice(0x10c7a140, 0x0, 0x0, 0x0, 0x0, 0x0)
        /root/go/src/net/textproto/reader.go:55 +0x58
net/textproto.(*Reader).ReadLine(0x10c7a140, 0x0, 0x0, 0x0, 0x0)
        /root/go/src/net/textproto/reader.go:36 +0x34
net/http.ReadRequest(0x10790420, 0x11010000, 0x0, 0x0)
        /root/go/src/net/http/request.go:653 +0x80
net/http.(*conn).readRequest(0x10776120, 0x0, 0x0, 0x0)
        /root/go/src/net/http/server.go:633 +0x3a8
net/http.(*conn).serve(0x10776120)
        /root/go/src/net/http/server.go:1319 +0x724
created by net/http.(*Server).Serve
        /root/go/src/net/http/server.go:1910 +0x360

goroutine 42 [chan receive]:
main.handleStatusWS(0x107e2050)
        /root/stratux-dev/main/managementinterface.go:106 +0x4c
golang.org/x/net/websocket.Server.serveWebSocket(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /root/go_path/src/golang.org/x/net/websocket/server.go:89 +0x260
golang.org/x/net/websocket.Server.ServeHTTP(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /root/go_path/src/golang.org/x/net/websocket/server.go:70 +0x38
main.managementInterface.func1(0x731e37f8, 0x10774080, 0x1070c070)
        /root/stratux-dev/main/managementinterface.go:425 +0x4c
net/http.HandlerFunc.ServeHTTP(0x484fc0, 0x731e37f8, 0x10774080, 0x1070c070)
        /root/go/src/net/http/server.go:1422 +0x34
net/http.(*ServeMux).ServeHTTP(0x10711200, 0x731e37f8, 0x10774080, 0x1070c070)
        /root/go/src/net/http/server.go:1699 +0x164
net/http.serverHandler.ServeHTTP(0x1078c340, 0x731e37f8, 0x10774080, 0x1070c070)
        /root/go/src/net/http/server.go:1862 +0x190
net/http.(*conn).serve(0x1076e000)
        /root/go/src/net/http/server.go:1361 +0xbfc
created by net/http.(*Server).Serve
        /root/go/src/net/http/server.go:1910 +0x360

goroutine 12 [chan receive]:
main.handleStatusWS(0x10712190)
        /root/stratux-dev/main/managementinterface.go:106 +0x4c
golang.org/x/net/websocket.Server.serveWebSocket(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /root/go_path/src/golang.org/x/net/websocket/server.go:89 +0x260
golang.org/x/net/websocket.Server.ServeHTTP(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /root/go_path/src/golang.org/x/net/websocket/server.go:70 +0x38
main.managementInterface.func1(0x731e37f8, 0x1077a000, 0x10ca4000)
        /root/stratux-dev/main/managementinterface.go:425 +0x4c
net/http.HandlerFunc.ServeHTTP(0x484fc0, 0x731e37f8, 0x1077a000, 0x10ca4000)
        /root/go/src/net/http/server.go:1422 +0x34
net/http.(*ServeMux).ServeHTTP(0x10711200, 0x731e37f8, 0x1077a000, 0x10ca4000)
        /root/go/src/net/http/server.go:1699 +0x164
net/http.serverHandler.ServeHTTP(0x1078c340, 0x731e37f8, 0x1077a000, 0x10ca4000)
        /root/go/src/net/http/server.go:1862 +0x190
net/http.(*conn).serve(0x10caa000)
        /root/go/src/net/http/server.go:1361 +0xbfc
created by net/http.(*Server).Serve
        /root/go/src/net/http/server.go:1910 +0x360

goroutine 13 [chan receive]:
main.handleStatusWS(0x107123c0)
        /root/stratux-dev/main/managementinterface.go:106 +0x4c
golang.org/x/net/websocket.Server.serveWebSocket(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /root/go_path/src/golang.org/x/net/websocket/server.go:89 +0x260
golang.org/x/net/websocket.Server.ServeHTTP(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /root/go_path/src/golang.org/x/net/websocket/server.go:70 +0x38
main.managementInterface.func1(0x731e37f8, 0x1077ab80, 0x10ca4e00)
        /root/stratux-dev/main/managementinterface.go:425 +0x4c
net/http.HandlerFunc.ServeHTTP(0x484fc0, 0x731e37f8, 0x1077ab80, 0x10ca4e00)
        /root/go/src/net/http/server.go:1422 +0x34
net/http.(*ServeMux).ServeHTTP(0x10711200, 0x731e37f8, 0x1077ab80, 0x10ca4e00)
        /root/go/src/net/http/server.go:1699 +0x164
net/http.serverHandler.ServeHTTP(0x1078c340, 0x731e37f8, 0x1077ab80, 0x10ca4e00)
        /root/go/src/net/http/server.go:1862 +0x190
net/http.(*conn).serve(0x10caa240)
        /root/go/src/net/http/server.go:1361 +0xbfc
created by net/http.(*Server).Serve
        /root/go/src/net/http/server.go:1910 +0x360

goroutine 14 [select]:
_/root/stratux-dev/mpu6050.(*MPU6050).Run.func1(0x107d7f10)
        /root/stratux-dev/mpu6050/mpu6050.go:137 +0x12c
created by _/root/stratux-dev/mpu6050.(*MPU6050).Run
        /root/stratux-dev/mpu6050/mpu6050.go:148 +0x44

goroutine 15 [runnable]:
main.attitudeReaderSender()
        /root/stratux-dev/main/ry835ai.go:1702 +0x6c
created by main.initAHRS
        /root/stratux-dev/main/ry835ai.go:1775 +0x1cc

goroutine 16 [chan receive]:
main.tempAndPressureReader()
        /root/stratux-dev/main/ry835ai.go:1605 +0x78
created by main.initAHRS
        /root/stratux-dev/main/ry835ai.go:1776 +0x1e0
root@raspberrypi:~#
`

**Comment by peepsnet** [comment]
Let me know what u need

**Comment by peepsnet** [comment]
The real issue is probably with the Avsquirrel Fork
Opened an issue in his Fork
https://github.com/AvSquirrel/stratux/issues/15

@cyoung: Feel free to close here

**Comment by cyoung** [comment]
https://github.com/AvSquirrel/stratux/tree/fd936e7e1b71429abb4e853f8a7116078a3da718
https://github.com/AvSquirrel/stratux/blob/fd936e7e1b71429abb4e853f8a7116078a3da718/main/ry835ai.go#L948

**Comment by AvSquirrel** [comment]
Thanks. Very helpful. This appears to be related to my development branch only, so I'll tag as 'externalbug' and continue tracking at avsquirrel/stratux#16
