### ISSUE TITLE
Find clock source for reasonably accurate time

### ISSUE THREAD

**Issue by cyoung** [cyoung/stratux#33]
UAT uplink messages perhaps?

**Comment by kdknigga** [comment]
GPS?

**Comment by 224XS** [comment]
Most devices that will be used to display data from Stratux will have access to one or more of these
1) GPS
2) Baseband cell network
3) ntd
plus
UAT downlink messages when available should be no more than a second off their GPS timebase
UAT uplink "should" also be no more than a second off, probably much less.

How accurate do you need?

**Comment by 224XS** [comment]
I rechecked the UAT uplink time spec - the header timestamp it is only good for resolving an 
80 micros slot in a single second (GDL 90 Spec section 3.3.1, p15)

I assume you want the time to set the rasp pi clock and a connection to www or baseband is not available inside the rasp pi.

users with a gps module will have a good time source of course. The display device (iPad, phone, etc) should also have a quality internal source that can be harvested and relayed back to the pi on running the web UI or a separate one time process.

Anything I can do?

**Comment by cyoung** [comment]
https://github.com/cyoung/stratux/blob/master/main/ry835ai.go#L118-L125

Seconds since midnight UAT - well, it's a timestamp, but not enough to set the Pi's clock. Is a full date/time sent on any GNSS actually?

Seems like a lot of trouble to do this with signal decoding. Yeah, if you're able to - let's just go with the iPad/Android clock.

**Comment by bradanlane** [comment]
I'm not sure you will have a transparent method for sending a date-time stamp *back* from the mobile device to the Stratux. Is there something that can be harvested from the network handshake? Or are you assuming something gets added to the WebUI?

GPS is the best choice when one is installed in the Stratux.

**Comment by kdknigga** [comment]
Yes, GPS has a full date and time stamp.

In fact, GPS time is pretty much the best time source one can have aside
from a caesium fountain.

ZDA is the NMEA message.

https://github.com/cyoung/stratux/blob/master/main/ry835ai.go#L118-L125

Seconds since midnight UAT - well, it's a timestamp, but not enough to set
the Pi's clock. Is a full date/time sent on any GNSS actually?

Seems like a lot of trouble to do this with signal decoding. Yeah, if
you're able to - let's just go with the iPad/Android clock.

—
Reply to this email directly or view it on GitHub
<https://github.com/cyoung/stratux/issues/33#issuecomment-140742395>.

**Comment by 224XS** [comment]
Hi,

Several NMEA sentences include full time info:
RMC, ZDA

Although I have not used it, ublox seems to have iTOW timestamps which would serve.

I’ll start looking into using the display device clock

Ira
N224XS

**Comment by cyoung** [comment]
I take back what I said previously then, looks like GPS is ideal -

      $GNRMC,141228.00,A,x,N,y,W,0.289,,160915,,,A*7C


Would you be interested in implementing this @224XS ?

**Comment by 224XS** [comment]
I have not got the module, but I can take a crack at the rasp pi code for it.

Do you have a preference for the architecture you want to use for pushing stuff from the web UI back into the pi/stratux?

if there is no GPS module, the pi should try to pull from the display device don’t you think?

Ira

**Comment by AvSquirrel** [comment]
@cyoung / @224XS - I do have the module, and would be able to build any code that you need tested.

**Comment by bradanlane** [comment]
@224xs - is there a solution which does not require the user to launch the WebUI (or any other "extra" UI/App) on the mobile device?

**Comment by 224XS** [comment]
Excellent!

**Comment by 224XS** [comment]
I would think a rasp pi startup process would grab accurate time from a GPS module. Only if there's no GPS on the Pi would you'll need to shoot the time from the webUI

**Comment by haykinson** [comment]
I don't think you should do this at startup time, at least not synchronously. The GPS may take some time to acquire a time source, so it's best done as a daemon or in code.

Also, http://www.satsignal.eu/ntp/Raspberry-Pi-NTP.html and http://www.bufferbloat.net/projects/cerowrt/wiki/Getting_time_from_gpsd can serve as good inputs into the discussion.

**Comment by kdknigga** [comment]
I've got XGPS160+gpsd+ntpd working on my rig, but I haven't yet made
gen_gdl90 work with gpsd.

My home computer is currently not working, so I need to get that fixed
before I can tinker more.

(Pro tip: don't let HP try to fix your Linux laptop.  You'll get it back
running Windows even though it was only the motherboard that was broken.)

**Comment by heelix** [comment]
Is it pulling time from the XGPS160?  I've got that same GPS hardware.

**Comment by kdknigga** [comment]
As I recall, yes.  It's been a while since I've messed with it, though.

I'll confirm and report back when I get my laptop back in working order.

Also, I got a Reyax module not too long ago.  I'll see if that GPS plays
nice with gpsd.

**Comment by 224XS** [comment]
True!  A startup process that tests for the presence of the GPS, then waits 60 s for a cold start since there is no keep alive batt.

**Comment by cyoung** [comment]
I don't think you'll even get a valid RMC message unless there is a GPS lock.

**Comment by kdknigga** [comment]
RPI + ry835ai + gpsd + ntpd = http://imgur.com/a/1XYsN

**Comment by cyoung** [comment]
@224XS - your code is integrated now.

Haven't looked into it really but the NEO-M8N seems to have a decent clock even without a GPS fix, definitely better than the Pi in any case.

**Comment by 224XS** [comment]
No worries Chris. Happy to help!
I just got a basket case of a 1953 PA-22/20, so my attention is going to be a bit divided now 
Ira
