### ISSUE TITLE
Ry835ai gps gpio "disconnected"

### ISSUE THREAD

**Issue by JEgasmanpa** [cyoung/stratux#342]
1. Stratux version:
2. Stratux config:

    SDR
      [ ] single
      [ x] dual

    GPS
      [ x] yes
      [ ] no
      type:

    AHRS
      [ x] yes
      [ ] no

    power source: adafruit powerboost 1000 with 3.7v LiPo battery

    usb cable:

3. EFB app and version: (e.g., WingX Pro7 8.6.2) yes

    EFB platform: (e.g., iOS 9.2)yes

    EFB hardware: (e.g., iPad Mini 2) yes

4. Description of your issue:

If possible, enable "Replay Logs", reproduce the problem, and provide a copy of the logs in http://192.168.10.1/logs/stratux/ and http://192.168.10.1/logs/stratux.log.

**Comment by JEgasmanpa** [comment]
After upgrade to v8r1 GPS (ry835ai) web ui "disconnected" AHRS ok.  USB gps works ok.

**Comment by cyoung** [comment]
Looks like you've fixed it? Re-open if not.
