### ISSUE TITLE
Using Bluetooth on RPi3

### ISSUE THREAD

**Issue by skypuppy** [cyoung/stratux#345]
1. Stratux version:  0.8r2
2. Stratux config:

    SDR
      [ ] single
      [ x] dual

    GPS
      [ x] yes
      [ ] no
      type: MTK3339 on serial, sirf on usb

    AHRS
      [ x] yes
      [ ] no

    power source: all wart

    usb cable:

3. EFB app and version: (e.g., WingX Pro7 8.6.2)  iFlyGPS 9.4

    EFB platform: (e.g., iOS 9.2): Android 5.x

    EFB hardware: (e.g., iPad Mini 2): Samsung Galaxy Tab S 10.1

4. Description of your issue:
The RPi-3 brings up an interesting possibility for an addition or change: using Bluteooth (LE) instead of wifi.  Does all EFB hardware have BT?  The main advantage is it consumes much less power than wifi.  Another advantage is for clubs/groups that fly with stratux because BT already has the capability for unique connections along with lower power radio so that fewer planes will see the same signal during close-in flying.  Wifi can be used in that same config by turning on WPA or something but the signal collision overhead is still incurred.
Thoughts?  A BT dongle is just as cheap as a wifi dongle.

**Comment by ScraboTower** [comment]
But isn't Apple for example, very tight about the BT standards used to connect to their devices ?

**Comment by skypuppy** [comment]
I don't know. 

 /rant on/ I am *really* sick of these companies locking in their products trying to create "vertical markets."  Garmin, Apple (in many areas), and so on just make me angry and I vote with my wallet.  Let them "sit on the shelf and rot."
/rant off/

I do know that my chosen EFB, iFly, does not have BT capability at this time.  However, lot's of them do.

**Comment by Nokomis449** [comment]
Skypuppy I'm sure you're talking about iFly's dedicated hardware (720, 740) which are wifi only, but the iFly app on Android and iDevices can use BT recievers as well as wifi receivers.  Just wanted to clarify that for others.

**Comment by peepsnet** [comment]
BLE is not avalible on all devices. Bluetooth is but the low energy is not.

Wifi is though

**Comment by Ergonomicmike** [comment]
On iFly: I was wondering whether iFly could use BT. So I tried transferring a Flight Plan from one tablet to the other paired via BT. No joy.

**Comment by skypuppy** [comment]
I remember iFly via tablets, etc., as not being bt capable.

**Comment by Nokomis449** [comment]
The BT-only Dual XGPS is an option under iFly's "Connected Devices".  Someone on Amazon gave this review:

http://www.amazon.com/review/R1Q45F8B1TL55A

**Comment by Nokomis449** [comment]
Re: ***On iFly: I was wondering whether iFly could use BT. So I tried transferring a Flight Plan from one tablet to the other paired via BT. No joy.***

Yeah I didn't mean to imply all networking functions will work on iFly via BT; only that Android and iDevices could receive ADS-B via BT devices.  I was specifically referring to skypuppy's BT/vertical market rant (with which I agree).  I wasn't thinking about flight plan sharing via BT.

**Comment by mhrussell1** [comment]
I just bought the Pi3 and GPS receiver for use with Avare and CloudAhoy.  Unfortunately, I then found that CloudAhoy will only work via BT, so I am motivated to add a BT interface to stratux.  I write S/W for Linux systems for a living but I have not done any projects via Git so I am hesitant to commit taking on this task.  Also, I hope this is not an improper way to jump into an open source project.

**Comment by skypuppy** [comment]
Just create another branch and have at it!  :)

**Comment by cyoung** [comment]
Unable to add Bluetooth support. Not enough EFB-side support to be worth the time.

**Comment by adambertsch** [comment]
Any chance we could try this for Avare w/ external I/O plugin and bluetooth on the pi3 as a first step?  I can work on this, but don't want to put in the effort if the pull request is unlikely to be merged.

**Comment by cyoung** [comment]
Yes, if you want to add this it will be merged so long as everything works well.

**Comment by cyoung** [comment]
#developers on Slack (see link on website) if you need help getting started.
