### ISSUE TITLE
EFB app compatibility error message needs to be scoped by IP address or MAC

### ISSUE THREAD

**Issue by bkwny** [cyoung/stratux#350]
1. Stratux version:  v0.8r2 (e12611e8d4)
2. Stratux config:

    SDR
      [ ] single
      [ x] dual

    GPS
      [ x] yes
      [ ] no
      type:  VK-172

    AHRS
      [ ] yes
      [x ] no

    power source:  Turnigy UBEC

    usb cable:  UBEC output line soldered to R Pi power pads

3. EFB app and version: (e.g., WingX Pro7 8.6.2)
    ForeFlight 7.6

    EFB platform: (e.g., iOS 9.2)   iOS 9.2

    EFB hardware: (e.g., iPad Mini 2)  iPad 3

4. Description of your issue:

The error message "Stratux is not supported by..." is too general.  More than one EFB device can use Stratux concurrently.  Some of those devices could be running compatible EFB apps while others could be running incompatible ones.  The error message should state which EFB(s), by MAC or by IP address, are the offending ones.  Or, change the message to say, "At least one of the EFBs bound to this Stratux is running an incompatible...".

If possible, enable "Replay Logs", reproduce the problem, and provide a copy of the logs in http://192.168.10.1/logs/stratux/ and http://192.168.10.1/logs/stratux.log.

no need

**Comment by cyoung** [comment]
Good point, I'll add the hostname of the device and the IP to the message.
