### ISSUE TITLE
New (slight) feature request

### ISSUE THREAD

**Issue by skypuppy** [cyoung/stratux#357]
1. Stratux version:
2. Stratux config:

    SDR
      [ ] single
      [x ] dual

    GPS
      [x ] yes
      [ ] no
      type:MTK 3339 serial and Sirf USB

    AHRS
      [ x] yes
      [ ] no

    power source:  wall-wart, battery, ships power

    usb cable:

3. EFB app and version: (e.g., WingX Pro7 8.6.2)
 iFlyGPS 9.4

    EFB platform: (e.g., iOS 9.2)
  Android 5 something

    EFB hardware: (e.g., iPad Mini 2)
  Galaxy Tab S 10.2 and Galaxy Tab 10.1

4. Description of your issue:

With the ever increasing popularity of the MTK 3339 GPS and as AvSquirrel has it working quite well, please add the MTK3339 into the mainstream code, along with the VK part.  Easy coding, low maintenance.

If possible, enable "Replay Logs", reproduce the problem, and provide a copy of the logs in http://192.168.10.1/logs/stratux/ and http://192.168.10.1/logs/stratux.log.

**Comment by cyoung** [comment]
We can keep an open dialogue about this in #315, no need for two issues. Thanks.
