### ISSUE TITLE
Audible Traffic Alerts?

### ISSUE THREAD

**Issue by glwilkins** [cyoung/stratux#364]
Will we ever see audible traffic alerts in any new release?

**Comment by peepsnet** [comment]
That is what the EFB does...

**Comment by ScraboTower** [comment]
Not all of them

**Comment by skypuppy** [comment]
iFlyGPS does.  You can turn the sound and/or visual alarms on or off.

**Comment by JohnOCFII** [comment]
> Will we ever see audible traffic alerts in any new release?

From my understanding of what the Web interface design goals for Stratux are -- probably not.  The Web interface is mainly for setup and confirmation of functionality of the Stratux components.  Features such as audible traffic alerts are better suited for one of the EFB targets, such as iFly, WingX, ForeFlight, etc.

**Comment by glwilkins** [comment]
I haven't had my stratux in the air yet to test this out

Will it work via Bluetooth to for flight?
Does it use voice comands like:
"Traffic at 10 o'clock low"?

Thanks for all the comments.

**Comment by cyoung** [comment]
Stratux itself doesn't output any audio. What app are you using it with? ForeFlight does give traffic alerts when it sees a target (I think) within 2nm.

**Comment by AMNegron** [comment]
FltPlan Go also has that functionality, but I have not tested it

**Comment by peepsnet** [comment]
lol... WORKS!!

**Comment by cyoung** [comment]
@glwilkins - the app you're using with stratux likely already does this.
