### ISSUE TITLE
gen_gdl90 crashes in 5da86d919f

### ISSUE THREAD

**Issue by peepsnet** [cyoung/stratux#369]
1. Stratux version:
2. Stratux config:

    SDR
      [ ] single
      [ X ] dual

    GPS
      [ x ] yes
      [ ] no
      type:

    AHRS
      [ x ] yes
      [ ] no

    power source:
2.1A Wal plug with portacable 21AWG cable
    usb cable:

3. EFB app and version: (e.g., WingX Pro7 8.6.2)

    N/A

4. Description of your issue:

I my Pi2 & Pi3 run over night and when I woke up both showed the stratux service running but no connection. looked at htop/top and no gen_gdl90. Dump1090 was stil running. 

Both SDR's still in use though. varified using `rtl_eeprom -d 0/1`

a `service stratux restart` returns all to normal

If possible, enable "Replay Logs", reproduce the problem, and provide a copy of the logs in http://192.168.10.1/logs/stratux/ and http://192.168.10.1/logs/stratux.log.

**Comment by cyoung** [comment]
Fixed by PR #386.
