### ISSUE TITLE
Edimax driver doesn't load

### ISSUE THREAD

**Issue by admiral1701** [cyoung/stratux#378]
4. Description of your issue:  I downloaded and ran the latest build from official stratux webpage.  As far as I can tell, the driver or the configure file does not load the wifi adapter.  I have the edimax ew-7811un.  

Dump1090 seems to wiz right along, I just can't connect the iPad to the pi network.  I put the edimax in my laptop and it worked wonderfully.

I'm a computer guy just not a Linux guy.  This has been a steep learning curve.

Any help is appreciated.

**Comment by peepsnet** [comment]
So what type pi? And all that other stuff...

**Comment by admiral1701** [comment]
Pi2 b+

**Comment by admiral1701** [comment]
Dude.  Thanks again.. Read the response on the Reddit forum

**Comment by cyoung** [comment]
Ah, the Pi2B+ again...
