### ISSUE TITLE
Log from UAT today - 0.3b1

### ISSUE THREAD

**Issue by JohnOCFII** [cyoung/stratux#39]
I'm hoping that the log file is persistent across shutdowns, as I flew for about 90 minutes, shutdown, drove home, powered up and grabbed this log.

No known crashes.  About halfway through the flight the ForeFlight display did show 'o' for aircraft altitudes.  Selecting the target did show the correct altitude.  I've attached a screen shot in addition to the UAT log.

Here is the zip'd up log file:  https://dl.dropboxusercontent.com/u/2506999/stratux-uat.log.zip

![img_0134](https://cloud.githubusercontent.com/assets/7844212/9834195/0f640eae-5976-11e5-8e08-0f436b6c2c77.jpg)

**Comment by cyoung** [comment]
Thanks for this! Logs are persistent across reboots, but there is a logrotate process that may move them around and/or compress them. You can see all of the logs in the folder http://192.168.10.1/logs/. If it was rotated, it will still have the "stratus-uat.log" prefix.

**Comment by cyoung** [comment]
![pps](https://cloud.githubusercontent.com/assets/57193/9876698/03dbbba6-5b86-11e5-81a8-84d7227be66e.png)

**Comment by cyoung** [comment]
Thanks @JohnOCFII.
