### ISSUE TITLE
stratux and gpsd

### ISSUE THREAD

**Issue by skypuppy** [cyoung/stratux#397]
1. Stratux version:
2. Stratux config:

    SDR
      [ ] single
      [ ] dual

    GPS
      [ ] yes
      [ ] no
      type:

    AHRS
      [ ] yes
      [ ] no

    power source:

    usb cable:

3. EFB app and version: (e.g., WingX Pro7 8.6.2)

    EFB platform: (e.g., iOS 9.2)

    EFB hardware: (e.g., iPad Mini 2)

4. Description of your issue:

Have tested gpsd on Pi3 with serial MTK3339 and Sirf with USB.  With a couple tweaks (thanks again, Adafruit!) gpsd is confirmed working on serial device on the Pi3!  Needs a bit more testing but shouldn't be difficult or time-consuming.  Just had to jump in and let you guys know these preliminary findings, before all tests were accomplished.

I wish I could do a 2D chart here, but:
1. serial:
sockets works, memory mapped - untested, dBus - getting dBus errors as if stratux and Jessie have not enabled it.  More testing needed

2. Sirf via USB, got tired and couldn't figure out which USB port to name, or baudrate.  lsusb no help.

Curiously, even with stratux service running or not and gpsd running (without sockets,) the serial port could still talk to gpsmon and cgps.  

I believe gpsd is now ready for prime time with stratux on the Pi if the USB and ublox can be confirmed.  I don't have a ublox device.  The gpsd website says they have suipport for both Sirf and ublox but I'm one who likes to see it before I use it.  :)

If possible, enable "Replay Logs", reproduce the problem, and provide a copy of the logs in http://192.168.10.1/logs/stratux/ and http://192.168.10.1/logs/stratux.log.

**Comment by peepsnet** [comment]
#328
