### ISSUE TITLE
Collision avoidance map and alerts - Enhancement ?

### ISSUE THREAD

**Issue by kalustian** [cyoung/stratux#411]
1. Stratux version:
2. Stratux config:

    SDR
      [ ] single
      [ ] dual

    GPS
      [ ] yes
      [ ] no
      type:

    AHRS
      [ ] yes
      [ ] no

    power source:

    usb cable:

3. EFB app and version: (e.g., WingX Pro7 8.6.2)

    EFB platform: (e.g., iOS 9.2)

    EFB hardware: (e.g., iPad Mini 2)

4. Description of your issue:

I dont want to take you out from your main project objective, but wanted to propose a future enhancement within the Web-UI. 

You already have all target/aircraft altitude and locations, including the GPS information as well. It will be nice to map ( using Web -UI ? ) all targets near your GPS position and alert via GPIO/LED or produce a sound of those targets within certain distance and altitude of your position reported via the GPS.  

The idea is to have an offline "Collision avoidance"  not dependent to any 3rd party application.

Note - when I am referring to "map", I am not talking about an actual geo-world map...but a graphical representation of the aircraft/targets vs your gps location.

**Comment by cyoung** [comment]
@kalustian - thanks for the suggestion. We'll close this for now but consider it in the future.

It's not quite as simple as it seems - we need to make sure the browser has a reliable connection to stratux and doesn't lag. This is a problem that is easier solved in an app, but we'll see about it later.
