### ISSUE TITLE
Virus Scan PSA

### ISSUE THREAD

**Issue by Axtel4** [cyoung/stratux#414]
1. Stratux version: Version: v0.8r2 (86859f32f5)
2. Stratux config:

    SDR
      [ ] single
      [ X ] dual

    GPS
      [ X ] yes
      [ ] no
      type:

    AHRS
      [ ] yes
      [ X ] no

    power source:  Ship power via Anker Power Drive 2

    usb cable: Heavy duty

3. EFB app and version: (e.g., WingX Pro7 8.6.2) NA

    EFB platform: (e.g., iOS 9.2) Android

    EFB hardware: (e.g., iPad Mini 2) Asus TF-300, LG G3, and Windows Browser Web IU

4. Description of your issue:
I posted this over on [Reddit] (https://www.reddit.com/r/stratux/comments/4jbmrx/virus_scan_psa/) , but I am placing it here also incase any of the Software Gurus have a way to accomplish the same thing on the Stratux side.

> I ran into an issue that took a couple of days to sort out.  

> I discovered that ESET NOD32 Antivirus pushed an update that crippled the Web UI Status and Traffic pages on my desktop machine.  The R-Pi / Stratux connection via a wired router connection or through a WiFi connection were impacted.  It did not affect any connections with my Android devices or Windows computers that were not running ESET NOD32.

> Symptom: On the Status page I would connect to Stratux and then immediately get a Disconnect.  It would then cycle between Disconnect and Connect.  The Traffic page would not populate while the GPS page still showed location on the map.  I observed the same behaviour with my Chome and Firefox browsers.  It did not impact any SSH or FTP actions between the Deskltop and Stratux.  

> Cause / Solution: It turned out that the AV was blocking the Web Socket data after a connect request.  To correct the issue I had to “Whitelist” the Raspberry Pi IP Addresse(s) within the AV.  After making the change, to Web UI returned to full functionality.

If possible, enable "Replay Logs", reproduce the problem, and provide a copy of the logs in http://192.168.10.1/logs/stratux/ and http://192.168.10.1/logs/stratux.log.

**Comment by AvSquirrel** [comment]
Possible external issue with ESET NOD32?
https://forum.eset.com/topic/8355-protocol-filtering-breaks-websockets-after-update-at-5052016/

**Comment by cyoung** [comment]
Thanks!
