### ISSUE TITLE
Stratux Logo?

### ISSUE THREAD

**Issue by ayarbro** [cyoung/stratux#419]
Wondering if anyone is interested in creating an official logo for the project?  Can't seem to find one anywhere, but not surprising since everyone on the dev group is busy making it way better everyday, not drawing silly logos.  Drawing a case up for my rpi3 and want to put a stratux logo on top.  If I come up with something I think is acceptable I'll put it here.  Should I ask for submitions on reddit?

Thanks!

-Anders

**Comment by cyoung** [comment]
https://github.com/cyoung/stratux/tree/master/web/img
https://github.com/cyoung/stratux/blob/master/web/img/screen-1536x2008.png

This is the official logo now. If you want to design a new one, re-open the issue and post here and we'd gladly consider it. Thanks for the suggestion.
