### ISSUE TITLE
After update DEV build may 16 ... GPS Disconnected

### ISSUE THREAD

**Issue by mmaitre74** [cyoung/stratux#424]
1. Stratux version:
v0.8r2-aae8e925ef
v0.8r2-744240da50
v0.8r2-7881d6c53a
v0.8r2-b9951241a5

2. Stratux config:

    SDR
      [ ] single
      [X ] dual

    GPS : RY835AI
      [X ] yes
      [ ] no
      type:

    AHRS
      [X ] yes
      [ ] no

    power source: 5V adaptor

    usb cable: GPS micro-USB connection

3. EFB app and version: (e.g., WingX Pro7 8.6.2)

    EFB platform: (e.g., iOS 9.2)

    EFB hardware: (e.g., iPad Mini 2)

4. Description of your issue: THe Gps is alway disconnected .  Version build b9951241a5 and up to aae8e925ef.

If possible, enable "Replay Logs", reproduce the problem, and provide a copy of the logs in http://192.168.10.1/logs/stratux/ and http://192.168.10.1/logs/stratux.log.

**Comment by cyoung** [comment]
Which GPS unit?

**Comment by mmaitre74** [comment]
Sorry : RY835AI

 

De : cyoung [mailto:notifications@github.com] 
Envoyé : 23 mai 2016 19:56
À : cyoung/stratux <stratux@noreply.github.com>
Cc : mmaitre74 <mmaitre@sympatico.ca>; Author <author@noreply.github.com>
Objet : Re: [cyoung/stratux] After update DEV build may 16 ... GPS Disconnected (#424)

 

Which GPS unit?

**Comment by cyoung2** [comment]
Got it. We'll have an updated version later tonight with a fix.

**Comment by AvSquirrel** [comment]
#418 ?

**Comment by cyoung** [comment]
@AvSquirrel 's PR integrated which fixes it here: http://updates.stratux.me/builds/update-stratux-v0.8r2-47271df764.sh

@mmaitre74 - give it a try and let us know if it fixes it, reopen if any problem.

**Comment by mmaitre74** [comment]
Working now. Issue Fix.
