### ISSUE TITLE
Suggest change "EFB App unsupported" message from -Error- to -Caution-

### ISSUE THREAD

**Issue by JohnOCFII** [cyoung/stratux#432]
1. Stratux version: v0.9b1 (8910781)
2. Stratux config:

    SDR
      [ ] single
      [X] dual

    GPS
      [X] yes
      [ ] no
      type: RY835AI

    AHRS
      [X] yes
      [ ] no

    power source: panel

    usb cable: PortaPow

3. EFB app and version: (e.g., WingX Pro7 8.6.2) ForeFlight 7.6.1

    EFB platform: (e.g., iOS 9.2) iOS 9.3.2

    EFB hardware: (e.g., iPad Mini 2) iPad Air 2

4. Description of your issue:

The new message about an EFB App not supporting the Stratux is listed as an Error.  While I appreciate the notification, could the message be dismissed after reading?  If not, could the language be changed to indicate "Caution" instead of Error, perhaps with a yellow icon and black text?  

To me, an error indicates the application noticed something that isn't working.  This is more of a cautionary note that something -might- not work.

Thanks for your consideration.

If possible, enable "Replay Logs", reproduce the problem, and provide a copy of the logs in http://192.168.10.1/logs/stratux/ and http://192.168.10.1/logs/stratux.log.

**Comment by cyoung** [comment]
We'll keep it as-is for now.
