### ISSUE TITLE
0.9b3 Trip report

### ISSUE THREAD

**Issue by Axtel4** [cyoung/stratux#449]
1. Stratux version:  0.9b3 stratux-v0.9b3-9d3060af95.sh
2. Stratux config: 
   
   SDR
     [ ] single
     [ X ] dual
   
   GPS
     [ X ] yes
     [ ] no
     type: VK-172
   
   AHRS
     [ ] yes
     [ N ] no
   
   R-Pi
       [ ] Zero
       [ X ] 2B
       [ ] 3
   
     power source:  Ship power
   
     usb cable:  Anker HD
3. EFB app and version: (e.g., WingX Pro7 8.6.2)   DroidEFB 2.1.3
   
   EFB platform: (e.g., iOS 9.2)  Android KitKat
   
   EFB hardware: (e.g., iPad Mini 2)  ASUS TF300 Table / LG G3 
4. Description of your issue:
   I got about 4 hours of flying in with 0.9b3 today.  Prior to departure I started Stratux, connected the EFB devices and enabled logging (not verbose).

While on climb out to altitude (IFR flight plan) I received an EFB warning " No GPS signal or signal suspect" warning.  I switched to my device's internal GPS and waited until time would to troubleshoot.

Once at altitude, I switch to the Statux Web UI and saw a list of "WARNING SQLite lite logging behind".  I disabled logging and tried to connect to the GPS again.  No joy.  Note, at this time I was still receiving traffic, Weather and NexRad updates.  I had to turn off logging and report Stratux to recover the GPS connection. 

Turning logging back on it only took about 5 minutes for the problem to reappear.  I rebooted again and left logging of for the rest of my flight.  I did not have and GPS connection issues with the logging turned off.  Note: This happened with both devices I had connected to Stratux.

Edit: Added screenshots.  Added R-Pi type.

Screenshot of Logging Errors:
![screenshot_2016-06-25-11-24-01](https://cloud.githubusercontent.com/assets/15059010/16360113/66f81990-3b15-11e6-9ddf-9ccc02f532b4.jpg)

Screen shot of EFB warning:
![screenshot_2016-06-25-11-24-37](https://cloud.githubusercontent.com/assets/15059010/16360072/a8c0e340-3b13-11e6-8756-fd3304fe5171.png)

Screenshot showing EFB GPS source:
![screenshot_2016-06-25-11-25-00](https://cloud.githubusercontent.com/assets/15059010/16360073/c373f25e-3b13-11e6-9152-552491899848.png)

Screenshot showing received towers:
![screenshot_2016-06-25-11-28-26](https://cloud.githubusercontent.com/assets/15059010/16360074/d6659584-3b13-11e6-8fd3-562c5f40fefe.png)

Screenshot after reboot attempt:
![screenshot_2016-06-25-11-28-40](https://cloud.githubusercontent.com/assets/15059010/16360078/f12c5e3e-3b13-11e6-99ca-fb1bd4aa9f98.png)

Screenshot after and extended logging period:
![screenshot_2016-06-25-12-18-04](https://cloud.githubusercontent.com/assets/15059010/16360080/ff85eef0-3b13-11e6-85d6-80a871eb4c5f.png)

If possible, enable "Replay Logs", reproduce the problem, and provide a copy of the logs in http://192.168.10.1/logs/stratux/ and http://192.168.10.1/logs/stratux.log.  I'll see if anything was captured in the logs.

**Comment by Ergonomicmike** [comment]
Kinda cross posting here, 'cause I said this under another issue. I flew 2 hours today w/ v0.9b2 (fresh image) with no issues. BU-353. Logging disabled. NEXRAD coming in. Guess I'll have to put "Enable logging" on my test card for next time.

Interestingly, no AIRMETs issued today, despite there being mod turb.

**Comment by Axtel4** [comment]
No issues after turning off logging in 0.9b3.  The my entire 2 hour return flight - sans logging - was without error.

**Comment by Ergonomicmike** [comment]
Am thinking this has been fixed and so this issue can be closed? I inadvertently enabled sqlite logging a few days ago with v1.3.b2. Ran for at least an hour with no error messages.

**Comment by cyoung** [comment]
The logging options were moved to "developer mode" only.

https://github.com/cyoung/stratux/commit/da28af53c08a8c0c6a4d004c3b3b84a89b11c3b9
