### ISSUE TITLE
Stratux data to iPad cuts out after a few minutes.  Uses NooElec Mini2+ with antenna suppied by NooElec.  Any ideas on why, antenna ??

### ISSUE THREAD

**Issue by JM9055** [cyoung/stratux#453]
1. Stratux version:0.9.5
2. Stratux config:

    SDR
      [x ] single
      [ ] dual

    GPS
      [ ] yes
      [ x] no
      type:

    AHRS
      [ ] yes
      [ x] no

    power source:Aircraft

    usb cable:

3. EFB app and version: ForeFlight

    EFB platform: 7.6.1

    EFB hardware: iPad 2

4. Description of your issue:  Cutting out signal to iPad

If possible, enable "Replay Logs", reproduce the problem, and provide a copy of the logs in http://192.168.10.1/logs/stratux/ and http://192.168.10.1/logs/stratux.log.

**Comment by cyoung** [comment]
Stratux version?

**Comment by JM9055** [comment]
I assume I need to insert the micro chip in the adapter to find version?

**Comment by JM9055** [comment]
Date is 3-16-2016 on version program.

**Comment by cyoung** [comment]
Should be fixed with v1.0r1, update to the latest version linked on the website (http://stratux.me/). Thanks.
