### ISSUE TITLE
Can I use a USB to serial cable to send traffic/wx data to a GRT Avionics HxR EFIS display. The display has serial ports that can be assigned to "ADSB."  I have the latest Stratux kit on a Pi 3.  WIFI works fine with my Foreflight app, but looking to get info on EFIS display.  Thanks, Mike.

### ISSUE THREAD

**Issue by cowboy737** [cyoung/stratux#480]
1. Stratux version:
2. Stratux config: single/dual SDR, GPS yes/no (type?), AHRS yes/no, battery, battery cable.
3. EFB app and version (e.g., WingX Pro7 8.6.2). EFB platform (e.g., iOS 9.2). EFB hardware (e.g., iPad Mini 2).
4. Description of your issue. If possible, enable "Replay Logs", reproduce the problem, and provide a copy of the logs in http://192.168.10.1/logs/stratux/ and http://192.168.10.1/logs/stratux.log.

**Comment by cyoung** [comment]
@cowboy737 - http://www.grtavionics.com/StratuxSupplement.pdf
