### ISSUE TITLE
Can't access web page or device with FF

### ISSUE THREAD

**Issue by Ylinen** [cyoung/stratux#50]
I have a Raspberry Pi 2 Model B.  The right wifi.

I put the latest image on the SD card and boot.  When I connect a HDMI cable and monitor to see what is happening.  It boots up and goes to the Raspberry Pi Config page.

I can't access the web page.  I see nothing in fore flight when I connect to the stratux wifi which works.

What is wrong?

I also see no log fixes on the SD card nor an ETC directory.  Only directory is Objects.

I also can't SSH to the device.

Disregard.  I don't have the Pi 2.  I have the Pi + B.

**Comment by cyoung** [comment]
Pi B+ is your problem. The binary won't run on it. Upgrade to the Pi2.
