### ISSUE TITLE
synthetic vision

### ISSUE THREAD

**Issue by 9foxlabs** [cyoung/stratux#517]
1. Stratux version:
2. Stratux config:

    SDR
      - [ ] single
      - [ ] dual

    GPS
      - [ ] yes
      - [ ] no
      type:

    AHRS
      - [ ] yes
      - [ ] no

    power source:

    usb cable:

3. EFB app and version: (e.g., WingX Pro7 8.6.2)

    EFB platform: (e.g., iOS 9.2)

    EFB hardware: (e.g., iPad Mini 2)

4. Description of your issue: No issue, but when do you think synthetic vision will be available? It's one of my primary reasons for purchasing the name neanderthal one. I do appreciate the open source of it though

If possible, enable "Replay Logs", reproduce the problem, and provide a copy of the logs in http://192.168.10.1/logs/stratux/ and http://192.168.10.1/logs/stratux.log.

**Comment by 9foxlabs** [comment]
"Purchasing the name brand one", not "neanderthal". Lol

**Comment by Ergonomicmike** [comment]
Synthetic Vision is a function of the EFB. (Not the Stratux, per se.)

**Comment by cyoung** [comment]
@9foxlabs - the neanderthal AHRS are more advanced than ours at the moment. The terrain portion of synthetic vision does not require AHRS, however, just a GPS position. You could use synthetic vision for obstacles using stratux as a GPS source, just no attitude reference.
