### ISSUE TITLE
Feature Request - Development Stack On Release Images

### ISSUE THREAD

**Issue by ssokol** [cyoung/stratux#52]
It would be quite useful if the Golang development stack came preinstalled on releases - at least any alpha / beta releases. The software is already available in /root/stratux. If would be convenient if that could be edited, compiled and deployed without having to connect the device to the Internet and manually install the development tools.

Alternately, we could include a script to quickly install the necessary software.

**Comment by cyoung** [comment]
Makes the image about 60MB bigger.

**Comment by JohnOCFII** [comment]
> Alternately, we could include a script to quickly install the necessary software.

Maybe go with this option -- space only used for those who want/need it, but makes it easy to get installed.

**Comment by ssokol** [comment]
I'm not sure anyone would notice the extra 60 MB - either in storage used
or in the additional download time - but I'm good either way.

On Mon, Sep 21, 2015 at 1:00 PM, JohnOCFII <notifications@github.com> wrote:

> Alternately, we could include a script to quickly install the necessary
> software.
>
> Maybe go with this option -- space only used for those who want/need it,
> but makes it easy to get installed.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cyoung/stratux/issues/52#issuecomment-142062081>.
>



-- 
Steven Sokol
408 Camelot Drive
Liberty, MO 64068

mobile: +1 816-806-8844
fax: +1 816-817-0441

**Comment by haykinson** [comment]
+1 on the request to just add it to the image. This way the environment is ready for making changes.

**Comment by bradanlane** [comment]
Just an FYI for those who forgot what "most of America" has for internet connectivity, that extra 60mb translated to another 3-6 minutes of download.

**Comment by ssokol** [comment]
True, but the process of installing and configuring the dev tools is also a
lengthy process. I'm all for stripping it down to the minimal size for
stable / production releases, but it seems like a win to have the tools in
place on any pre-release / alpha / beta build.

On Mon, Sep 21, 2015 at 1:24 PM, bradanlane <notifications@github.com>
wrote:

> Just an FYI for those who forgot what "most of America" has for internet
> connectivity, that extra 60mb translated to another 3-6 minutes of download.
>
>
> > On Sep 21, 2015, at 2:05 PM, Ilya Haykinson <notifications@github.com>
> wrote:
> >
> > +1 on the request to just add it to the image. This way the environment
> is ready for making changes.
> >
> > —
> > Reply to this email directly or view it on GitHub.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cyoung/stratux/issues/52#issuecomment-142067319>.
>



-- 
Steven Sokol
408 Camelot Drive
Liberty, MO 64068

mobile: +1 816-806-8844
fax: +1 816-817-0441

**Comment by cyoung** [comment]
Already included for debug images, 60MB comment for documentation for non-debug release images.

**Comment by ssokol** [comment]
Hmmm... I'm running 0.3b3 and I don't find the go complier, mercurial, or
any of the other build tools on the image. There's a copy of the source in
/root/stratux, but I have to manually install go, etc. to build it.

On Mon, Sep 21, 2015 at 1:34 PM, cyoung <notifications@github.com> wrote:

> Already included for debug images, 60MB comment for documentation for
> non-debug release images.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cyoung/stratux/issues/52#issuecomment-142069790>.
>



-- 
Steven Sokol
408 Camelot Drive
Liberty, MO 64068

mobile: +1 816-806-8844
fax: +1 816-817-0441

**Comment by cyoung** [comment]
Already included for future debug images, 60MB comment for documentation for non-debug release images.

**Comment by ssokol** [comment]
Ack. Thanks!

On Mon, Sep 21, 2015 at 1:45 PM, cyoung <notifications@github.com> wrote:

> Already included for future debug images, 60MB comment for documentation
> for non-debug release images.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cyoung/stratux/issues/52#issuecomment-142072459>.
>



-- 
Steven Sokol
408 Camelot Drive
Liberty, MO 64068

mobile: +1 816-806-8844
fax: +1 816-817-0441
