### ISSUE TITLE
Any plans to support CanaKit's Wifi adaptor?

### ISSUE THREAD

**Issue by TCHWRX** [cyoung/stratux#53]
Just checking :)

**Comment by cyoung** [comment]
Not particularly. Do you have any connection with the company?

**Comment by TCHWRX** [comment]
No connection with the company except that I bought my PI from them and that's the WiFi adapter they sent me and it does not work with your software.
I have already ordered one of the supported ones instead.

**Comment by cyoung** [comment]
The edimax has been tested quite a bit, so until someone wants to set up the CanaKit and do some extensive testing - no plans really. It's also a lot of work for zero net gain, as the cost of the two are exactly the same and don't appear to have any advantages over one another.
