### ISSUE TITLE
Just cracked my new SD card pre loaded with Stratux

### ISSUE THREAD

**Issue by x2flya320** [cyoung/stratux#532]
1. Stratux version:??
2. Stratux config: Rasberry Pi 3 model B

    SDR
    DUAL
      - [x ] dual

    GPS
     NO
      - [ x] no
      type:

    AHRS
      - [ ] yes
      - [ x] no

    power source: Wall

    usb cable:

3. EFB app and version: (e.g., WingX Pro7 8.6.2) Foreflight 8.1.1

    EFB platform: (e.g., iOS 9.2) IOS 10.1.1

    EFB hardware: (e.g., iPad Mini 2) Ipad Pro

4. Description of your issue: Just cracked my Micro SD card with the pre loaded Stratux software.. Grrr Any way to download it and put it one of my spare Cards? Any help is greatly appreciated. I just got it and cracked it when putting the case together.. 
Cheers, Greg

If possible, enable "Replay Logs", reproduce the problem, and provide a copy of the logs in http://192.168.10.1/logs/stratux/ and http://192.168.10.1/logs/stratux.log.

**Comment by cyoung** [comment]
Greg, send me an email at cyoung@gmail.com. Thanks!
