### ISSUE TITLE
error code when starting fancontrol.py

### ISSUE THREAD

**Issue by roperf15** [cyoung/stratux#543]
1. Stratux version:1.0r1 build dc62a3abba (9/21/2017)
2. Stratux config: pi 3

    SDR
      - [ ] single
      - [X ] dual

    GPS
      - [X ] yes
      - [ ] no
      type:

    AHRS
      - [ ] yes
      - [X ] no

    power source: battery and shore power

    usb cable:

3. EFB app and version: (e.g., WingX Pro7 8.6.2) FF newest

    EFB platform: (e.g., iOS 9.2) IOS

    EFB hardware: (e.g., iPad Mini 2) IPAD 2

4. Description of your issue:

When trying to run fancontrol.py from the command line I get the error below.  I went back to the original 1.0r1 image and ran fancontrol.py with no issues.  I installed selected updates sequentially and tested fancontrol.py on each one.  They all worked until I got to dc62a3abba (9/21/2017). I tested several of the newer builds as well and got the same error. The error seems to have been introduced after f477a8366e (9/5/2017).  That build tested good.  I did not test 31bbf1bc1b (9/19/21).  I'm a noob and I can't tell where the possible problem might be when looking at the code.  I can see that 11 sep is when fancontrol.py was daemonized.   Here is the received error.

root@raspberrypi:/usr/bin# python fancontrol.py
Traceback (most recent call last):
  File "fancontrol.py", line 12, in <module>
    from daemon import runner
ImportError: No module named daemon

thx
Jim

If possible, enable "Replay Logs", reproduce the problem, and provide a copy of the logs in http://192.168.10.1/logs/stratux/ and http://192.168.10.1/logs/stratux.log.

**Comment by johnpayne** [comment]
Jim,  You might be missing the python-daemon package?
You could try installing it:
`sudo apt-get install python-daemon`

**Comment by cyoung** [comment]
@roperf15 - which base image?

**Comment by roperf15** [comment]
@cyoung - I'm a noob and not sure what you are asking.  I started with the full base image of 1.0r1 downloaded from this site and then got the update files from the list of daily builds.  Does that answer your question?  Thx!

Jim

**Comment by peepsnet** [comment]
https://github.com/cyoung/stratux/issues/493

**Comment by low-and-slow** [comment]
I can't get the fancontrol.py script to run like I was able to with the stable version, however I don't need to. A lot has changed since the stable version, including which GPIO pin is called out in the code.  It was pin 11, but now it's pin 12. Give that a shot.

**Comment by roperf15** [comment]
I did what johnpayne suggested above and it solved the problem.  Thanks for the help!

sudo apt-get install python-daemon
