### ISSUE TITLE
Help, Possibly software issue?!

### ISSUE THREAD

**Issue by raylow78** [cyoung/stratux#583]
1. Stratux version: **v1.2r1**
2. Stratux config:

    SDR
      - [ ] single
      - [x ] dual

    GPS
      - [x] yes
      - [ ] no
      type: iPad has internal GPS

    AHRS
      - [ ] yes
      - [ ] no

    power source:**EasyAcc 6000mAh Ultra-Slim External Battery** 

    usb cable:

3. EFB app and version: (e.g., WingX Pro7 8.6.2) **ForeFlight 9.0**

    EFB platform: (e.g., iOS 9.2) **iOS 10.3.1**

    EFB hardware: (e.g., iPad Mini 2) **iPad Mini 4**

4. Description of your issue:

I just put together my dual band stratux using the items listed on the website. The only thing I did not purchase was the optional GPS because my iPad has an internal one built it. Once I powered it up and loaded ForeFlight nothing happens. The device powers on with a red light and steady green light, it does not blink. ForeFlight picks up that it is connected to an ADS-B however it will not display any traffic, weather or ads-b towers. I can hear airplanes flying overhead so I know they are there lol.

I don't think the software is loading properly onto the micro sd. I am running pi filler on my mac (OS X El Captain 10.11.6). I have unzipped the file before running it through pi filler. It says that all of the data is loaded on and to go ahead and plug it into the motherboard. However, if I place the micro sd back into my computer it shows the original data on the card rather than the statux software.

What should I do to troubleshoot?

If possible, enable "Replay Logs", reproduce the problem, and provide a copy of the logs in http://192.168.10.1/logs/stratux/ and http://192.168.10.1/logs/stratux.log.

2016/02/26 01:18:36 Stratux v1.2r2 (bcd62e7c00e132dada7ed7cbf0a5d28133916ff1) starting.
2016/02/26 01:18:36 Entered uatReader() ...
2016/02/26 01:18:36 can't read settings /etc/stratux.conf: open /etc/stratux.conf: no such file or directory
2016/02/26 01:18:37 ===== UAT Device Name  : Generic RTL2832U OEM =====
2016/02/26 01:18:37 ===== UAT Device Serial: stratux:978=====
2016/02/26 01:18:37     GetTunerType: RTLSDR_TUNER_R820T
2016/02/26 01:18:37     SetTunerGainMode Successful
2016/02/26 01:18:37     SetTunerGain Successful
2016/02/26 01:18:37     GetTunerGain: 480
2016/02/26 01:18:37     SetSampleRate - rate: 2083334
2016/02/26 01:18:37     GetSampleRate: 2083334
2016/02/26 01:18:37     GetXtalFreq - Rtl: 28800000, Tuner: 28800000
2016/02/26 01:18:37     SetXtalFreq - Center freq: 28800000, Tuner freq: 28800000
2016/02/26 01:18:37     SetCenterFreq 978MHz Successful
2016/02/26 01:18:37     GetCenterFreq: 978000000
2016/02/26 01:18:37     Setting Bandwidth: 1000000
2016/02/26 01:18:38     SetTunerBw 1000000 Successful
2016/02/26 01:18:38     ResetBuffer Successful
2016/02/26 01:18:38     GetFreqCorrection: 0
2016/02/26 01:18:38     SetFreqCorrection 0 Successful
2016/02/26 01:18:38 Entered UAT read() ...
2016/02/26 01:18:38 ===== ES Device Serial: stratux:1090 PPM 0 =====
2016/02/26 01:18:38 Entered ES read() ...
2016/02/26 01:18:38 Executed /usr/bin/dump1090 successfully...
2016/02/26 01:18:41 readBMP180(): input/output error
2016/02/26 01:19:06 client connected: 192.168.10.10:4000 (Raymonds-iPad).
2016/02/26 01:19:06 stats [started: 30 seconds ago]
2016/02/26 01:19:06  - Disk bytes used = 1.4 GB (76.4 %), Disk bytes free = 440 MB (23.6 %)
2016/02/26 01:19:06  - CPUTemp=36.48 deg C, MemStats.Alloc=2.3 MB, MemStats.Sys=6.6 MB, totalNetworkMessagesSent=0
2016/02/26 01:19:06  - UAT/min 0/0 [maxSS=0.00%], ES/min 179/179, Total traffic targets tracked=1
2016/02/26 01:19:06  - Network data messages sent: 0 total, 0 nonqueueable.  Network data bytes sent: 0 total, 0 nonqueueable.
2016/02/26 01:19:06  - Last GPS fix: 30 seconds ago, GPS solution type: 0 using 0 satellites (0/0 seen/tracked), NACp: 0, est accuracy 999999.00 m
2016/02/26 01:19:06  - GPS vertical velocity: 0.00 ft/sec; GPS vertical accuracy: 999999 m
2016/02/26 01:19:36 client connected: 192.168.10.11:4000 (Raymonds-MBP).
2016/02/26 01:19:36 stats [started: 1 minute ago]
2016/02/26 01:19:36  - Disk bytes used = 1.4 GB (76.4 %), Disk bytes free = 440 MB (23.6 %)
2016/02/26 01:19:36  - CPUTemp=37.01 deg C, MemStats.Alloc=3.3 MB, MemStats.Sys=7.7 MB, totalNetworkMessagesSent=21
2016/02/26 01:19:36  - UAT/min 0/0 [maxSS=0.00%], ES/min 216/216, Total traffic targets tracked=1
2016/02/26 01:19:36  - Network data messages sent: 15 total, 15 nonqueueable.  Network data bytes sent: 250 total, 250 nonqueueable.
2016/02/26 01:19:36  - Last GPS fix: 1 minute ago, GPS solution type: 0 using 0 satellites (0/0 seen/tracked), NACp: 0, est accuracy 999999.00 m
2016/02/26 01:19:36  - GPS vertical velocity: 0.00 ft/sec; GPS vertical accuracy: 999999 m
2016/02/26 01:20:06 stats [started: 1 minute ago]
2016/02/26 01:20:06  - Disk bytes used = 1.4 GB (76.4 %), Disk bytes free = 440 MB (23.6 %)
2016/02/26 01:20:06  - CPUTemp=37.55 deg C, MemStats.Alloc=1.4 MB, MemStats.Sys=8.8 MB, totalNetworkMessagesSent=48
2016/02/26 01:20:06  - UAT/min 0/0 [maxSS=0.00%], ES/min 37/216, Total traffic targets tracked=1
2016/02/26 01:20:06  - Network data messages sent: 30 total, 30 nonqueueable.  Network data bytes sent: 500 total, 500 nonqueueable.
2016/02/26 01:20:06  - Last GPS fix: 1 minute ago, GPS solution type: 0 using 0 satellites (0/0 seen/tracked), NACp: 0, est accuracy 999999.00 m
2016/02/26 01:20:06  - GPS vertical velocity: 0.00 ft/sec; GPS vertical accuracy: 999999 m
2016/02/26 01:20:36 stats [started: 1 minute ago]
2016/02/26 01:20:36  - Disk bytes used = 1.4 GB (76.4 %), Disk bytes free = 440 MB (23.6 %)
2016/02/26 01:20:36  - CPUTemp=38.63 deg C, MemStats.Alloc=2.4 MB, MemStats.Sys=8.8 MB, totalNetworkMessagesSent=75
2016/02/26 01:20:36  - UAT/min 0/0 [maxSS=0.00%], ES/min 1/216, Total traffic targets tracked=1
2016/02/26 01:20:36  - Network data messages sent: 45 total, 45 nonqueueable.  Network data bytes sent: 751 total, 751 nonqueueable.
2016/02/26 01:20:36  - Last GPS fix: 1 minute ago, GPS solution type: 0 using 0 satellites (0/0 seen/tracked), NACp: 0, est accuracy 999999.00 m
2016/02/26 01:20:36  - GPS vertical velocity: 0.00 ft/sec; GPS vertical accuracy: 999999 m
2016/02/26 01:21:06 stats [started: 2 minutes ago]
2016/02/26 01:21:06  - Disk bytes used = 1.4 GB (76.4 %), Disk bytes free = 440 MB (23.6 %)
2016/02/26 01:21:06  - CPUTemp=38.63 deg C, MemStats.Alloc=3.0 MB, MemStats.Sys=8.8 MB, totalNetworkMessagesSent=102
2016/02/26 01:21:06  - UAT/min 0/0 [maxSS=0.00%], ES/min 1/216, Total traffic targets tracked=1
2016/02/26 01:21:06  - Network data messages sent: 60 total, 60 nonqueueable.  Network data bytes sent: 1001 total, 1001 nonqueueable.
2016/02/26 01:21:06  - Last GPS fix: 2 minutes ago, GPS solution type: 0 using 0 satellites (0/0 seen/tracked), NACp: 0, est accuracy 999999.00 m
2016/02/26 01:21:06  - GPS vertical velocity: 0.00 ft/sec; GPS vertical accuracy: 999999 m
2016/02/26 01:21:34 wrote settings.
2016/02/26 01:21:35 Configuring Ping ADS-B
2016/02/26 01:21:35 No suitable Ping device found.
2016/02/26 01:21:36 stats [started: 2 minutes ago]
2016/02/26 01:21:36  - Disk bytes used = 1.4 GB (76.4 %), Disk bytes free = 440 MB (23.6 %)
2016/02/26 01:21:36  - CPUTemp=38.63 deg C, MemStats.Alloc=3.7 MB, MemStats.Sys=8.8 MB, totalNetworkMessagesSent=129
2016/02/26 01:21:36  - UAT/min 0/0 [maxSS=0.00%], ES/min 1/216, Total traffic targets tracked=1
2016/02/26 01:21:36  - Network data messages sent: 75 total, 75 nonqueueable.  Network data bytes sent: 1251 total, 1251 nonqueueable.
2016/02/26 01:21:36  - Last GPS fix: 2 minutes ago, GPS solution type: 0 using 0 satellites (0/0 seen/tracked), NACp: 0, est accuracy 999999.00 m
2016/02/26 01:21:36  - GPS vertical velocity: 0.00 ft/sec; GPS vertical accuracy: 999999 m
2016/02/26 01:21:46 wrote settings.
2016/02/26 01:21:46 Entered Ping shutdown() ...
2016/02/26 01:22:06 stats [started: 3 minutes ago]
2016/02/26 01:22:06  - Disk bytes used = 1.4 GB (76.4 %), Disk bytes free = 440 MB (23.6 %)
2016/02/26 01:22:06  - CPUTemp=38.63 deg C, MemStats.Alloc=1.2 MB, MemStats.Sys=8.8 MB, totalNetworkMessagesSent=156
2016/02/26 01:22:06  - UAT/min 0/0 [maxSS=0.00%], ES/min 1/216, Total traffic targets tracked=1
2016/02/26 01:22:06  - Network data messages sent: 90 total, 90 nonqueueable.  Network data bytes sent: 1501 total, 1501 nonqueueable.
2016/02/26 01:22:06  - Last GPS fix: 3 minutes ago, GPS solution type: 0 using 0 satellites (0/0 seen/tracked), NACp: 0, est accuracy 999999.00 m
2016/02/26 01:22:06  - GPS vertical velocity: 0.00 ft/sec; GPS vertical accuracy: 999999 m
2016/02/26 01:22:36 stats [started: 3 minutes ago]
2016/02/26 01:22:36  - Disk bytes used = 1.4 GB (76.4 %), Disk bytes free = 440 MB (23.6 %)
2016/02/26 01:22:36  - CPUTemp=39.17 deg C, MemStats.Alloc=2.0 MB, MemStats.Sys=8.8 MB, totalNetworkMessagesSent=183
2016/02/26 01:22:36  - UAT/min 0/0 [maxSS=0.00%], ES/min 1/216, Total traffic targets tracked=1
2016/02/26 01:22:36  - Network data messages sent: 105 total, 105 nonqueueable.  Network data bytes sent: 1751 total, 1751 nonqueueable.
2016/02/26 01:22:36  - Last GPS fix: 3 minutes ago, GPS solution type: 0 using 0 satellites (0/0 seen/tracked), NACp: 0, est accuracy 999999.00 m
2016/02/26 01:22:36  - GPS vertical velocity: 0.00 ft/sec; GPS vertical accuracy: 999999 m
2016/02/26 01:23:06 stats [started: 4 minutes ago]
2016/02/26 01:23:06  - Disk bytes used = 1.4 GB (76.4 %), Disk bytes free = 440 MB (23.6 %)
2016/02/26 01:23:06  - CPUTemp=38.63 deg C, MemStats.Alloc=3.6 MB, MemStats.Sys=8.8 MB, totalNetworkMessagesSent=212
2016/02/26 01:23:06  - UAT/min 0/0 [maxSS=0.00%], ES/min 123/216, Total traffic targets tracked=2
2016/02/26 01:23:06  - Network data messages sent: 122 total, 122 nonqueueable.  Network data bytes sent: 2065 total, 2065 nonqueueable.
2016/02/26 01:23:06  - Last GPS fix: 4 minutes ago, GPS solution type: 0 using 0 satellites (0/0 seen/tracked), NACp: 0, est accuracy 999999.00 m
2016/02/26 01:23:06  - GPS vertical velocity: 0.00 ft/sec; GPS vertical accuracy: 999999 m
2016/02/26 01:18:11 Stratux v1.2r2 (bcd62e7c00e132dada7ed7cbf0a5d28133916ff1) starting.
2016/02/26 01:18:11 Entered uatReader() ...
2016/02/26 01:18:11 read in settings.
2016/02/26 01:18:11 client connected: 192.168.10.10:4000 (Raymonds-iPad).
2016/02/26 01:18:11 client connected: 192.168.10.11:4000 (Raymonds-MBP).
2016/02/26 01:18:12 ===== UAT Device Name  : Generic RTL2832U OEM =====
2016/02/26 01:18:12 ===== UAT Device Serial: stratux:978=====
2016/02/26 01:18:12     GetTunerType: RTLSDR_TUNER_R820T
2016/02/26 01:18:12     SetTunerGainMode Successful
2016/02/26 01:18:12     SetTunerGain Successful
2016/02/26 01:18:12     GetTunerGain: 480
2016/02/26 01:18:12     SetSampleRate - rate: 2083334
2016/02/26 01:18:12     GetSampleRate: 2083334
2016/02/26 01:18:12     GetXtalFreq - Rtl: 28800000, Tuner: 28800000
2016/02/26 01:18:12     SetXtalFreq - Center freq: 28800000, Tuner freq: 28800000
2016/02/26 01:18:12     SetCenterFreq 978MHz Successful
2016/02/26 01:18:12     GetCenterFreq: 978000000
2016/02/26 01:18:12     Setting Bandwidth: 1000000
2016/02/26 01:18:12     SetTunerBw 1000000 Successful
2016/02/26 01:18:12     ResetBuffer Successful
2016/02/26 01:18:12     GetFreqCorrection: 0
2016/02/26 01:18:12     SetFreqCorrection 0 Successful
2016/02/26 01:18:12 Entered UAT read() ...
2016/02/26 01:18:12 ===== ES Device Serial: stratux:1090 PPM 0 =====
2016/02/26 01:18:12 Entered ES read() ...
2016/02/26 01:18:13 Executed /usr/bin/dump1090 successfully...
2016/02/26 01:18:16 readBMP180(): input/output error
2016/02/26 01:18:41 stats [started: 30 seconds ago]
2016/02/26 01:18:41  - Disk bytes used = 1.4 GB (76.4 %), Disk bytes free = 439 MB (23.6 %)
2016/02/26 01:18:41  - CPUTemp=36.48 deg C, MemStats.Alloc=1.6 MB, MemStats.Sys=6.6 MB, totalNetworkMessagesSent=44
2016/02/26 01:18:41  - UAT/min 0/0 [maxSS=0.00%], ES/min 0/0, Total traffic targets tracked=0
2016/02/26 01:18:41  - Network data messages sent: 34 total, 34 nonqueueable.  Network data bytes sent: 582 total, 582 nonqueueable.
2016/02/26 01:18:41  - Last GPS fix: 30 seconds ago, GPS solution type: 0 using 0 satellites (0/0 seen/tracked), NACp: 0, est accuracy 999999.00 m
2016/02/26 01:18:41  - GPS vertical velocity: 0.00 ft/sec; GPS vertical accuracy: 999999 m

**Comment by Helno** [comment]
Based on that log file it is definitely working. It appears to have seen traffic and is seeing your ipad and MacBook pro.

Take a look in the Foreflight settings and be sure that hide distant traffic is turned off.

**Comment by raylow78** [comment]
I was able to figure out the issue...long story short it was a pi filler issue.
