### ISSUE TITLE
Memory leak kills some Stratux services after 2.5 hours

### ISSUE THREAD

**Issue by ssokol** [cyoung/stratux#60]
I've done another all-day test, this time with 0.3b4 stock. It was running with a single R820T2 and a RY835AI. UAT, GPS and AHRS were enabled. 

The system was started at 13:05 and continued to log until 18:17, so just over five hours. The Stratux web UI stopped updating the "Uptime" value after 2 hours, 25 minutes which roughly correlates with the time that ForeFlight stopped displaying GPS and ADS-B information and lost the "FreeFlight" data feed. The "Stratux" data feed remained and continued to provide attitude and altitude until the experiment was terminated.

As seems to be the case when this occurs, memory usage was very high. I was able to log in and capture memory usage, CPU, etc. (see below) but was unable to successfully kill the gen_gdl90 process. Attempting to do so - first by attaching to the screen session and issuing a Ctr+c, then using the kill command - left the process defunct but still resident in memory. I attempted a clean shutdown using "poweroff" but the system hung during the shutdown.

Stratux.log is available here: https://gist.github.com/ssokol/34a6eca6b9d0016640c0

The other Stratux logs are available if you need them.

![screen shot 2015-09-24 at 5 04 55 pm](https://cloud.githubusercontent.com/assets/350268/10088453/8be9b000-62e0-11e5-9dbf-643ea551133a.png)

![screen shot 2015-09-24 at 5 06 18 pm](https://cloud.githubusercontent.com/assets/350268/10088462/91ed9692-62e0-11e5-9b3f-613deab5f607.png)

![screen shot 2015-09-24 at 5 06 52 pm](https://cloud.githubusercontent.com/assets/350268/10088465/978b4d4c-62e0-11e5-86a7-954328b74279.png)

**Comment by bradanlane** [comment]
We may be able to narrow this down a bit. I ran Stratux for 6hrs non-stop with two SDRs but no GPS/AHRS. WebUI available the entire time.  I have logs if there is anything to look for.

**Comment by cyoung** [comment]
Thanks @ssokol and @bradanlane.

For future reference, memprof:

     func dumpHeapProfileAndExit() {
             t := time.NewTicker(10 * time.Minute)
             <-t.C
             f, err := os.Create("/tmp/gen_gdl90.mem.prof")
             if err != nil {
                     log.Printf("err: %s\n", err.Error())
                     return
             }
             pprof.WriteHeapProfile(f)
             f.Close()
             os.Exit(1)
     }

Then just threw "go dumpHeapProfileAndExit()" in main(). 

     apt-get --fix-missing install graphviz
     go tool pprof --pdf gen_gdl90 /tmp/gen_gdl90.mem.prof >/var/www/memprof.pdf


Before:

![screen shot 2015-09-24 at 11 18 39 pm](https://cloud.githubusercontent.com/assets/57193/10092289/a90fe8b6-6312-11e5-9d6d-50ef654c380f.png)


After:

![screen shot 2015-09-24 at 11 49 43 pm](https://cloud.githubusercontent.com/assets/57193/10092657/f69bb11a-6316-11e5-8875-1595c2005594.png)
