### ISSUE TITLE
description of issue

### ISSUE THREAD

**Issue by Basalisk84** [cyoung/stratux#601]
1. Stratux version:
2. Stratux config:

    SDR
      - [ ] single
      - [x ] dual

    GPS
      - [x ] yes
      - [ ] no
      type:

    AHRS
      - [ x] yes
      - [ ] no

    power source:

    usb cable:

3. EFB app and version: (e.g., WingX Pro7 8.6.2)
Droid EFB
    EFB platform: (e.g., iOS 9.2)
Windows 10 and Android Lolipop
    EFB hardware: (e.g., iPad Mini 2)
Surface pro 3 and Asus transformer prime
4. Description of your issue:

My CPU fan that plugs into the ahrs module works with v1.2r2 but doesn't come on with v1.3b2

I installed v1.3b1 and logged into the settings and used the update function to get V1.3b2

If possible, enable "Replay Logs", reproduce the problem, and provide a copy of the logs in http://192.168.10.1/logs/stratux/ and http://192.168.10.1/logs/stratux.log.

**Comment by cyoung** [comment]
@Basalisk84 which fan/case are you using?

The fan is turned off to conserve power in v1.3b2 unless the CPU goes above 50C - at which point it will ramp up the speed of the fan. Where are your CPU temps at now?
