### ISSUE TITLE
Throttle AHRS reports when the unit is stationary/pressure is constant

### ISSUE THREAD

**Issue by pasniak** [cyoung/stratux#607]
1. Stratux version:  v1.3b2 (95fe19902a)

2. Stratux config:

    SDR
      - [ ] single
      - [ ] dual

    GPS
      - [x] yes
      - [ ] no
      type:

    AHRS
      - [x] yes
      - [ ] no

4. Description of your issue:  

When Stratux is stationary, PFD display (in Avare) keeps on refreshing (and adds CPU load on the tablet) due to incoming messages (ws).  PFD does not change visually (bar magnetic heading which I guess needs some fix?). 

I could deal with it in the client (PFD) code but it is probably better to do it at the sensor code level because it would avoid reparsing JSON.

For example I see the following fluctuations in ws://192.168.10.1/situation when Strutux is sitting on my desk:

BaroPressureAltitude:
355.181640625
355.1310119628906
355.1310119628906
355.1310119628906
355.08251953125
355.1310119628906

AHRSSlipSkid:
-0.3168134391307831
-0.3012425899505615
-0.3101137578487396
-0.2918091118335724
-0.28500768542289734
-0.28368738293647766

AHRSRoll:
0.2997537851333618
0.2973392903804779
0.3007013201713562
0.3036881983280182
0.3063836395740509
0.3044423758983612
0.30386266112327576
0.3024156093597412

AHRSPitch:
-0.01704983413219452
-0.01904536597430706
-0.02025335282087326
-0.018916286528110504
-0.01769513450562954
-0.018712619319558144
-0.01935202069580555

AHRSMagHeading:
253.15817
253.32114
252.8255
253.08794
255.66367
254.39497
252.86827
255.38394

AHRSGLoad:
0.9995430111885071
0.9993182420730591
0.9994113445281982
0.999926745891571
0.9996764659881592
0.9993181824684143
0.9991434216499329
1.000234603881836

AHRSLastAttitudeTime and BaroLastMeasurementTime for 2 messages:

0001-01-01T10:05:53.8Z 0001-01-01T10:05:53.76Z
0001-01-01T10:05:53.8Z 0001-01-01T10:05:53.76Z

0001-01-01T10:05:53.9Z 0001-01-01T10:05:53.86Z
0001-01-01T10:05:53.9Z 0001-01-01T10:05:53.86Z

**Comment by cyoung** [comment]
I don't think we'll make this change. The unit is meant to be used in a vehicle which is constantly moving. If the app can't handle the full refresh rate and we throttle it for ground use, then it creates a development environment which is not representative of the real-world device use. Reopen if you have some convincing argument otherwise.
