### ISSUE TITLE
Statux Status Logging in Developer Mode, cannot toggle off

### ISSUE THREAD

**Issue by D35Bonanza** [cyoung/stratux#616]
1. Stratux version:
2. Stratux config:

    SDR
      - [ ] single
      - [x ] dual

    GPS
      - [ x] yes
      - [ ] no
      type:

    AHRS
      - [ ] yes
      - [x ] no

    power source: 28 vdc Aircraft. ubec 5.5vdc at 2amp

    usb cable:

3. EFB app and version: 
Avare
    EFB platform: 
Android
    EFB hardware: 
Nexus
4. Description of your issue:
Status Logging cannot be toggled on/.off in Developers Mode for StaticIps use on local LAN eth0 routed to Internet. The APD is not being used on wlan0

Gen_gdl90.go has been commented and make, stxstop, make install, stxstart shows no status logging being logged for developers mode on Developers window Stratux Webpage.

		//FIXME: Only do this if data logging is enabled.
	//initDataLog()

// Start printing stats periodically to the logfiles.
	//go printStats()

//FIXME is current for gen_gdl90.go
after stopping the goprintStats() the CPU temp dropped 4degC

If possible, enable "Replay Logs", reproduce the problem, and provide a copy of the logs in http://192.168.10.1/logs/stratux/ and http://192.168.10.1/logs/stratux.log.

**Comment by D35Bonanza** [comment]
//FIXME is current for gen_gdl90.go

**Comment by cyoung** [comment]
Good point. We might just route the normal logging to `/dev/null` unless enabled.
