### ISSUE TITLE
Auto Power On possible?

### ISSUE THREAD

**Issue by FlyingSikh** [cyoung/stratux#617]
1. Stratux version:1.3b2
2. Stratux config: 

    SDR
      - [ ] single
      - [ x] dual

    GPS
      - [ x] yes
      - [ ] no
      type:

    AHRS
      - [ x] yes
      - [ ] no

    power source: EasyAcc 6000mAh 

    usb cable: supplied

3. EFB app and version: (e.g., WingX Pro7 8.6.2)
FlyQ latest IPad Air2

    EFB platform: (e.g., iOS 9.2)

    EFB hardware: (e.g., iPad Mini 2)

4. Description of your issue: is it possible to add Auto Power On when battery pack is charging or senses power being supplied. I'm planning to remote mount with charging cable permanently attached so I never have to touch it. Powering off by WebUI is fine.

If possible, enable "Replay Logs", reproduce the problem, and provide a copy of the logs in http://192.168.10.1/logs/stratux/ and http://192.168.10.1/logs/stratux.log.

**Comment by peepsnet** [comment]
This would seem to be more a feature of the battery pack...

The other option would be to make your own case that holds the batteries and create a circuit that can do this... a power switching control unit

**Comment by cyoung** [comment]
So you will have ship power -> pass-through charging battery pack -> stratux.

It's certainly possible but not so much by software implementation.

**Comment by FlyingSikh** [comment]
Ok, How does Stratus do it?

**Comment by Nokomis449** [comment]
My solution was to buy a cheap IR relay and put it in a small Radio Shack project box.  Ship's USB power plugs into the input side of the relay, and the Stratux power cord is plugged into the output of the relay.  The Stratux sits on the hatrack in back and the handheld remote allows me to turn the Stratux on & off from the pilot's seat.

**Comment by dmschlab** [comment]
>Ok, How does Stratus do it?

They designed their hardware that way

**Comment by cyoung** [comment]
Hardware mod, not something we can easily do in the software now. Good idea.
