### ISSUE TITLE
 Invalid NMEA string: Invalid NMEA message, must disable/enable GPS to clear error.

### ISSUE THREAD

**Issue by D35Bonanza** [cyoung/stratux#620]
1. Stratux version:1.3b1 update-stratux-v1.3b2-51fd728cc6
2. Stratux config:

    SDR
      - [ ] single
      - [x ] dual

    GPS
      - [x ] yes
      - [ ] no
      type:vk172

    AHRS
      - [ ] yes
      - [x ] no

    power source: ubec 5v 2.5amp

    usb cable:

3. EFB app and version: (e.g., WingX Pro7 8.6.2)
avare
    EFB platform:
android
    EFB hardware: 
LG phone
4. Description of your issue:
On start, 
2017/06/15 04:10:34 GPS error. Invalid NMEA string: Invalid NMEA message
2017/06/15 04:10:34 GPS error. Invalid NMEA string: Invalid NMEA message
2017/06/15 04:10:34 GPS error. Invalid NMEA string: Invalid NMEA message
Toggle GPS off/on
2017/06/15 04:12:32  - Disk bytes used = 4.3 GB (27.5 %), Disk bytes free = 11 GB (72.5 %)
2017/06/15 04:12:32  - CPUTemp=53.69 deg C, MemStats.Alloc=6.2 MB, MemStats.Sys=12 MB, totalNetworkMessagesSent=5,984
2017/06/15 04:12:32  - CPU load 
2017/06/15 04:12:32  - UAT/min 39/39 [maxSS=0.00%], ES/min 4,706/4,841, Total traffic targets tracked=25
2017/06/15 04:12:32  - Network data messages sent: 5529 total, 5469 nonqueueable.  Network data bytes sent: 190090 total, 162369 nonqueueable.
2017/06/15 04:12:32  - Last GPS fix: now, GPS solution type: 1 using 9 satellites (10/11 seen/tracked), NACp: 10, est accuracy 6.00 m
2017/06/15 04:12:32  - GPS vertical velocity: -0.37 ft/sec; GPS vertical accuracy: 11 m

If possible, enable "Replay Logs", reproduce the problem, and provide a copy of the logs in http://192.168.10.1/logs/stratux/ and http://192.168.10.1/logs/stratux.log.

**Comment by cyoung** [comment]
I think that's just a baud rate mismatch. It should always resolve itself under normal circumstances.
