### ISSUE TITLE
AHRS Chip and Fan Control

### ISSUE THREAD

**Issue by 737mechdude** [cyoung/stratux#622]
1. Stratux version: Newest 1.2r2
2. Stratux config: Pi 3b

    SDR
      - [ ] single
      - [ ] dual dual mini as sold amazon with antennae

    GPS
      - [ ] yes yes
      - [ ] no
      type:

    AHRS
      - [ ] yes soon
      - [ ] no

    power source: USB 50000 mah pack

    usb cable: standard

3. EFB app and version: (e.g., WingX Pro7 8.6.2) wingx pro7

    EFB platform: (e.g., iOS 9.2) ios 10.32

    EFB hardware: (e.g., iPad Mini 2) mini 4

4. Description of your issue: AHRS CHIP Plug and play??  Do I have to change code to make the AHRS chip work?  I just ordered it, I want to be ready to use it.  Also fan control, is that automatic? Or user defined?

If possible, enable "Replay Logs", reproduce the problem, and provide a copy of the logs in http://192.168.10.1/logs/stratux/ and http://192.168.10.1/logs/stratux.log.

**Comment by cyoung** [comment]
You need one of the latest betas for it to work, install this update:

http://updates.stratux.me/builds/update-stratux-v1.3b2-51fd728cc6.sh
