### ISSUE TITLE
Upgrade from 0.8r2 to 1.2r2.  Will not start WiFi.  RPi 2 Model B

### ISSUE THREAD

**Issue by Radioman704** [cyoung/stratux#627]
1. Stratux version:0.8r2
2. Stratux config:

    SDR
      - [ ] single
      - [x ] dual

    GPS
      - [x ] yes
      - [ ] no
      type:

    AHRS
      - [ ] yes
      - [x ] no

    power source: External 2.5amp

    usb cable: 1M

3. EFB app and version: (e.g., WingX Pro7 8.6.2) FlyQ EFB v2.4.5

    EFB platform: (e.g., iOS 9.2)iOS 8.4.1

    EFB hardware: (e.g., iPad Mini 2)iPad

4. Description of your issue: I am running RPi 2 Model B.  Stratux V0.8r2 without any major issues.  Tried to upgrade to V1.2r2.  The RPi "green" led comes on as it should but the Wifi never initializes.  Are there known problems with this version and RPi 2 Model B?

If possible, enable "Replay Logs", reproduce the problem, and provide a copy of the logs in http://192.168.10.1/logs/stratux/ and http://192.168.10.1/logs/stratux.log.

**Comment by cyoung** [comment]
Give [v1.4r1](https://github.com/cyoung/stratux/releases/download/v1.4r1/stratux-v1.4r1-f6bad36cdc.img.zip) a try.
