### ISSUE TITLE
GPS Button stays RED

### ISSUE THREAD

**Issue by FlyingSikh** [cyoung/stratux#633]
1.Stratux version: v1.3b2 ( 8ea90ac )

2.Stratux config:

SDR
 single
◦[X ] dual

GPS
◦[ X] yes
 no
 type:GPYes

AHRS
◦[X ] yes
 no

power source: 2.4A

usb cable: 6inch

3.EFB app and version: (e.g., WingX Pro7 8.6.2)
 FlyQ
 EFB platform: (e.g., iOS 9.2)
 iOS10.2
 EFB hardware: (e.g., iPad Mini 2)
 iPad Air2

4.Description of your issue:
GPS Button staying RED even though GPS are seen and resolved.

If possible, enable "Replay Logs", reproduce the problem, and provide a copy of the logs in http://192.168.10.1/logs/stratux/ and http://192.168.10.1/logs/stratux.log.

**Comment by FlyingSikh** [comment]
![stratuxlog](https://user-images.githubusercontent.com/28975354/27974841-862f012a-6314-11e7-9494-f3680a8b756f.JPG)

**Comment by cyoung** [comment]
Which is the "GPS button"?

**Comment by FlyingSikh** [comment]
sorry, one under GPS/AHRS.

**Comment by FlyingSikh** [comment]
has anyone seen this?
What could be causing it? I have tried formatting and reloading the SD Card. Shall I try a new GPS?
TIA

**Comment by Ergonomicmike** [comment]
Perhaps unique to the GPSYes? I have a VK-162 and the red/green light under the web UI's AHRS works just fine for me.

**Comment by cyoung** [comment]
I think you're referring to the "GPS/AHRS" page.

Your logs show that the GPS is not locking.

**Comment by 737mechdude** [comment]
I can confirm I had the same issue, it was the GPS.  Replaced and all is great again.

**Comment by cyoung** [comment]
@FlyingSikh - sounds like GPS wasn't getting a lock. Try with the latest and re-open if the issue persists.
