### ISSUE TITLE
Getting the data coming from Stratux into MATLAB

### ISSUE THREAD

**Issue by Sara1371** [cyoung/stratux#640]
1. Stratux version: Home built stratux with Raspberry pi 3
2. Stratux config:

    SDR
      - [ ] single
      - [X ] dual 

    GPS
      - [X ] yes
      - [ ] no
      type:

    AHRS
      - [ ] yes
      - [ ] no

    power source: power bank

    usb cable: 

3. EFB app and version: (e.g., WingX Pro7 8.6.2)

    EFB platform: (e.g., iOS 9.2)

    EFB hardware: (e.g., iPad Mini 2)

4. Description of your issue: Hello! I need to get the data coming into stratux into Matlab. I actually need to have access to the raw data in an ASCII or binary or any other format. Is there an interface program or anything else for this purpose?

If possible, enable "Replay Logs", reproduce the problem, and provide a copy of the logs in http://192.168.10.1/logs/stratux/ and http://192.168.10.1/logs/stratux.log.

**Comment by cyoung** [comment]
@Sara1371 - I think this question was answered on [Reddit](https://www.reddit.com/r/stratux/comments/6lv0vk/getting_data_into_matlab/).

Reopen if you need anything further.
