### ISSUE TITLE
Stratux interface software

### ISSUE THREAD

**Issue by JimR2017** [cyoung/stratux#644]
1. Stratux version:Home built with RPi3
2. Stratux config:

    SDR
      - [ ] single
      - [ x] dual

    GPS
      - [ x] yes
      - [ ] no
      type:

    AHRS
      - [ ] yes
      - [ x] no

    power source:

    usb cable:

3. EFB app and version: (e.g., WingX Pro7 8.6.2)

    EFB platform: (e.g., iOS 9.2)

    EFB hardware: (e.g., iPad Mini 2)

4. Description of your issue:
We are developing a new EFB simulation for a research project.  We are looking for more information on accessing data from the Stratux.  Is there a Software Development Kit (SDK) or interface manual that will describe how to structure the interface with the Stratux RPi3?

If possible, enable "Replay Logs", reproduce the problem, and provide a copy of the logs in http://192.168.10.1/logs/stratux/ and http://192.168.10.1/logs/stratux.log.

**Comment by cyoung** [comment]
Hi Jim,

Did you find this link? https://github.com/cyoung/stratux/blob/master/notes/app-vendor-integration.md

If you've already seen it, what further information do you need specifically?

**Comment by JimR2017** [comment]
Thank you for your help.  I think we are making good progress now.
Best
Jim
