### ISSUE TITLE
Night Mode

### ISSUE THREAD

**Issue by PopsActual** [cyoung/stratux#659]
1. Stratux version:1.4r2
2. Stratux config:

    SDR
      - [ ] single
      - [x] dual

    GPS
      - [x] yes
      - [ ] no
      type: GPYes

    AHRS
      - [x] yes
      - [ ] no

    power source: 

    usb cable:

3. EFB app and version: ForeFlight

    EFB platform: iOS 10.3

    EFB hardware: iPad Mini 2

4. Description of your issue:  Enhancement request.  What are the chances of doing a night mode in the UI?  Just a button that would turn off all the lights in the Pi, SDRs, and GPYes?

If possible, enable "Replay Logs", reproduce the problem, and provide a copy of the logs in http://192.168.10.1/logs/stratux/ and http://192.168.10.1/logs/stratux.log.

**Comment by cyoung** [comment]
Thanks for asking this. See below, the webui looks pretty decent with inverted colors.

Settings -> General -> Accessibility -> Accessibility Shortcut (all the way at the bottom) -> Invert Colors

Then triple-tap the home screen button to activate/deactivate.


![img_0313](https://user-images.githubusercontent.com/57193/29801405-72342784-8c3d-11e7-8d05-59cd1fb6a75f.png)

![img_0314](https://user-images.githubusercontent.com/57193/29801407-749a3900-8c3d-11e7-8180-af9a8dc045d1.png)

**Comment by PopsActual** [comment]
Does that turn off the hardware lights?  That's really my problem right now.

**Comment by cyoung** [comment]
No, it doesn't.
Lights on the SDRs - which ones do you have? Recent ones don't have LEDs.
GPYes - can't turn those off in software.
We'd be looking at only turning off the LEDs on the Pi.

**Comment by ijessen** [comment]
@cyoung are we sure the GPYes can't be turned off in software? When I looked into the u-blox 7 spec a few weeks ago it seems like a CFG-TP5 serial message (ID 0x06 0x31) could be formatted to deactivate the default time pulse output, which I believe is wired to the PPS LED on the GPYes.  I don't have anything to test on at the moment, but I would guess this should work?

**Comment by cyoung** [comment]
@ijessen - you're right. Just tried this with u-center and that did it.

![u-center tp5](https://user-images.githubusercontent.com/57193/31688203-a69d8126-b359-11e7-8b7e-4ac1cd786a73.png)

**Comment by cyoung** [comment]
Okay, added `NightMode`. If someone wants to add something to the webui to toggle `globalStatus.NightMode`, that should round it out. Default state on led0 is "off". It will still flash if there's a critical system error.

**Comment by cyoung** [comment]
We've turned off everything we can. The power LED on the Pi can't be turned off. I've had the power LED removed from the GPYes and turned ACT off with above u-blox configuration.
