### ISSUE TITLE
Error when Make

### ISSUE THREAD

**Issue by Strato38** [cyoung/stratux#661]
1. Stratux version:
2. Stratux config:

    SDR
      - [x] single
      - [ ] dual

    GPS
      - [x] yes
      - [ ] no
      type: RY835AI (USB)

    AHRS
      - [ ] yes
      - [x] no

    power source: USB Charger

    usb cable:

3. EFB app and version: (e.g., WingX Pro7 8.6.2)

    EFB platform: (e.g., iOS 9.2)

    EFB hardware: (e.g., iPad Mini 2)

4. Description of your issue:

When make I get this error 

gcc -g -o view1090 view1090.o anet.o interactive.o mode_ac.o mode_s.o net_io.o crc.o stats.o cpr.o icao_filter.o track.o util.o -lpthread -lm -lrt 
make[2]: Leaving directory '/root/stratux/dump1090'
go get -t -d -v ./main ./test ./godump978 ./uatparse ./sensors
make[1]: go: Command not found
Makefile:17: recipe for target 'xgen_gdl90' failed
make[1]: *** [xgen_gdl90] Error 127
make[1]: Leaving directory '/root/stratux'
Makefile:14: recipe for target 'all' failed
make: *** [all] Error 2

If possible, enable "Replay Logs", reproduce the problem, and provide a copy of the logs in http://192.168.10.1/logs/stratux/ and http://192.168.10.1/logs/stratux.log.

**Comment by cyoung** [comment]
Looks like you're missing the go compiler, you could `apt-get install golang` perhaps. Try one of the "-dev" images in the releases.
