### ISSUE TITLE
No GPS or Weather

### ISSUE THREAD

**Issue by TArrowJim** [cyoung/stratux#662]
1. Stratux version: v1.4r1 (f6bad36cdc)
2. Stratux config: Raspberry Pi 3, Stratux 1090ES & UAT, GPYes

    SDR
      - [ ] single
      - [X ] dual

    GPS
      - [X ] yes
      - [ ] no
      type:

    AHRS
      - [ ] yes
      - [X ] no

    power source: EasyAcc

    usb cable:

3. EFB app and version: (e.g., WingX Pro7 8.6.2) Foreflight v9.2.1

    EFB platform: (e.g., iOS 9.2) iOS 10.3.3

    EFB hardware: (e.g., iPad Mini 2) iPad MD511LL/A

4. Description of your issue:

Just put my stratux together and the 1090/traffic reception seems fine. I see nothing on the 978/weather or GPS side. UAT on Status page shows 0 for signal and zeros across the board. GPS likewise, I see nothing. The unit is up against a window.

Log is below.

Thoughts on both 978 and GPS?

Jim

2016/02/26 01:18:08 Stratux v1.4r1 (f6bad36cdcb81e877e4dfe6e55c840a904cade0b) starting.
2016/02/26 01:18:08 Entered uatReader() ...
2016/02/26 01:18:08 read in settings.
2016/02/26 01:18:08 datalog.go: Watchdog wants to START logging.
2016/02/26 01:18:08 AHRS Info: initializing new Simple AHRS
2016/02/26 01:18:08 client connected: 192.168.10.10:4000 (iPad).
2016/02/26 01:18:08 datalog.go: dataLog() started
2016/02/26 01:18:08 AHRS Info: couldn't start ahrswebListener: dial tcp [::1]:8000: getsockopt: connection refused
2016/02/26 01:18:09 ===== ES Device Serial: stratux:1090 PPM 0 =====
2016/02/26 01:18:09 Entered ES read() ...
2016/02/26 01:18:09 Executed /usr/bin/dump1090 successfully...
2016/02/26 01:18:09 ===== UAT Device Name  : Generic RTL2832U OEM =====
2016/02/26 01:18:09 ===== UAT Device Serial: stratux:978=====
2016/02/26 01:18:09 	GetTunerType: RTLSDR_TUNER_R820T
2016/02/26 01:18:09 	SetTunerGainMode Successful
2016/02/26 01:18:09 	SetTunerGain Successful
2016/02/26 01:18:09 	GetTunerGain: 480
2016/02/26 01:18:10 	SetSampleRate - rate: 2083334
2016/02/26 01:18:10 	GetSampleRate: 2083334
2016/02/26 01:18:10 	GetXtalFreq - Rtl: 28800000, Tuner: 28800000
2016/02/26 01:18:10 	SetXtalFreq - Center freq: 28800000, Tuner freq: 28800000
2016/02/26 01:18:10 	SetCenterFreq 978MHz Successful
2016/02/26 01:18:10 	GetCenterFreq: 978000000
2016/02/26 01:18:10 	Setting Bandwidth: 1000000
2016/02/26 01:18:10 	SetTunerBw 1000000 Successful
2016/02/26 01:18:10 	ResetBuffer Successful
2016/02/26 01:18:10 	GetFreqCorrection: 0
2016/02/26 01:18:10 	SetFreqCorrection 0 Successful
2016/02/26 01:18:10 Entered UAT read() ...
2016/02/26 01:18:12 BMP280 Connection Attempt 1
2016/02/26 01:18:12 BMP280 Connection Attempt 2
2016/02/26 01:18:12 BMP280 Connection Attempt 3
2016/02/26 01:18:12 BMP280 Connection Attempt 4
2016/02/26 01:18:12 BMP280 Connection Attempt 5
2016/02/26 01:18:12 BMP280 Connection Attempt 1
2016/02/26 01:18:12 BMP280 Connection Attempt 2
2016/02/26 01:18:12 BMP280 Connection Attempt 3
2016/02/26 01:18:12 BMP280 Connection Attempt 4
2016/02/26 01:18:12 BMP280 Connection Attempt 5
2016/02/26 01:18:12 AHRS Info: couldn't initialize BMP280 or BMP180
2016/02/26 01:18:12 AHRS Info: attempting IMU connection.
2016/02/26 01:18:12 MPU9250: Error reading calibration data from /etc/mpu9250cal.json: open /etc/mpu9250cal.json: no such file or directory
2016/02/26 01:18:12 AHRS Error: couldn't initialize an IMU
2016/02/26 01:18:12 GPS error. Invalid NMEA string: Invalid NMEA message
2016/02/26 01:18:12 GPS detected: u-blox NMEA position message seen.
2016/02/26 01:18:16 BMP280 Connection Attempt 1
2016/02/26 01:18:16 BMP280 Connection Attempt 2
2016/02/26 01:18:16 BMP280 Connection Attempt 3
2016/02/26 01:18:16 BMP280 Connection Attempt 4
2016/02/26 01:18:16 BMP280 Connection Attempt 5
2016/02/26 01:18:16 BMP280 Connection Attempt 1
2016/02/26 01:18:16 BMP280 Connection Attempt 2
2016/02/26 01:18:16 BMP280 Connection Attempt 3
2016/02/26 01:18:16 BMP280 Connection Attempt 4
2016/02/26 01:18:16 BMP280 Connection Attempt 5
2016/02/26 01:18:16 AHRS Info: couldn't initialize BMP280 or BMP180
2016/02/26 01:18:16 AHRS Info: attempting IMU connection.
2016/02/26 01:18:16 MPU9250: Error reading calibration data from /etc/mpu9250cal.json: open /etc/mpu9250cal.json: no such file or directory
2016/02/26 01:18:16 AHRS Error: couldn't initialize an IMU
2016/02/26 01:18:20 BMP280 Connection Attempt 1
2016/02/26 01:18:20 BMP280 Connection Attempt 2
2016/02/26 01:18:20 BMP280 Connection Attempt 3
2016/02/26 01:18:20 BMP280 Connection Attempt 4
2016/02/26 01:18:20 BMP280 Connection Attempt 5
2016/02/26 01:18:20 BMP280 Connection Attempt 1
2016/02/26 01:18:20 BMP280 Connection Attempt 2
2016/02/26 01:18:20 BMP280 Connection Attempt 3
2016/02/26 01:18:20 BMP280 Connection Attempt 4
2016/02/26 01:18:20 BMP280 Connection Attempt 5
2016/02/26 01:18:20 AHRS Info: couldn't initialize BMP280 or BMP180
2016/02/26 01:18:20 AHRS Info: attempting IMU connection.
2016/02/26 01:18:20 MPU9250: Error reading calibration data from /etc/mpu9250cal.json: open /etc/mpu9250cal.json: no such file or directory
2016/02/26 01:18:20 AHRS Error: couldn't initialize an IMU
2016/02/26 01:18:24 BMP280 Connection Attempt 1
2016/02/26 01:18:24 BMP280 Connection Attempt 2
2016/02/26 01:18:24 BMP280 Connection Attempt 3
2016/02/26 01:18:24 BMP280 Connection Attempt 4
2016/02/26 01:18:24 BMP280 Connection Attempt 5
2016/02/26 01:18:24 BMP280 Connection Attempt 1
2016/02/26 01:18:24 BMP280 Connection Attempt 2
2016/02/26 01:18:24 BMP280 Connection Attempt 3
2016/02/26 01:18:24 BMP280 Connection Attempt 4
2016/02/26 01:18:24 BMP280 Connection Attempt 5
2016/02/26 01:18:24 AHRS Info: couldn't initialize BMP280 or BMP180
2016/02/26 01:18:24 AHRS Info: attempting IMU connection.
2016/02/26 01:18:24 MPU9250: Error reading calibration data from /etc/mpu9250cal.json: open /etc/mpu9250cal.json: no such file or directory
2016/02/26 01:18:24 AHRS Error: couldn't initialize an IMU
2016/02/26 01:18:28 BMP280 Connection Attempt 1
2016/02/26 01:18:28 BMP280 Connection Attempt 2
2016/02/26 01:18:28 BMP280 Connection Attempt 3
2016/02/26 01:18:28 BMP280 Connection Attempt 4
2016/02/26 01:18:28 BMP280 Connection Attempt 5
2016/02/26 01:18:28 BMP280 Connection Attempt 1
2016/02/26 01:18:28 BMP280 Connection Attempt 2
2016/02/26 01:18:28 BMP280 Connection Attempt 3
2016/02/26 01:18:28 BMP280 Connection Attempt 4
2016/02/26 01:18:28 BMP280 Connection Attempt 5
2016/02/26 01:18:28 AHRS Info: couldn't initialize BMP280 or BMP180
2016/02/26 01:18:28 AHRS Info: attempting IMU connection.
2016/02/26 01:18:28 MPU9250: Error reading calibration data from /etc/mpu9250cal.json: open /etc/mpu9250cal.json: no such file or directory
2016/02/26 01:18:28 AHRS Error: couldn't initialize an IMU
2016/02/26 01:18:32 BMP280 Connection Attempt 1
2016/02/26 01:18:32 BMP280 Connection Attempt 2
2016/02/26 01:18:32 BMP280 Connection Attempt 3
2016/02/26 01:18:32 BMP280 Connection Attempt 4
2016/02/26 01:18:32 BMP280 Connection Attempt 5
2016/02/26 01:18:32 BMP280 Connection Attempt 1
2016/02/26 01:18:32 BMP280 Connection Attempt 2
2016/02/26 01:18:32 BMP280 Connection Attempt 3
2016/02/26 01:18:32 BMP280 Connection Attempt 4
2016/02/26 01:18:32 BMP280 Connection Attempt 5
2016/02/26 01:18:32 AHRS Info: couldn't initialize BMP280 or BMP180
2016/02/26 01:18:32 AHRS Info: attempting IMU connection.
2016/02/26 01:18:32 MPU9250: Error reading calibration data from /etc/mpu9250cal.json: open /etc/mpu9250cal.json: no such file or directory
2016/02/26 01:18:32 AHRS Error: couldn't initialize an IMU
2016/02/26 01:18:36 BMP280 Connection Attempt 1
2016/02/26 01:18:36 BMP280 Connection Attempt 2
2016/02/26 01:18:36 BMP280 Connection Attempt 3
2016/02/26 01:18:36 BMP280 Connection Attempt 4
2016/02/26 01:18:36 BMP280 Connection Attempt 5
2016/02/26 01:18:36 BMP280 Connection Attempt 1
2016/02/26 01:18:36 BMP280 Connection Attempt 2
2016/02/26 01:18:36 BMP280 Connection Attempt 3
2016/02/26 01:18:36 BMP280 Connection Attempt 4
2016/02/26 01:18:36 BMP280 Connection Attempt 5
2016/02/26 01:18:36 AHRS Info: couldn't initialize BMP280 or BMP180
2016/02/26 01:18:36 AHRS Info: attempting IMU connection.
2016/02/26 01:18:36 MPU9250: Error reading calibration data from /etc/mpu9250cal.json: open /etc/mpu9250cal.json: no such file or directory
2016/02/26 01:18:36 AHRS Error: couldn't initialize an IMU
2016/02/26 01:18:38 stats [started: 30 seconds ago]
2016/02/26 01:18:38  - Disk bytes used = 1.6 GB (86.1 %), Disk bytes free = 259 MB (13.9 %)
2016/02/26 01:18:38  - CPUTemp=40.78 deg C, MemStats.Alloc=2.5 MB, MemStats.Sys=8.8 MB, totalNetworkMessagesSent=5
2016/02/26 01:18:38  - CPU load 
2016/02/26 01:18:38  - UAT/min 0/0 [maxSS=0.00%], ES/min 587/587, Total traffic targets tracked=8
2016/02/26 01:18:38  - Network data messages sent: 0 total, 0 nonqueueable.  Network data bytes sent: 0 total, 0 nonqueueable.
2016/02/26 01:18:38  - Last GPS fix: 30 seconds ago, GPS solution type: 0 using 0 satellites (1/0 seen/tracked), NACp: 0, est accuracy 999999.00 m
2016/02/26 01:18:38  - GPS vertical velocity: 0.00 ft/sec; GPS vertical accuracy: 999999 m
2016/02/26 01:18:38  - Last IMU read: 30 seconds ago
2016/02/26 01:18:38  - Last BMP read: 30 seconds ago
2016/02/26 01:18:40 BMP280 Connection Attempt 1
2016/02/26 01:18:40 BMP280 Connection Attempt 2
2016/02/26 01:18:40 BMP280 Connection Attempt 3
2016/02/26 01:18:40 BMP280 Connection Attempt 4
2016/02/26 01:18:40 BMP280 Connection Attempt 5
2016/02/26 01:18:40 BMP280 Connection Attempt 1
2016/02/26 01:18:40 BMP280 Connection Attempt 2
2016/02/26 01:18:40 BMP280 Connection Attempt 3
2016/02/26 01:18:40 BMP280 Connection Attempt 4
2016/02/26 01:18:40 BMP280 Connection Attempt 5
2016/02/26 01:18:40 AHRS Info: couldn't initialize BMP280 or BMP180
2016/02/26 01:18:40 AHRS Info: attempting IMU connection.
2016/02/26 01:18:40 MPU9250: Error reading calibration data from /etc/mpu9250cal.json: open /etc/mpu9250cal.json: no such file or directory
2016/02/26 01:18:40 AHRS Error: couldn't initialize an IMU
2016/02/26 01:18:44 BMP280 Connection Attempt 1
2016/02/26 01:18:44 BMP280 Connection Attempt 2
2016/02/26 01:18:44 BMP280 Connection Attempt 3
2016/02/26 01:18:44 BMP280 Connection Attempt 4
2016/02/26 01:18:44 BMP280 Connection Attempt 5
2016/02/26 01:18:44 BMP280 Connection Attempt 1
2016/02/26 01:18:44 BMP280 Connection Attempt 2
2016/02/26 01:18:44 BMP280 Connection Attempt 3
2016/02/26 01:18:44 BMP280 Connection Attempt 4
2016/02/26 01:18:44 BMP280 Connection Attempt 5
2016/02/26 01:18:44 AHRS Info: couldn't initialize BMP280 or BMP180
2016/02/26 01:18:44 AHRS Info: attempting IMU connection.
2016/02/26 01:18:44 MPU9250: Error reading calibration data from /etc/mpu9250cal.json: open /etc/mpu9250cal.json: no such file or directory
2016/02/26 01:18:44 AHRS Error: couldn't initialize an IMU
2016/02/26 01:18:48 BMP280 Connection Attempt 1
2016/02/26 01:18:48 BMP280 Connection Attempt 2
2016/02/26 01:18:48 BMP280 Connection Attempt 3
2016/02/26 01:18:48 BMP280 Connection Attempt 4
2016/02/26 01:18:48 BMP280 Connection Attempt 5
2016/02/26 01:18:48 BMP280 Connection Attempt 1
2016/02/26 01:18:48 BMP280 Connection Attempt 2
2016/02/26 01:18:48 BMP280 Connection Attempt 3
2016/02/26 01:18:48 BMP280 Connection Attempt 4
2016/02/26 01:18:48 BMP280 Connection Attempt 5
2016/02/26 01:18:48 AHRS Info: couldn't initialize BMP280 or BMP180
2016/02/26 01:18:48 AHRS Info: attempting IMU connection.
2016/02/26 01:18:48 MPU9250: Error reading calibration data from /etc/mpu9250cal.json: open /etc/mpu9250cal.json: no such file or directory
2016/02/26 01:18:48 AHRS Error: couldn't initialize an IMU
2016/02/26 01:18:52 BMP280 Connection Attempt 1
2016/02/26 01:18:52 BMP280 Connection Attempt 2
2016/02/26 01:18:52 BMP280 Connection Attempt 3
2016/02/26 01:18:52 BMP280 Connection Attempt 4
2016/02/26 01:18:52 BMP280 Connection Attempt 5
2016/02/26 01:18:52 BMP280 Connection Attempt 1
2016/02/26 01:18:52 BMP280 Connection Attempt 2
2016/02/26 01:18:52 BMP280 Connection Attempt 3
2016/02/26 01:18:52 BMP280 Connection Attempt 4
2016/02/26 01:18:52 BMP280 Connection Attempt 5
2016/02/26 01:18:52 AHRS Info: couldn't initialize BMP280 or BMP180
2016/02/26 01:18:52 AHRS Info: attempting IMU connection.
2016/02/26 01:18:52 MPU9250: Error reading calibration data from /etc/mpu9250cal.json: open /etc/mpu9250cal.json: no such file or directory
2016/02/26 01:18:52 AHRS Error: couldn't initialize an IMU
2016/02/26 01:18:56 BMP280 Connection Attempt 1
2016/02/26 01:18:56 BMP280 Connection Attempt 2
2016/02/26 01:18:56 BMP280 Connection Attempt 3
2016/02/26 01:18:56 BMP280 Connection Attempt 4
2016/02/26 01:18:56 BMP280 Connection Attempt 5
2016/02/26 01:18:56 BMP280 Connection Attempt 1
2016/02/26 01:18:56 BMP280 Connection Attempt 2
2016/02/26 01:18:56 BMP280 Connection Attempt 3
2016/02/26 01:18:56 BMP280 Connection Attempt 4
2016/02/26 01:18:56 BMP280 Connection Attempt 5
2016/02/26 01:18:56 AHRS Info: couldn't initialize BMP280 or BMP180
2016/02/26 01:18:56 AHRS Info: attempting IMU connection.
2016/02/26 01:18:56 MPU9250: Error reading calibration data from /etc/mpu9250cal.json: open /etc/mpu9250cal.json: no such file or directory
2016/02/26 01:18:56 AHRS Error: couldn't initialize an IMU
2016/02/26 01:19:00 BMP280 Connection Attempt 1
2016/02/26 01:19:00 BMP280 Connection Attempt 2
2016/02/26 01:19:00 BMP280 Connection Attempt 3
2016/02/26 01:19:00 BMP280 Connection Attempt 4
2016/02/26 01:19:00 BMP280 Connection Attempt 5
2016/02/26 01:19:00 BMP280 Connection Attempt 1
2016/02/26 01:19:00 BMP280 Connection Attempt 2
2016/02/26 01:19:00 BMP280 Connection Attempt 3
2016/02/26 01:19:00 BMP280 Connection Attempt 4
2016/02/26 01:19:00 BMP280 Connection Attempt 5
2016/02/26 01:19:00 AHRS Info: couldn't initialize BMP280 or BMP180
2016/02/26 01:19:00 AHRS Info: attempting IMU connection.
2016/02/26 01:19:00 MPU9250: Error reading calibration data from /etc/mpu9250cal.json: open /etc/mpu9250cal.json: no such file or directory
2016/02/26 01:19:00 AHRS Error: couldn't initialize an IMU
2016/02/26 01:19:04 BMP280 Connection Attempt 1
2016/02/26 01:19:04 BMP280 Connection Attempt 2
2016/02/26 01:19:04 BMP280 Connection Attempt 3
2016/02/26 01:19:04 BMP280 Connection Attempt 4
2016/02/26 01:19:04 BMP280 Connection Attempt 5
2016/02/26 01:19:04 BMP280 Connection Attempt 1
2016/02/26 01:19:04 BMP280 Connection Attempt 2
2016/02/26 01:19:04 BMP280 Connection Attempt 3
2016/02/26 01:19:04 BMP280 Connection Attempt 4
2016/02/26 01:19:04 BMP280 Connection Attempt 5
2016/02/26 01:19:04 AHRS Info: couldn't initialize BMP280 or BMP180
2016/02/26 01:19:04 AHRS Info: attempting IMU connection.
2016/02/26 01:19:04 MPU9250: Error reading calibration data from /etc/mpu9250cal.json: open /etc/mpu9250cal.json: no such file or directory
2016/02/26 01:19:04 AHRS Error: couldn't initialize an IMU
2016/02/26 01:19:08 BMP280 Connection Attempt 1
2016/02/26 01:19:08 client connected: 192.168.10.11:4000 (Jim-HP).
2016/02/26 01:19:08 BMP280 Connection Attempt 2
2016/02/26 01:19:08 BMP280 Connection Attempt 3
2016/02/26 01:19:08 BMP280 Connection Attempt 4
2016/02/26 01:19:08 BMP280 Connection Attempt 5
2016/02/26 01:19:08 stats [started: 59 seconds ago]
2016/02/26 01:19:08  - Disk bytes used = 1.6 GB (86.2 %), Disk bytes free = 257 MB (13.8 %)
2016/02/26 01:19:08  - CPUTemp=39.70 deg C, MemStats.Alloc=3.9 MB, MemStats.Sys=9.9 MB, totalNetworkMessagesSent=11
2016/02/26 01:19:08  - CPU load 
2016/02/26 01:19:08  - UAT/min 0/0 [maxSS=0.00%], ES/min 1,291/1,291, Total traffic targets tracked=8
2016/02/26 01:19:08  - Network data messages sent: 0 total, 0 nonqueueable.  Network data bytes sent: 0 total, 0 nonqueueable.
2016/02/26 01:19:08  - Last GPS fix: 59 seconds ago, GPS solution type: 0 using 0 satellites (1/0 seen/tracked), NACp: 0, est accuracy 999999.00 m
2016/02/26 01:19:08  - GPS vertical velocity: 0.00 ft/sec; GPS vertical accuracy: 999999 m
2016/02/26 01:19:08  - Last IMU read: 59 seconds ago
2016/02/26 01:19:08  - Last BMP read: 59 seconds ago
2016/02/26 01:19:08 BMP280 Connection Attempt 1
2016/02/26 01:19:08 BMP280 Connection Attempt 2
2016/02/26 01:19:08 BMP280 Connection Attempt 3
2016/02/26 01:19:08 BMP280 Connection Attempt 4
2016/02/26 01:19:08 BMP280 Connection Attempt 5
2016/02/26 01:19:08 AHRS Info: couldn't initialize BMP280 or BMP180
2016/02/26 01:19:08 AHRS Info: attempting IMU connection.
2016/02/26 01:19:08 MPU9250: Error reading calibration data from /etc/mpu9250cal.json: open /etc/mpu9250cal.json: no such file or directory
2016/02/26 01:19:08 AHRS Error: couldn't initialize an IMU
2016/02/26 01:19:12 BMP280 Connection Attempt 1
2016/02/26 01:19:12 BMP280 Connection Attempt 2
2016/02/26 01:19:12 BMP280 Connection Attempt 3
2016/02/26 01:19:12 BMP280 Connection Attempt 4
2016/02/26 01:19:12 BMP280 Connection Attempt 5
2016/02/26 01:19:12 BMP280 Connection Attempt 1
2016/02/26 01:19:12 BMP280 Connection Attempt 2
2016/02/26 01:19:12 BMP280 Connection Attempt 3
2016/02/26 01:19:12 BMP280 Connection Attempt 4
2016/02/26 01:19:12 BMP280 Connection Attempt 5
2016/02/26 01:19:12 AHRS Info: couldn't initialize BMP280 or BMP180
2016/02/26 01:19:12 AHRS Info: attempting IMU connection.
2016/02/26 01:19:12 MPU9250: Error reading calibration data from /etc/mpu9250cal.json: open /etc/mpu9250cal.json: no such file or directory
2016/02/26 01:19:12 AHRS Error: couldn't initialize an IMU
2016/02/26 01:19:16 BMP280 Connection Attempt 1
2016/02/26 01:19:16 BMP280 Connection Attempt 2
2016/02/26 01:19:16 BMP280 Connection Attempt 3
2016/02/26 01:19:16 BMP280 Connection Attempt 4
2016/02/26 01:19:16 BMP280 Connection Attempt 5
2016/02/26 01:19:16 BMP280 Connection Attempt 1
2016/02/26 01:19:16 BMP280 Connection Attempt 2
2016/02/26 01:19:16 BMP280 Connection Attempt 3
2016/02/26 01:19:16 BMP280 Connection Attempt 4
2016/02/26 01:19:16 BMP280 Connection Attempt 5
2016/02/26 01:19:16 AHRS Info: couldn't initialize BMP280 or BMP180
2016/02/26 01:19:16 AHRS Info: attempting IMU connection.
2016/02/26 01:19:16 MPU9250: Error reading calibration data from /etc/mpu9250cal.json: open /etc/mpu9250cal.json: no such file or directory
2016/02/26 01:19:16 AHRS Error: couldn't initialize an IMU
2016/02/26 01:19:20 BMP280 Connection Attempt 1
2016/02/26 01:19:20 BMP280 Connection Attempt 2
2016/02/26 01:19:20 BMP280 Connection Attempt 3
2016/02/26 01:19:20 BMP280 Connection Attempt 4
2016/02/26 01:19:20 BMP280 Connection Attempt 5
2016/02/26 01:19:20 BMP280 Connection Attempt 1
2016/02/26 01:19:20 BMP280 Connection Attempt 2
2016/02/26 01:19:20 BMP280 Connection Attempt 3
2016/02/26 01:19:20 BMP280 Connection Attempt 4
2016/02/26 01:19:20 BMP280 Connection Attempt 5
2016/02/26 01:19:20 AHRS Info: couldn't initialize BMP280 or BMP180
2016/02/26 01:19:20 AHRS Info: attempting IMU connection.
2016/02/26 01:19:20 MPU9250: Error reading calibration data from /etc/mpu9250cal.json: open /etc/mpu9250cal.json: no such file or directory
2016/02/26 01:19:20 AHRS Error: couldn't initialize an IMU
2016/02/26 01:19:24 BMP280 Connection Attempt 1
2016/02/26 01:19:24 BMP280 Connection Attempt 2
2016/02/26 01:19:24 BMP280 Connection Attempt 3
2016/02/26 01:19:24 BMP280 Connection Attempt 4
2016/02/26 01:19:24 BMP280 Connection Attempt 5
2016/02/26 01:19:24 BMP280 Connection Attempt 1
2016/02/26 01:19:24 BMP280 Connection Attempt 2
2016/02/26 01:19:24 BMP280 Connection Attempt 3
2016/02/26 01:19:24 BMP280 Connection Attempt 4
2016/02/26 01:19:24 BMP280 Connection Attempt 5
2016/02/26 01:19:24 AHRS Info: couldn't initialize BMP280 or BMP180
2016/02/26 01:19:24 AHRS Info: attempting IMU connection.
2016/02/26 01:19:24 MPU9250: Error reading calibration data from /etc/mpu9250cal.json: open /etc/mpu9250cal.json: no such file or directory
2016/02/26 01:19:24 AHRS Error: couldn't initialize an IMU
2016/02/26 01:19:28 BMP280 Connection Attempt 1
2016/02/26 01:19:28 BMP280 Connection Attempt 2
2016/02/26 01:19:28 BMP280 Connection Attempt 3
2016/02/26 01:19:28 BMP280 Connection Attempt 4
2016/02/26 01:19:28 BMP280 Connection Attempt 5
2016/02/26 01:19:28 BMP280 Connection Attempt 1
2016/02/26 01:19:28 BMP280 Connection Attempt 2
2016/02/26 01:19:28 BMP280 Connection Attempt 3
2016/02/26 01:19:28 BMP280 Connection Attempt 4
2016/02/26 01:19:28 BMP280 Connection Attempt 5
2016/02/26 01:19:28 AHRS Info: couldn't initialize BMP280 or BMP180
2016/02/26 01:19:28 AHRS Info: attempting IMU connection.
2016/02/26 01:19:28 MPU9250: Error reading calibration data from /etc/mpu9250cal.json: open /etc/mpu9250cal.json: no such file or directory
2016/02/26 01:19:28 AHRS Error: couldn't initialize an IMU
2016/02/26 01:19:32 BMP280 Connection Attempt 1
2016/02/26 01:19:32 BMP280 Connection Attempt 2
2016/02/26 01:19:32 BMP280 Connection Attempt 3
2016/02/26 01:19:32 BMP280 Connection Attempt 4
2016/02/26 01:19:32 BMP280 Connection Attempt 5
2016/02/26 01:19:32 BMP280 Connection Attempt 1
2016/02/26 01:19:32 BMP280 Connection Attempt 2
2016/02/26 01:19:32 BMP280 Connection Attempt 3
2016/02/26 01:19:32 BMP280 Connection Attempt 4
2016/02/26 01:19:32 BMP280 Connection Attempt 5
2016/02/26 01:19:32 AHRS Info: couldn't initialize BMP280 or BMP180
2016/02/26 01:19:32 AHRS Info: attempting IMU connection.
2016/02/26 01:19:32 MPU9250: Error reading calibration data from /etc/mpu9250cal.json: open /etc/mpu9250cal.json: no such file or directory
2016/02/26 01:19:32 AHRS Error: couldn't initialize an IMU
2016/02/26 01:19:36 BMP280 Connection Attempt 1
2016/02/26 01:19:36 BMP280 Connection Attempt 2
2016/02/26 01:19:36 BMP280 Connection Attempt 3
2016/02/26 01:19:36 BMP280 Connection Attempt 4
2016/02/26 01:19:36 BMP280 Connection Attempt 5
2016/02/26 01:19:36 BMP280 Connection Attempt 1
2016/02/26 01:19:36 BMP280 Connection Attempt 2
2016/02/26 01:19:36 BMP280 Connection Attempt 3
2016/02/26 01:19:36 BMP280 Connection Attempt 4
2016/02/26 01:19:36 BMP280 Connection Attempt 5
2016/02/26 01:19:36 AHRS Info: couldn't initialize BMP280 or BMP180
2016/02/26 01:19:36 AHRS Info: attempting IMU connection.
2016/02/26 01:19:36 MPU9250: Error reading calibration data from /etc/mpu9250cal.json: open /etc/mpu9250cal.json: no such file or directory
2016/02/26 01:19:36 AHRS Error: couldn't initialize an IMU
2016/02/26 01:19:38 stats [started: 1 minute ago]
2016/02/26 01:19:38  - Disk bytes used = 1.6 GB (86.2 %), Disk bytes free = 257 MB (13.8 %)
2016/02/26 01:19:38  - CPUTemp=40.78 deg C, MemStats.Alloc=3.2 MB, MemStats.Sys=9.9 MB, totalNetworkMessagesSent=164
2016/02/26 01:19:38  - CPU load 
2016/02/26 01:19:38  - UAT/min 0/0 [maxSS=0.00%], ES/min 1,737/1,737, Total traffic targets tracked=10
2016/02/26 01:19:38  - Network data messages sent: 141 total, 141 nonqueueable.  Network data bytes sent: 4113 total, 4113 nonqueueable.
2016/02/26 01:19:38  - Last GPS fix: 1 minute ago, GPS solution type: 0 using 0 satellites (1/0 seen/tracked), NACp: 0, est accuracy 999999.00 m
2016/02/26 01:19:38  - GPS vertical velocity: 0.00 ft/sec; GPS vertical accuracy: 999999 m
2016/02/26 01:19:38  - Last IMU read: 1 minute ago
2016/02/26 01:19:38  - Last BMP read: 1 minute ago
2016/02/26 01:19:40 BMP280 Connection Attempt 1
2016/02/26 01:19:40 BMP280 Connection Attempt 2
2016/02/26 01:19:40 BMP280 Connection Attempt 3
2016/02/26 01:19:40 BMP280 Connection Attempt 4
2016/02/26 01:19:40 BMP280 Connection Attempt 5
2016/02/26 01:19:40 BMP280 Connection Attempt 1
2016/02/26 01:19:40 BMP280 Connection Attempt 2
2016/02/26 01:19:40 BMP280 Connection Attempt 3
2016/02/26 01:19:40 BMP280 Connection Attempt 4
2016/02/26 01:19:40 BMP280 Connection Attempt 5
2016/02/26 01:19:40 AHRS Info: couldn't initialize BMP280 or BMP180
2016/02/26 01:19:40 AHRS Info: attempting IMU connection.
2016/02/26 01:19:40 MPU9250: Error reading calibration data from /etc/mpu9250cal.json: open /etc/mpu9250cal.json: no such file or directory
2016/02/26 01:19:40 AHRS Error: couldn't initialize an IMU
2016/02/26 01:19:44 BMP280 Connection Attempt 1
2016/02/26 01:19:44 BMP280 Connection Attempt 2
2016/02/26 01:19:44 BMP280 Connection Attempt 3
2016/02/26 01:19:44 BMP280 Connection Attempt 4
2016/02/26 01:19:44 BMP280 Connection Attempt 5
2016/02/26 01:19:44 BMP280 Connection Attempt 1
2016/02/26 01:19:44 BMP280 Connection Attempt 2
2016/02/26 01:19:44 BMP280 Connection Attempt 3
2016/02/26 01:19:44 BMP280 Connection Attempt 4
2016/02/26 01:19:44 BMP280 Connection Attempt 5
2016/02/26 01:19:44 AHRS Info: couldn't initialize BMP280 or BMP180
2016/02/26 01:19:44 AHRS Info: attempting IMU connection.
2016/02/26 01:19:44 MPU9250: Error reading calibration data from /etc/mpu9250cal.json: open /etc/mpu9250cal.json: no such file or directory
2016/02/26 01:19:44 AHRS Error: couldn't initialize an IMU

**Comment by TArrowJim** [comment]
OK, still now 978 Weather but that is likely because I'm on the ground, right?
It took driving around for 15 minutes or so to finally get a GPS fix and once obtained it is much easier to get it from my 4th floor office.
Perhaps a heads up for new users.

**Comment by cyoung** [comment]
Upgrade to [v1.4r2](https://github.com/cyoung/stratux/releases/tag/v1.4r2).

You're right about the towers on the ground. See here for a map: http://towers.stratux.me.
