### ISSUE TITLE
Question about EFB

### ISSUE THREAD

**Issue by Rorsta** [cyoung/stratux#674]
1. Stratux version:
2. Stratux config:

    SDR
      - [ ] single
      - [ ] dual

    GPS
      - [ ] yes
      - [ ] no
      type:

    AHRS
      - [ ] yes
      - [ ] no

    power source:

    usb cable:

3. EFB app and version: (e.g., WingX Pro7 8.6.2)

    EFB platform: (e.g., iOS 9.2)

    EFB hardware: (e.g., iPad Mini 2)

4. Description of your issue: I'm just wanting to know if the stratux can be used with the garmin pilot app?
Cheers,
Rory

If possible, enable "Replay Logs", reproduce the problem, and provide a copy of the logs in http://192.168.10.1/logs/stratux/ and http://192.168.10.1/logs/stratux.log.

**Comment by cyoung** [comment]
Hi Rory,

Sorry, Stratux can't be used with Garmin Pilot. They use proprietary protocols that we haven't attempted to implement yet.
