### ISSUE TITLE
Dangerzone IP Alias Issues

### ISSUE THREAD

**Issue by calonmerc** [cyoung/stratux#675]
1. Stratux version: 1.4r3 (3d57564490
2. Stratux config:

    SDR
      - [ ] single
      - [x] dual

    GPS
      - [x] yes
      - [ ] no
      type:

    AHRS
      - [ ] yes
      - [x] no

    power source: 2.1A wall wart

    usb cable: known good cable

3. EFB app and version: Foreflight, but using web browser (Chrome).

    EFB platform: iOS 11.0.03

    EFB hardware: iPad Mini 2

4. Description of your issue: The IP alias mentioned by cyoung at 192.168.10.1 seems to have connection issues and/or delay issues. Running Dangerzone, I can connect to 10.26.36.1 flawlessly. Trying to connect to 192.168.10.1 appears to be extremely sluggish and also appears to not connect.
This time, I tried it with a fresh dangerzone install, gave it 10 minutes to fully boot, went direct to browser. 192.168.10.1 loads the display, but the version field is not filled in and none of the settings screen have the right details. I opened a new tab, loaded the 10.26.36.1 address. Everything in the second tab loads fine, immediately. Go back to the first tab, same state. Force refresh the browser, same state. I let it load for 3-5 minutes, paying attention to my laptop, and then all of the details in the 192.168.10.1 page are loaded correctly. @cyoung mentioned posting an issue, so here we go!

**Comment by cyoung** [comment]
Looks like an issue, but probably not going to fix it.

Use http://10.26.36.1/ for now.
