### ISSUE TITLE
Adafruit gps

### ISSUE THREAD

**Issue by Austinthemighty** [cyoung/stratux#683]
1. Stratux version: v1.4r3
2. Stratux config:

    SDR
      - [ ] single
      - [x] dual

    GPS
      - [x] yes
      - [ ] no
      type:

    AHRS
      - [ ] yes
      - [x] no

    power source: 3amp power brick

Description of your issue:

Adafruit Gps No longer works with v1.4r3.  I think something in the code changed that is preventing it from working

**Comment by cyoung** [comment]
Not supported hardware. There are some known issues with GPS via RPi UART, but we're not focusing on them as there are no supported hardware configurations that use it.
