### ISSUE TITLE
link to amazon is broken

### ISSUE THREAD

**Issue by jhjulkun** [cyoung/stratux#686]
The link to Amazon for the pass through battery pack with cable appears to be broken.
Since I'm not familiar with the product can you please suggest a replacement ?

Thanks!

https://www.amazon.com/gp/product/B00ZWUZG70/ref=as_li_tl?ie=UTF8&camp=1789&creative=9325&creativeASIN=B00ZWUZG70&linkCode=as2&tag=stratux-20&linkId=1187c1e509da863c8a8c353dbebde378

**Comment by cyoung** [comment]
They stopped selling this battery on Amazon. There are some similar offerings. Website links were updated.
