### ISSUE TITLE
Bluetooth connection to EFB

### ISSUE THREAD

**Issue by spectasaurus** [cyoung/stratux#689]
Just wondering if there is any technical reason why Stratux wouldn't be able to connect to an EFB (eg, ForeFlight) using Bluetooth?  Is the bandwidth not sufficient?  I know it would be nice to use Bluetooth in order for my ipad to continue to receive cellular data while flying.

**Comment by pp4life** [comment]
https://www.reddit.com/r/stratux/comments/4sv2c6/using_stratux_over_bluetooth/

**Comment by spectasaurus** [comment]
Thank you.  I was not aware of this thread.
