### ISSUE TITLE
Stratux Webradar for non ES targets

### ISSUE THREAD

**Issue by dns-007** [cyoung/stratux#699]
1. Stratux version:
2. Stratux config:

    SDR
      - [ ] single
      - [x ] dual

    GPS
      - [ x] yes
      - [ ] no
      type:

    AHRS
      - [ x] yes
      - [ ] no

    power source:

    usb cable:

3. EFB app and version: (e.g., WingX Pro7 8.6.2)

    EFB platform: (e.g., iOS 9.2)

    EFB hardware: (e.g., iPad Mini 2)

4. Description of your issue:

This is a reply to request https://github.com/cyoung/stratux/issues/346  
Flying in Europe, there are not that many GA planes with ADS-B out. But a lot planes have a Transponder and send at least their height. So this is a Webradar, that filter planes in your hight +-1000 ft and based on the Signal strength, determinds if the other plane is incomming. 
The big question behind this, may be if Stratux gets a kind of "second screen" in addition to your moving map Tablet, there could be a second smaller Tables/Smartphone that shows this Webradar and maybe the "artificial horizon" or other Information like weather info?
Comments and questions welcome. 
Greetings from Germany, Joern

**Comment by cyoung** [comment]
Joern, sorry for the late response. This seems to be a question about Mode-C/Mode-S non-position reporting traffic.

See #346. The issue has been discussed at length. For the time being, we likely will not attempt to implement this because there is too much hardware variation.
