### ISSUE TITLE
gen_gdl90 faults, runtime/cgo: pthread_create failed: resource temporarily unavailable

### ISSUE THREAD

**Issue by d-hoke** [cyoung/stratux#701]
1. Stratux version: v1.4r4 (5af6d77583)
2. Stratux config: (pre-built unit recently obtained from CrewDogElectronics)

    SDR
      - [ ] single
      - [x] dual

    GPS
      - [x] yes
      - [ ] no
      type:

    AHRS
      - [x] yes
      - [ ] no

    power source: ipad charger pass through battery (which was fully charged at least on 2nd incident)

    usb cable: from EasyAcc battery

3. EFB app and version: (e.g., WingX Pro7 8.6.2) web browsers, chrome from nexus tablet, firefox from linux (puppy slacko)

    EFB platform: (e.g., iOS 9.2)

    EFB hardware: (e.g., iPad Mini 2)

4. Description of your issue: 
background - benchtesting stratux unit (***only even noticed because of being in developer mode which output a message about uptime and daemon being restarted)

issue
gen_gdl90 has faulted twice in past 24-36 hours
[gengdl90faultsextract.zip](https://github.com/cyoung/stratux/files/1860337/gengdl90faultsextract.zip)
, with daemon.log reporting (snippet of first fault follows, full extracts in attached file):
Mar 28 22:29:10 raspberrypi gen_gdl90[482]: runtime/cgo: pthread_create failed: Resource temporarily unavailable
Mar 28 22:29:10 raspberrypi gen_gdl90[482]: SIGABRT: abort

ulimits -a from pi system:
core file size          (blocks, -c) 0
data seg size           (kbytes, -d) unlimited
scheduling priority             (-e) 0
file size               (blocks, -f) unlimited
pending signals                 (-i) 7338
max locked memory       (kbytes, -l) 64
max memory size         (kbytes, -m) unlimited
open files                      (-n) 65536
pipe size            (512 bytes, -p) 8
POSIX message queues     (bytes, -q) 819200
real-time priority              (-r) 0
stack size              (kbytes, -s) 8192
cpu time               (seconds, -t) unlimited
max user processes              (-u) 7338
virtual memory          (kbytes, -v) unlimited
file locks                      (-x) unlimited

(top of) one top iteration AFTER restart had occurred some hours ago:
top - 13:57:25 up 1 day, 18:37,  1 user,  load average: 2.42, 2.28, 1.94
Tasks:  88 total,   3 running,  85 sleeping,   0 stopped,   0 zombie
%Cpu(s): 11.4 us,  3.1 sy,  0.0 ni, 84.9 id,  0.4 wa,  0.0 hi,  0.3 si,  0.0 st
KiB Mem:    948012 total,   322340 used,   625672 free,    65256 buffers
KiB Swap:   102396 total,        0 used,   102396 free.   153852 cached Mem

  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND
11414 root      20   0 1448588  21920   8780 S  66.6  2.3 130:21.82 gen_gdl90
15717 root      20   0   28100   9800   2152 R  12.1  1.0  10:10.89 dump1090
  191 root      -2   0       0      0      0 S   6.1  0.0   7:16.06 ksdioirqd/+
16220 pi        20   0    5112   2368   2092 R   6.1  0.2   0:00.03 top
    1 root      20   0    5448   3992   2792 S   0.0  0.4   0:08.27 systemd

Will explore "Replay logs", and add results if any obtained, not yet familiar with that...

If possible, enable "Replay Logs", reproduce the problem, and provide a copy of the logs in http://192.168.10.1/logs/stratux/ and http://192.168.10.1/logs/stratux.log.
(none obtained yet)

**Comment by cyoung** [comment]
Hmm. Did this repeat after upgrading to the latest?

**Comment by cyoung** [comment]
Re-open if you're able to reproduce the problem.
