### ISSUE TITLE
gps.go, questionable handling of mySituation.AHRSGyroHeading in func makeAHRSGDL90Report()

### ISSUE THREAD

**Issue by d-hoke** [cyoung/stratux#705]
1. Stratux version: v1.4r4 (5af6d77)
2. Stratux config: irrelevant (I think) but its dual radio, GPS/AHRS, RPi3 

4. Description of your issue: 
Following code from main/gps.go:func makeAHRSGDL90Report():
`		if isAHRSInvalidValue(mySituation.AHRSGyroHeading) {
			hdg = roundToInt16(mySituation.AHRSGyroHeading * 10) // TODO westphae: switch to AHRSMagHeading?
		} else {
			hdg = roundToInt16(float64(mySituation.GPSTrueCourse))
		}
`

seems questionable in at least two respects:
1) Appears to be using a value that is found to be invalid
2) in the else branch, the value used is not scaled by 10, as seems to be done with all the other values in that general section of code subject to 
`if isAHRSValid() {
  ...
}
`

**Comment by cyoung** [comment]
Not able to investigate now -- @westphae, any thoughts?

**Comment by westphae** [comment]
I believe this comment is correct.  Working on validating the result in the gdl90 stream; once validated, will correct, test and push.  Currently this has little to no impact as no EFB's that I know of report the gyro heading.

**Comment by westphae** [comment]
Created a PR at https://github.com/cyoung/stratux/pull/720 to fix this.

**Comment by cyoung** [comment]
Excellent.
