### ISSUE TITLE
FIS-B Changes/Upgrades 2018

### ISSUE THREAD

**Issue by AMNegron** [cyoung/stratux#712]
Will there be any updates or changes required to Stratux code to support the anticipated changes to the FIS-B data stream coming later this year?

![img_1371](https://user-images.githubusercontent.com/16216815/39255076-44c46ebc-4871-11e8-96b9-efa78315dca3.JPG)

[AOPA1804_ADSB-In.pdf](https://github.com/cyoung/stratux/files/1947644/AOPA1804_ADSB-In.pdf)

**Comment by cyoung** [comment]
@AMNegron - thanks for asking. We won't need to make any changes to support these products. EFBs will need to make a change to display them, but they will receive them without any changes to Stratux.
