### ISSUE TITLE
Stratux v1.4r5 totally failed on me (no WiFi, etc.)

### ISSUE THREAD

**Issue by Ergonomicmike** [cyoung/stratux#714]
1. Stratux version: v1.4r5
2. Stratux config: 

    SDR
      - [ ] single
      - [X] dual

    GPS
      - [X] yes
      - [ ] no
      type: the Puck one

    AHRS
      - [X ] yes
      - [ ] no

    power source: Anker

    usb cable: Anker

3. EFB app and version: (e.g., WingX Pro7 8.6.2) iFly 10.3.2b

    EFB platform: (e.g., iOS 9.2) Android LL

    EFB hardware: (e.g., iPad Mini 2) Asus Zen Pad

4. Description of your issue: 

I flew last week with a fresh image of v1.4r5 on a 16GB micro SD. I did NOT expand the file system. 

When I flew last week, I had logging running to gather data, because iFly wasn't getting GPS data from the new version of Stratux. During those flights, I was able to connect to the Stratux via WiFi and get Traffic Info for my outbound and inbound flight. (About an hour each, total two hours.) I did not think to check if Wx data was getting thru to iFly. But because iFly's Altimeter setting was updating itself for the flight (via ADS--B), I must have been receiving wx data okay.

Flew the same Stratux with the same sd card today. Before the flight, I tapped the "Delete Logs" buttons in the Developer's options. (BTW, Developer's Options isn't persisting for me like it used to in prior versions.) The log sizes showed "0."

When I first started Stratux and iFly today, I saw traffic right away around the airport, I.e,, the Stratux was working fine. (Except for the fact that I still couldn't get GPS info from the Stratux (despite a recent fix to iFly - have commented about that elsewhere in the github), 

I did see a warning in red letters on the Web UI warning something about low disk space. 

Then, somewhere about half way thru the trip, I noticed that I wasn't getting any wx info in iFly. (Because iFly's Altimeter setting wasn't updating.)

Judging from the "last update" of NEXRAD, I hadn't gotten any weather data after I taken off.

When I got to my destination, I tried to gather data for you all. But now the Stratux wasn't sending a signal over WiFi.

So I pulled the micro SD and put in my old v1.4r4 card and flew home without any issues.

I'm gonna guess that my sdcard is full, because even tho I thought I had deleted the Replay logs, there's still a large sqlite file on the card. (I ran fschk on the card at home. It reported "Clean.")

Before re-imaging (and then expanding the file system) on the card to try again later, I thought I would attach what logs I had from today's flying.

If possible, enable "Replay Logs", reproduce the problem, and provide a copy of the logs in http://192.168.10.1/logs/stratux/ and http://192.168.10.1/logs/stratux.log.

[Stratux.fail.zip](https://github.com/cyoung/stratux/files/1976350/Stratux.fail.zip)

**Comment by Ergonomicmike** [comment]
More data. 

I took the SD card and stuck it in a linux box. Some utility reports 1.7 GB used, 75 MB free.

When I used gdmap to look at what is taking up all the space, nothing humongous jumps out. There's the stratux.sqlite file at 291 MB. Everything else is smaller. (Linux swap next at 100 MB.) Nevertheless, gdmap shows a total size of 1.52 GB.

Lots of little things, I guess. Am going to reimage the card and start fresh.

**Comment by Ergonomicmike** [comment]
Not having heard if anyone wanted more info on what was on my card, I re-imaged tonight, expanded the file system, and now Stratux 1.4r5 is back on the air. (Guess I could have done a Read operation with ImageWriter to save the contents. Too late now.)

**Comment by d-hoke** [comment]
(peanut gallery observations)
Regarding default base image size
On each of the three units I have seen, the included sd card was only 2GB, so think default base image size is probably <= 2GB.  
The dev tools that seemed to be part of some earlier images are not present in v1.4r4, possibly due to expanding footprint of actual stratux system, such that everything didn't fit within the 2GB base.

**Comment by Ergonomicmike** [comment]
Thanks d-hoke. 

I'm going to close this issue since 1) I fixed it by reimaging and expanding the file system and 2) since I didn't keep the data for the developers to see what went wrong. 

Am still confused tho. I thought that there had been changes to the logging stuff that was supposed to keep the card from filling up and failing like this. (Although, as above, it didn't look it was the normal logs that took up the space. Something else going on.)
