### ISSUE TITLE
Settings page uncomplete in 1.4r5

### ISSUE THREAD

**Issue by dns-007** [cyoung/stratux#716]
1. Stratux version:
2. Stratux config:

    SDR
      - [ ] single
      - [x ] dual

    GPS
      - [ x] yes
      - [ ] no
      type:

    AHRS
      - [ x] yes
      - [ ] no

    power source:
grid
    usb cable:

3. EFB app and version: (e.g., WingX Pro7 8.6.2)

4. Description of your issue:

On The Settings Page, the categories "Diagnostic" and "Hardware" are missing. This is right after the installation of the Sd card, so no hacking done. Is this a bug or a feature?
Can someone confirm this problem? 
Thanks!

**Comment by cyoung** [comment]
Feature. These were moved to "Developer Mode". They shouldn't be needed for normal operation. If you need them for testing, hit the version number on the status page 7 times in rapid succession to enter "Developer Mode".
