### ISSUE TITLE
Success of graceful shutdown changes, commit 92dab3802843134a0a1b1e25d23f700292969bb0 questionable

### ISSUE THREAD

**Issue by d-hoke** [cyoung/stratux#717]
Regarding commit at https://github.com/cyoung/stratux/commit/92dab3802843134a0a1b1e25d23f700292969bb0

From comment previously added to the commit:
"If I understand docs correctly, gracefulShutdown() will not be called if either of those .Reboot() calls is successful.
from http://man7.org/linux/man-pages/man2/reboot.2.html
"For the values of cmd that stop or restart the system, a successful
call to reboot() does not return."

Unless you only wanted to call gracefulShutdown() if the .Reboot() calls failed, then...
Consider modifying gracefulShutdown() to take a parameter about whether to exit or not (it currently appears to exit at its end), move the gracefulShutdown() calls before reboot, and use the parameter to
not exit when called from before the .Reboot()s..."

(Was uncertain if the comment had been seen.  If it had, sorry for the noise here.)

**Comment by cyoung** [comment]
92dab3802843134a0a1b1e25d23f700292969bb0

Will fix.
