### ISSUE TITLE
 Entered UAT shutdown() )no data)

### ISSUE THREAD

**Issue by boa888** [cyoung/stratux#718]
1. Stratux version: .4r5
2. Stratux config:

    SDR
      - [ ] single
      - [x ] dual

    GPS
      - [ x] yes
      - [ ] no
      type:

    AHRS
      - [x ] yes
      - [ ] no

    power source: 2.4A @5V via 12V cigarette USB outlet

    usb cable: Anker 

3. EFB app and version: (e.g., WingX Pro7 8.6.2) iFlyGPS 10.2.75

    EFB platform: (e.g., iOS 9.2) Android

    EFB hardware: (e.g., iPad Mini 2) Samsung Tab 4

4. Description of your issue: Drops towers 

If possible, enable "Replay Logs", reproduce the problem, and provide a copy of the logs in http://192.168.10.1/logs/stratux/ and http://192.168.10.1/logs/stratux.log.

I am dropping towers during flight and have to reboot to get the towers back. I have no idea how to read these logs but looking over the logs timestamp I believe I am losing them at 
**"Entered UAT shutdown( )"**
after which I notice UAT 0/1,388
When I "pull the plug" and restart I see
**Entered uatReader( )**
Does this shed any light on why I am losing towers and have to restart?
************************************************************************

 AHRS Gyro/Accel Error: MPU9250 Error: No new accel/gyro values
2018/05/12 18:53:17 stats [started: 6 minutes ago]
2018/05/12 18:53:17  - Disk bytes used = 1.4 GB (81.6 %), Disk bytes free = 325 MB (18.4 %)
2018/05/12 18:53:17  - CPUTemp=65.53 deg C, MemStats.Alloc=6.8 MB, MemStats.Sys=17 MB, totalNetworkMessagesSent=35,451
2018/05/12 18:53:17  - **UAT/min 1,363/1,388** [maxSS=93.20%], ES/min 629/2,141, Total traffic targets tracked=103
2018/05/12 18:53:17  - Network data messages sent: 35143 total, 32005 nonqueueable.  Network data bytes sent: 6189752 total, 1186870 nonqueueable.
2018/05/12 18:53:17  - Last GPS fix: now, GPS solution type: 2 using 10 satellites (16/18 seen/tracked), NACp: 11, est accuracy 0.62 m
2018/05/12 18:53:17  - GPS vertical velocity: -1.97 ft/sec; GPS vertical accuracy: 1.24 m
2018/05/12 18:53:17 - Last IMU read: now, Last BMP read: now
2018/05/12 18:53:17 **Entered UAT shutdown() .**..
2018/05/12 18:53:17 UAT shutdown(): calling u.wg.Wait() ...
2018/05/12 18:53:17 UAT read(): shutdown msg received...
2018/05/12 18:53:17 UAT shutdown(): u.wg.Wait() returned...
2018/05/12 18:53:17 UAT shutdown(): closing device ...
2018/05/12 18:53:17 UAT shutdown() complete ...
2018/05/12 18:53:47 stats [started: 6 minutes ago]
2018/05/12 18:53:47  - Disk bytes used = 1.4 GB (81.6 %), Disk bytes free = 325 MB (18.4 %)
2018/05/12 18:53:47  - CPUTemp=64.45 deg C, MemStats.Alloc=7.5 MB, MemStats.Sys=17 MB, totalNetworkMessagesSent=37,414
2018/05/12 18:53:47  - **UAT/min 722/1,388** [maxSS=93.20%], ES/min 574/2,141, Total traffic targets tracked=104
2018/05/12 18:53:47  - Network data messages sent: 37082 total, 33944 nonqueueable.  Network data bytes sent: 6248110 total, 1245228 nonqueueable.
2018/05/12 18:53:47  - Last GPS fix: now, GPS solution type: 2 using 10 satellites (16/18 seen/tracked), NACp: 11, est accuracy 0.62 m
2018/05/12 18:53:47  - GPS vertical velocity: -8.57 ft/sec; GPS vertical accuracy: 1.24 m
2018/05/12 18:53:47 - Last IMU read: now, Last BMP read: now
2018/05/12 18:54:17 stats [started: 7 minutes ago]
2018/05/12 18:54:17  - Disk bytes used = 1.4 GB (81.6 %), Disk bytes free = 325 MB (18.4 %)
2018/05/12 18:54:17  - CPUTemp=63.38 deg C, MemStats.Alloc=6.4 MB, MemStats.Sys=17 MB, totalNetworkMessagesSent=39,043
2018/05/12 18:54:17  - **UAT/min 0/1,388** [maxSS=93.20%], ES/min 299/2,141, Total traffic targets tracked=106
2018/05/12 18:54:17  - Network data messages sent: 38687 total, 35549 nonqueueable.  Network data bytes sent: 6290228 total, 1287346 nonqueueable.
2018/05/12 18:54:17  - Last GPS fix: now, GPS solution type: 2 using 10 satellites (16/18 seen/tracked), NACp: 11, est accuracy 0.62 m
2018/05/12 18:54:17  - GPS vertical velocity: 1.97 ft/sec; GPS vertical accuracy: 1.24 m
****************************************************
After pulling the plug
*******************************************************
2018/05/12 17:17:13 Stratux v1.4r5 (991f48eaa57c5701a7743c8d6d6f2e41cf4a3382) starting.
2018/05/12 17:17:13 **Entered uatReader() ...**
2018/05/12 17:17:13 read in settings.
2018/05/12 17:17:13 client connected: 192.168.10.15:4000 ().
2018/05/12 17:17:13 client connected: 192.168.10.11:4000 ().
2018/05/12 17:17:13 client connected: 192.168.10.14:4000 (android-69658b566e759354).
2018/05/12 17:17:13 client connected: 192.168.10.10:4000 (android-5f25f483b3245aab).
2018/05/12 17:17:13 AHRS Info: IMU Calibrations read from settings: accel -0.974139 -0.021834 0.177801; gyro 0.995972 1.262856 -0.565813
2018/05/12 17:17:14 AHRS Info: IMU Calibrations read from settings: accel -0.974139 -0.021834 0.177801; gyro 0.995972 1.262856 -0.565813
2018/05/12 17:17:15 AHRS Info: IMU Calibrations read from settings: accel -0.974139 -0.021834 0.177801; gyro 0.995972 1.262856 -0.565813
2018/05/12 17:17:16 AHRS Info: IMU Calibrations read from settings: accel -0.974139 -0.021834 0.177801; gyro 0.995972 1.262856 -0.565813
2018/05/12 17:17:17 AHRS Info: IMU Calibrations read from settings: accel -0.974139 -0.021834 0.177801; gyro 0.995972 1.262856 -0.565813
2018/05/12 17:17:17 GPS error. Invalid NMEA string: Invalid NMEA message
2018/05/12 17:17:18 GPS detected: u-blox NMEA position message seen.
2018/05/12 17:17:18 setting system time to: '20180512 18:57:04.000 UTC'
2018/05/12 18:57:04 Time set from GPS. Current time is 2018-05-12 18:57:04.000661197 +0000 UTC
2018/05/12 18:57:04 AHRS Info: IMU Calibrations read from settings: accel -0.974139 -0.021834 0.177801; gyro 0.995972 1.262856 -0.565813
2018/05/12 18:57:04 MPU9250 mag data not ready or overflow
2018/05/12 18:57:04 MPU9250 m1 LSB: EE
2018/05/12 18:57:29 stats [started: 30 seconds ago]
2018/05/12 18:57:29  - Disk bytes used = 1.4 GB (81.6 %), Disk bytes free = 324 MB (18.4 %)
2018/05/12 18:57:29  - CPUTemp=62.30 deg C, MemStats.Alloc=3.2 MB, MemStats.Sys=7.7 MB, totalNetworkMessagesSent=790
2018/05/12 18:57:29  - **UAT/min 0/0** [maxSS=0.00%], ES/min 0/0, Total traffic targets tracked=0
2018/05/12 18:57:29  - Network data messages sent: 770 total, 770 nonqueueable.  Network data bytes sent: 19217 total, 19217 nonqueueable.
2018/05/12 18:57:29  - Last GPS fix: 1 second ago, GPS solution type: 1 using 10 satellites (15/18 seen/tracked), NACp: 11, est accuracy 0.96 m
2018/05/12 18:57:29  - GPS vertical velocity: 2.61 ft/sec; GPS vertical accuracy: 1.92 m
2018/05/12 18:57:29 - Last IMU read: now, Last BMP read: 1 second ago
2018/05/12 18:57:59 stats [started: 1 minute ago]
2018/05/12 18:57:59  - Disk bytes used = 1.4 GB (81.6 %), Disk bytes free = 324 MB (18.4 %)
2018/05/12 18:57:59  - CPUTemp=63.38 deg C, MemStats.Alloc=3.4 MB, MemStats.Sys=7.7 MB, totalNetworkMessagesSent=2,566
2018/05/12 18:57:59  - UAT/min 0/0 [maxSS=0.00%], ES/min 0/0, Total traffic targets tracked=0
2018/05/12 18:57:59  - Network data messages sent: 2522 total, 2522 nonqueueable.  Network data bytes sent: 63009 total, 63009 nonqueueable.
2018/05/12 18:57:59  - Last GPS fix: 1 second ago, GPS solution type: 1 using 10 satellites (14/18 seen/tracked), NACp: 11, est accuracy 0.72 m
2018/05/12 18:57:59  - GPS vertical velocity: 0.86 ft/sec; GPS vertical accuracy: 1.44 m
2018/05/12 18:57:59 - Last IMU read: now, Last BMP read: 1 second ago
2018/05/12 18:58:29 stats [started: 1 minute ago]
2018/05/12 18:58:29  - Disk bytes used = 1.4 GB (81.6 %), Disk bytes free = 324 MB (18.4 %)
2018/05/12 18:58:29  - CPUTemp=63.91 deg C, MemStats.Alloc=491 kB, MemStats.Sys=7.7 MB, totalNetworkMessagesSent=4,462
2018/05/12 18:58:29  - UAT/min 0/0 [maxSS=0.00%], ES/min 0/0, Total traffic targets tracked=0
2018/05/12 18:58:29  - Network data messages sent: 4394 total, 4394 nonqueueable.  Network data bytes sent: 109789 total, 109789 nonqueueable.
2018/05/12 18:58:29  - Last GPS fix: 1 second ago, GPS solution type: 1 using 10 satellites (15/18 seen/tracked), NACp: 11, est accuracy 0.66 m
2018/05/12 18:58:29  - GPS vertical velocity: -6.73 ft/sec; GPS vertical accuracy: 1.32 m
2018/05/12 18:58:29 - Last IMU read: now, Last BMP read: now
2018/05/12 18:58:30 ===== ES Device Serial: stx:1090:33 PPM 33 =====
2018/05/12 18:58:30 Entered ES read() ...
2018/05/12 18:58:30 Executed /usr/bin/dump1090 successfully...
2018/05/12 18:58:30 ===== UAT Device Name  : Generic RTL2832U OEM =====
2018/05/12 18:58:30 ===== UAT Device Serial: 00000001=====
2018/05/12 18:58:30 	GetTunerType: RTLSDR_TUNER_R820T
2018/05/12 18:58:30 	SetTunerGainMode Successful
2018/05/12 18:58:30 	SetTunerGain Successful
2018/05/12 18:58:30 	GetTunerGain: 480
2018/05/12 18:58:30 	SetSampleRate - rate: 2083334
2018/05/12 18:58:30 	GetSampleRate: 2083334
2018/05/12 18:58:30 	GetXtalFreq - Rtl: 28800000, Tuner: 28800000
2018/05/12 18:58:30 	SetXtalFreq - Center freq: 28800000, Tuner freq: 28800000
2018/05/12 18:58:30 	SetCenterFreq 978MHz Successful
2018/05/12 18:58:30 	GetCenterFreq: 978000000
2018/05/12 18:58:30 	Setting Bandwidth: 1000000
2018/05/12 18:58:30 	SetTunerBw 1000000 Successful
2018/05/12 18:58:30 	ResetBuffer Successful
2018/05/12 18:58:30 	GetFreqCorrection: 0
2018/05/12 18:58:30 	SetFreqCorrection 0 Successful
2018/05/12 18:58:30 **Entered UAT read() ...**
2018/05/12 18:58:59 stats [started: 2 minutes ago]
2018/05/12 18:58:59  - Disk bytes used = 1.4 GB (81.6 %), Disk bytes free = 324 MB (18.4 %)
2018/05/12 18:58:59  - CPUTemp=65.53 deg C, MemStats.Alloc=3.2 MB, MemStats.Sys=8.8 MB, totalNetworkMessagesSent=7,381
2018/05/12 18:58:59  - **UAT/min 452/452** [maxSS=13.30%], ES/min 1,134/1,134, Total traffic targets tracked=55
2018/05/12 18:58:59  - Network data messages sent: 7290 total, 6932 nonqueueable.  Network data bytes sent: 622811 total, 199389 nonqueueable.
2018/05/12 18:58:59  - Last GPS fix: 1 second ago, GPS solution type: 1 using 10 satellites (15/18 seen/tracked), NACp: 11, est accuracy 0.66 m
2018/05/12 18:58:59  - GPS vertical velocity: -0.21 ft/sec; GPS vertical accuracy: 1.32 m
2018/05/12 18:58:59 - Last IMU read: 1 second ago, Last BMP read: 1 second ago

**Comment by cyoung** [comment]
Sounds like maybe the radio has an issue, either that or there's a power supply issue. I assume your red power LED is solid?

**Comment by Nokomis449** [comment]
When I used to see similar issues losing UAT, it was because it was low on disk space.  Deleting log files (freeing up disk space) would solve my issue for a while.  This was back before the logs were self-deleting.  I bet a clean install would solve his problem.  From his logs:

2018/05/12 18:54:17 - Disk bytes used = 1.4 GB (81.6 %), Disk bytes free = 325 MB (18.4 %)

**Comment by cyoung** [comment]
Still sounds like a power supply issue, re-open if you still have the issue @boa888.
