### ISSUE TITLE
Weird AHRS problem and Invalid NMEA string

### ISSUE THREAD

**Issue by IWenjunSun** [cyoung/stratux#719]
1. Stratux version:1.4r5
2. Stratux config:

    SDR
      - [ ] single
      - [x] dual

    GPS
      - [x] yes
      - [ ] no
      type:

    AHRS
      - [x] yes
      - [ ] no

    power source: tried many

    usb cable: tried many

3. EFB app and version: (e.g., WingX Pro7 8.6.2)

    EFB platform: (e.g., iOS 9.2)

    EFB hardware: (e.g., iPad Mini 2)

4. Description of your issue:
log file says GPS error. Invalid NMEA string: Invalid NMEA message. While I can get a GPS fix and see many satellites on the stratux page. When I plug in 978Mhz SDR, the red light goes off and AHRS becomes really slow. video reference(https://photos.app.goo.gl/QuaqG1m21bSg9yt33). as soon as i unplug the 978, red light comes back and AHRS goes happy and smooth. Don't think it's power issue, tried beefy 3A supply and battery, used usb meter to measure the power, 5.12V at 0.7A when both plugged in. 0.52A when only one plugged in 

If possible, enable "Replay Logs", reproduce the problem, and provide a copy of the logs in http://192.168.10.1/logs/stratux/ and http://192.168.10.1/logs/stratux.log.

**Comment by cyoung** [comment]
Have you fixed it? Reply and will re-open if not.
