### ISSUE TITLE
GnssDiffFromBaroAlt field not set for UAT tracks

### ISSUE THREAD

**Issue by Hunter522** [cyoung/stratux#721]
1. Stratux version: 1.4r4
2. Stratux config:

    SDR
      - [ ] single
      - [X] dual

    GPS
      - [X] yes
      - [ ] no
      type:

    AHRS
      - [X] yes
      - [ ] no

    power source: wallwart

    usb cable:

3. EFB app and version: (e.g., WingX Pro7 8.6.2) N/A

    EFB platform: (e.g., iOS 9.2) N/A

    EFB hardware: (e.g., iPad Mini 2) N/A

I am using this for a custom application.

4. Description of your issue:

The `GnssDiffFromBaroAlt ` field in JSON traffic reports when using WebSockets does not seem to be set for UAT tracks, they remain set to `0.0`. I have confirmed this by logging to the `.sqlite` file and running `dump978` separately to see if a GNSS altitude is being received at all. As per DO-282B (UAT MOPS), there is a `AUX STATE VECTOR` ADS-B payload element that contains `SECONDARY ALTITUDE` field which is the either geometric/gnss altitude or barometric altitude - whichever is opposite of the altitude field reported in the `STATE VECTOR` payload element (this is the altitude field normally used which is barometric typically). 

`dump978/uat_decode.c` seems to properly take care of decoding this but I don't see the use of this in `gen_gdl90.go` at all. `parseDownlinkReport()` in `gen_gdl90.go` looks like the function that takes care of decoding UAT frames but it doesn't take care of message types 1, 2, 5, and 6 that contain the `AUX STATE VECTOR` payload element. Not too sure here but is `dump978` library or Go wrapper even used in the main `gen_gdl90.go` program?

Anyway, pretty important for my use case I work in GPS/GNSS vertical datum (WGS84 ellipoid or geoid) and don't care much about pressure altitude. I would use the `GnssDiffFromBaroAlt` to compute the GNSS altitude based off the `Alt` (Pressure Altitude) field - but since that field is not set correctly I cant work with UAT targets. This may be a problem for other people as well that care about GNSS altitude.

Here is an annotated log from Stratux compared to what dump978 says:

```
{
        "Addr_type": "1",
        "Age": "0.19",
        "AgeLastAlt": "0.19",
        "Alt": "1525",                                    <------ Alt + GnssDiffFromBaroAlt = GnssAlt = What i'm interested in
        "AltIsGNSS": "0",
        "Bearing": "27.8151473137",
        "BearingDist_valid": "1",
        "Distance": "49242.752886832",
        "Emitter_category": "1",
        "ExtrapolatedPosition": "0",
        "GnssDiffFromBaroAlt": "0",                         <------- Notice not set!
        "Icao_addr": "3341381",
        "Last_GnssDiff": "0001-01-01 00:00:00 +0000 UTC",
        "Last_GnssDiffAlt": "0",
        "Last_alt": "0001-01-01 00:09:16.19 +0000 UTC",
        "Last_seen": "0001-01-01 00:09:16.19 +0000 UTC",
        "Last_source": "2",
        "Last_speed": "0001-01-01 00:09:16.19 +0000 UTC",
        "Lat": "28.0611839294",
        "Lng": "-97.0526733398",
        "NACp": "10",
        "NIC": "9",
        "OnGround": "0",
        "Position_valid": "1",
        "PriorityStatus": "0",
        "Reg": "",
        "SignalLevel": "-19.3315248903",
        "Speed": "112",
        "Speed_valid": "1",
        "Squawk": "1200",
        "Tail": "VFR",
        "TargetType": "0",
        "Timestamp": "2018-05-31 20:41:48.555540048 +0000 UTC",
        "Track": "326",
        "Vvel": "256",
        "id": "299",
        "timestamp_id": "81"
    }
```

```
HDR:
 MDB Type:          1
 Address:           32FC45 (reserved (national use))      <---- 3341381 in decimal
SV:
 NIC:               9
 Latitude:          +28.1030
 Longitude:         -97.0838
 Altitude:          1800 ft (barometric)
 N/S velocity:      98 kt
 E/W velocity:      -54 kt
 Track:             331
 Speed:             111 kt
 Vertical rate:     256 ft/min (from barometric altitude)
 UTC coupling:      yes
 TIS-B site ID:     0
MS:
 Emitter category:  Light <= 7000kg
 Callsign:          squawk 1200
 Emergency status:  No emergency
 UAT version:       2
 SIL:               3
 Transmit MSO:      47
 NACp:              10
 NACv:              2
 NICbaro:           1
 Capabilities:      CDTI ACAS
 Active modes:
 Target track type: true heading
AUXSV:
 Sec. altitude:     1725 ft (geometric)                <-------what i'm interested in and should be used in GnssDiffFromBaroAlt field in above JSON
```

**Comment by cyoung** [comment]
Test packet:
```
-08a20a3f3c0e7588af360a79002a30207d09da12ddd4040b52a4c2a0000a60000000;rs=6;
```

`uat2text` output:

```
HDR:
 MDB Type:          1
 Address:           A20A3F (ICAO address via ADS-B)
SV:
 NIC:               9
 Latitude:          +42.2272
 Longitude:         -83.8938
 Altitude:          3150 ft (barometric)
 N/S velocity:      9 kt
 E/W velocity:      -95 kt
 Track:             275
 Speed:             95 kt
 Vertical rate:     -384 ft/min (from geometric altitude)
 UTC coupling:      yes
 TIS-B site ID:     0
MS:
 Emitter category:  Light <= 7000kg
 Callsign:          N230TX
 Emergency status:  No emergency
 UAT version:       2
 SIL:               3
 Transmit MSO:      20
 NACp:              10
 NACv:              2
 NICbaro:           0
 Capabilities:      CDTI ACAS 
 Active modes:      
 Target track type: true heading
AUXSV:
 Sec. altitude:     3125 ft (geometric)
```

Websocket output from `ws://192.168.10.1/traffic`:

```json
{
  "Icao_addr": 10619455,
  "Reg": "N230TX",
  "Tail": "N230TX",
  "Emitter_category": 1,
  "OnGround": false,
  "Addr_type": 0,
  "TargetType": 1,
  "SignalLevel": -999,
  "Squawk": 0,
  "Position_valid": true,
  "Lat": 42.227196,
  "Lng": -83.89377,
  "Alt": 3150,
  "GnssDiffFromBaroAlt": -25,
  "AltIsGNSS": false,
  "NIC": 9,
  "NACp": 10,
  "Track": 276,
  "Speed": 95,
  "Speed_valid": true,
  "Vvel": -384,
  "Timestamp": "2019-01-31T16:11:28.658568863Z",
  "PriorityStatus": 0,
  "Age": 0,
  "AgeLastAlt": 0,
  "Last_seen": "0001-01-01T00:01:50.63Z",
  "Last_alt": "0001-01-01T00:01:50.63Z",
  "Last_GnssDiff": "0001-01-01T00:01:50.63Z",
  "Last_GnssDiffAlt": 3150,
  "Last_speed": "0001-01-01T00:01:50.63Z",
  "Last_source": 2,
  "ExtrapolatedPosition": false,
  "BearingDist_valid": false,
  "Bearing": 0,
  "Distance": 0
}
```

When you use `GnssDiffFromBaroAlt`, make sure you look at `Last_GnssDiff` and `Last_GnssDiffAlt`. These are saved when `GnssDiffFromBaroAlt` is calculated. This is important since messages without an AUXSV can be received where `Alt` is updated but `GnssDiffFromBaroAlt` is not.

Thanks for the detailed bug report, @Hunter522. Sorry it took so long.
