### ISSUE TITLE
Contribution - code snippet for Australian aircraft (traffic.go)

### ISSUE THREAD

**Issue by armeniki** [cyoung/stratux#736]
Hi everyone,

I wanted to firstly say thanks for everyone involved with this project!  

Secondly, I wanted to contribute a bit of code below, which will enable Australian users to decode the ICAO Mode S HEX into Australian "VH-xxx" tail numbers.  This code is in the **icao2reg** function in the file  **traffic.go** located in the **main** folder.

I have compiled this successfully and tested it on the latest version (1.4r5) with GoLang v1.10.3.

Cheers,
Armen

```
func icao2reg(icao_addr uint32) (string, bool) {
	// Initialize local variables
	base34alphabet := string("ABCDEFGHJKLMNPQRSTUVWXYZ0123456789")
	nationalOffset := uint32(0xA00001) // default is US
	tail := ""
	nation := ""

	// Determine nationality
	if (icao_addr >= 0xA00001) && (icao_addr <= 0xAFFFFF) {
		nation = "US"
	} else if (icao_addr >= 0xC00001) && (icao_addr <= 0xC3FFFF) {
		nation = "CA"
	} else if (icao_addr >= 0x7C0000) && (icao_addr <= 0x7FFFFF) {
		nation = "AU"
	} else {
		//TODO: future national decoding.
		return "OTHER", false
	}

	if nation == "CA" { // Canada decoding
		// First, discard addresses that are not assigned to aircraft on the civil registry
		if icao_addr > 0xC0CDF8 {
			//fmt.Printf("%X is a Canada aircraft, but not a CF-, CG-, or CI- registration.\n", icao_addr)
			return "CA-MIL", false
		}

		nationalOffset := uint32(0xC00001)
		serial := int32(icao_addr - nationalOffset)

		// Fifth letter
		e := serial % 26

		// Fourth letter
		d := (serial / 26) % 26

		// Third letter
		c := (serial / 676) % 26 // 676 == 26*26

		// Second letter
		b := (serial / 17576) % 26 // 17576 == 26*26*26

		b_str := "FGI"

		//fmt.Printf("B = %d, C = %d, D = %d, E = %d\n",b,c,d,e)
		tail = fmt.Sprintf("C-%c%c%c%c", b_str[b], c+65, d+65, e+65)
	}


	if nation == "AU" { // Australia decoding

		nationalOffset := uint32(0x7C0000)
		offset := (icao_addr - nationalOffset)
		i1 := offset/1296
		offset2 := offset % 1296
		i2 := offset2/36
		offset3 := offset2 % 36
		i3 := offset3
	
		var a_char, b_char, c_char string

		a_char = fmt.Sprintf("%c", i1+65)
		b_char = fmt.Sprintf("%c", i2+65)
		c_char = fmt.Sprintf("%c", i3+65)

		if i1<0 || i1>25 || i2<0 || i2>25 || i3<0 || i3>25 {
			return "OTHER", false
		}
			
		tail = "VH-" + a_char + b_char + c_char
	}


	if nation == "US" { // FAA decoding
		// First, discard addresses that are not assigned to aircraft on the civil registry
		if icao_addr > 0xADF7C7 {
			//fmt.Printf("%X is a US aircraft, but not on the civil registry.\n", icao_addr)
			return "US-MIL", false
		}

		serial := int32(icao_addr - nationalOffset)
		// First digit
		a := (serial / 101711) + 1

		// Second digit
		a_remainder := serial % 101711
		b := ((a_remainder + 9510) / 10111) - 1

		// Third digit
		b_remainder := (a_remainder + 9510) % 10111
		c := ((b_remainder + 350) / 951) - 1

		// This next bit is more convoluted. First, figure out if we're using the "short" method of
		// decoding the last two digits (two letters, one letter and one blank, or two blanks).
		// This will be the case if digit "B" or "C" are calculated as negative, or if c_remainder
		// is less than 601.

		c_remainder := (b_remainder + 350) % 951
		var d, e int32

		if (b >= 0) && (c >= 0) && (c_remainder > 600) { // alphanumeric decoding method
			d = 24 + (c_remainder-601)/35
			e = (c_remainder - 601) % 35

		} else { // two-letter decoding method
			if (b < 0) || (c < 0) {
				c_remainder -= 350 // otherwise "  " == 350, "A " == 351, "AA" == 352, etc.
			}

			d = (c_remainder - 1) / 25
			e = (c_remainder - 1) % 25

			if e < 0 {
				d -= 1
				e += 25
			}
		}

		a_char := fmt.Sprintf("%d", a)
		var b_char, c_char, d_char, e_char string

		if b >= 0 {
			b_char = fmt.Sprintf("%d", b)
		}

		if b >= 0 && c >= 0 {
			c_char = fmt.Sprintf("%d", c)
		}

		if d > -1 {
			d_char = string(base34alphabet[d])
			if e > 0 {
				e_char = string(base34alphabet[e-1])
			}
		}

		tail = "N" + a_char + b_char + c_char + d_char + e_char

	}

	return tail, true
}

```

**Comment by jamieqld** [comment]
Thanks for the great code.
Im new to this, would you know how I can get a version that only uses a single 1090 radio for version (1.4r5)
The one I have from the main page is dual radio.

**Comment by armeniki** [comment]
Hi jamieqld, thank you!  

You don't need a specific version to use only the 1090ES.  If you only want to use your SDR for 1090, just plug it in and edit the config file accordingly.  You can disable/enable the SDRs in there.

When you restart, you'll notice that only 1090ES data is displayed on the main page.

**Comment by jamieqld** [comment]
@armeniki ,
Im a real noob at this.
I have Stratux working on my Pi3 sd card. I have also download the source code, however I have been looking all day for the Config file so I can edit it, with no luck.

Would you be able to help me find/edit the config file. Please guide me as a noob.

Thanks 
jamie

**Comment by armeniki** [comment]
Hi Jamie, the configuration file is located here:

`/etc/stratux.conf`

Change the `UAT_Enabled` setting to `false`, reboot and you'll be all set.

**Comment by jamieqld** [comment]
Do I have to SSH into it.
I have a usb keyboard and mouse connected to the pi, and when i do a ls i dont see those files

**Comment by Helno** [comment]
@jamieqld You do not actually have to edit any files. 

You can change this in the web interface in either the settings tab or if you do not see a slider there for it you can click on the version number repeatedly on the main page and the developer tab will appear. There are sliders to enable or disable 978 1090 along with GPS AHRS and BARO.

**Comment by jamieqld** [comment]
Thanks Helno, I was able to get that to work. I was able to turn off radio 978 as not needed here is Australia.

I still would like to know how to get into /etc/stratux.conf

I tried to ssh with putty
Host: 192.168.10.1
Username:pi
Password:raspberry
no luck.

So please can someone tell me how to do it, I have been looking all night on here and found nothing to say how to do it.
I know im a noob at this, but very keen to learn.

jamie
VH-XJL

**Comment by kdknigga** [comment]
You're having problems sshing in, or you're having problems finding the
file after you ssh in?

**Comment by cyoung** [comment]
The file doesn't exist if the system is running on defaults. Once you change a setting, a `stratux.conf` file is generated.

**Comment by cyoung** [comment]
@armeniki - thanks! This is going in master now and you should see it integrated into the latest on the builds site soon (http://updates.stratux.me/builds/).
