### ISSUE TITLE
Submit Kwik EFIS / DMAP as compatible EFB application

### ISSUE THREAD

**Issue by ninelima** [cyoung/stratux#738]
1. Stratux version: v1.4r5 
2. Stratux config: dual SDR, GPS yes (u-blox 7 GNSS), AHRS yes, battery: USB cable to cigarette lighter (ships power).
3. EFB app and version: Kwik EFIS and Kwik DMAP. EFB platform: Android 4.4.2. EFB hardware: Nexus 7 Tablet and Samsung Galaxy S2.
4. Description of your issue: Request inclusion on the website of Kwik EFIS as a compatible EFB for use with Stratux.

Kwik EFIS for Android has been upgraded to support Stratux. It has been flight tested performed well with the hardware used.  The application is released as open source and made available through F-Droid as a signed and fully FOSS compliant package. 

Website:  http://members.iinet.net.au/~ninelima/efis    
Repository: https://github.com/ninelima/kwikEFIS

**Comment by JCBird1012** [comment]
Recommend closing — resolved in 4f9a02d.
