### ISSUE TITLE
Only one tuner tunes to 978MHz

### ISSUE THREAD

**Issue by jbrepogmailcom** [cyoung/stratux#745]
Hello,

from the log I can see that my only one tuner does not tune to 1090MHz. I am in Europe, how can I change tunning from 978 to 1090MHz? Thank you

2016/02/26 01:40:01 	GetTunerType: RTLSDR_TUNER_R820T
2016/02/26 01:40:01 	SetTunerGainMode Successful
2016/02/26 01:40:01 	SetTunerGain Successful
2016/02/26 01:40:01 	GetTunerGain: 480
2016/02/26 01:40:02 	SetSampleRate - rate: 2083334
2016/02/26 01:40:02 	GetSampleRate: 2083334
2016/02/26 01:40:02 	GetXtalFreq - Rtl: 28800000, Tuner: 28800000
2016/02/26 01:40:02 	SetXtalFreq - Center freq: 28800000, Tuner freq: 28800000
2016/02/26 01:40:02 	SetCenterFreq 978MHz Successful
2016/02/26 01:40:02 	GetCenterFreq: 978000000
2016/02/26 01:40:02 	Setting Bandwidth: 1000000
2016/02/26 01:40:02 	SetTunerBw 1000000 Successful
2016/02/26 01:40:02 	ResetBuffer Successful
2016/02/26 01:40:02 	GetFreqCorrection: 0
2016/02/26 01:40:02 	SetFreqCorrection 0 Successful

**Comment by cyoung** [comment]
1. Go to the main webui page (http://192.168.10.1/).
2. Tap the version number (middle-top of the screen) 7 times rapidly. This will enable "Developer Mode".
3. Go to "Settings". Disable 978.
