### ISSUE TITLE
Roll directions are inverted

### ISSUE THREAD

**Issue by jsilva-iii** [cyoung/stratux#747]
1. Stratux version:
                              stratux-v1.4r5 (downloadable image)
2. Stratux config:

    SDR
      - [ ] single
      - [X] dual

    GPS
      - [X] yes
      - [ ] no
      type:

    AHRS
      - [X] yes
      - [ ] no

    power source:
                          5V, 2A Power
    usb cable:

3. EFB app and version: (e.g., WingX Pro7 8.6.2)

    EFB platform: (e.g., iOS 9.2)

    EFB hardware: (e.g., iPad Mini 2)

4. Description of your issue:
From the web browser http://192.168.10.1 - the AHRS artificial horizon, tilt the AHRS wing down left, the AHRS shows horizon as rolling to right, same for tilt right, shows rolling to left. The pitch direction is however correct. I am using raspbery Pi3 and Stratux AHRS Sensors and Fan Controller / Raspberry Pi MPU9250+BMP280. 

If possible, enable "Replay Logs", reproduce the problem, and provide a copy of the logs in http://192.168.10.1/logs/stratux/ and http://192.168.10.1/logs/stratux.log.

**Comment by cyoung** [comment]
You need to change the physical orientation of the box or set the orientation in software. [Try this](https://www.youtube.com/watch?v=hJwe989b-1s).
