### ISSUE TITLE
Flarm process doesn't start because of missing libjpeg

### ISSUE THREAD

**Issue by PhilippMuenzel** [cyoung/stratux#753]
ATTN: @PepperJo

1. Stratux version: v1.4r5-flarm Flarm v2 https://github.com/PepperJo/stratux/releases/tag/v1.4r5-flarm2
2. Stratux config: 

    SDR
      - [ ] single
      - [x] dual

    GPS
      - [x] yes
      - [ ] no
      type: G-mouse

    AHRS
      - [x] yes
      - [ ] no

    power source: power bank

    usb cable:

3. EFB app and version: ForeFlight

    EFB platform: iOS 12

    EFB hardware: iPad Mini 2

4. Description of your issue:

No Flarm option appears in the Settings page. In the logs, when searching for flarm, the following messages keep appearing periodically, as the flarm service tries to start and fails: 
2018/07/17 20:01:19 FLARM: Decoder is not running
2018/07/17 20:01:19 FLARM: Restarting decoder
2018/07/17 20:01:19 FLARM: Started new decoding process (pid=592)
2018/07/17 20:01:19 FLARM: ogn-decode stderr: ogn-decode: error while loading shared libraries: libjpeg.so.8: cannot open shared object file: No such file or directory
2018/07/17 20:01:19 FLARM: Process /usr/bin/ogn-decode terminated: exit status 127

These lines keep appearing in the log over and over.
There is no checkbox or radio button on either the traffic or the settings page to enable the flarm receiver. 

The SDR logs are empty. It says to "enable device logging on setting page", but there is no button on the settings page to enable any "device logging".

**Comment by PepperJo** [comment]
There is no FLARM option, since the developer mode is disabled. You can enable developer mode by clicking on the title/header of the website a few times. But the missing library should have been fixed a while ago. Let me take another look. I'll keep you updated.

**Comment by PepperJo** [comment]
I just tested the image and it works fine for me:
`root@raspberrypi:~/stratux/ogn/rtlsdr-ogn# ldd ogn-decode 
	/usr/lib/arm-linux-gnueabihf/libarmmem.so (0xb6f6f000)
	libpthread.so.0 => /lib/arm-linux-gnueabihf/libpthread.so.0 (0xb6f40000)
	libjpeg.so.8 => /usr/lib/arm-linux-gnueabihf/libjpeg.so.8 (0xb6efd000)
	libconfig.so.9 => /usr/lib/arm-linux-gnueabihf/libconfig.so.9 (0xb6eec000)
	librt.so.1 => /lib/arm-linux-gnueabihf/librt.so.1 (0xb6ed5000)
	libdl.so.2 => /lib/arm-linux-gnueabihf/libdl.so.2 (0xb6ec2000)
	libstdc++.so.6 => /usr/lib/arm-linux-gnueabihf/libstdc++.so.6 (0xb6de6000)
	libm.so.6 => /lib/arm-linux-gnueabihf/libm.so.6 (0xb6d6b000)
	libgcc_s.so.1 => /lib/arm-linux-gnueabihf/libgcc_s.so.1 (0xb6d3e000)
	libc.so.6 => /lib/arm-linux-gnueabihf/libc.so.6 (0xb6bfd000)
	/lib/ld-linux-armhf.so.3 (0x7f601000)
`
Can you try to ssh with username pi and password raspberry and try the above command?

**Comment by PepperJo** [comment]
FYI I enabled issues on my fork, so in the future you can post FLARM related issues there.

**Comment by VirusPilot** [comment]
Philip, a quick hack: apt-get install libjpeg8

But I tested PepperJo's image as well with no problems at all. Are you using standard stratux components including 2 SDRs? Did you eeprom the SDRs?

**Comment by cyoung** [comment]
Sounds like you got it. Open if still an issue.
