### ISSUE TITLE
Feature request 

### ISSUE THREAD

**Issue by rw86347** [cyoung/stratux#758]
If I have a raspberry pi why not add a nice display too.

https://www.adafruit.com/product/2033?gclid=EAIaIQobChMIydSF69Gq3gIV0rfACh0nkgHxEAQYASABEgKpOvD_BwE

If you point me into the right direction I can create a GUI

**Comment by cyoung** [comment]
@rw86347 - thanks for the suggestion. We likely won't make an interface specifically for stratux, but there are a number of them out there that you could start with.

https://github.com/ninelima/kwikEFIS

https://github.com/Bagarre/Pi2D2

https://github.com/JohnMarzulli

I think we'll start working on a list for the Wiki, let us know (respond to this ticket, if you could) if you get it working.
