### ISSUE TITLE
Default Image DHCP options

### ISSUE THREAD

**Issue by Michandrz** [cyoung/stratux#762]
1. Stratux version: 1.4r5
2. Stratux config: 

    SDR
      - [ ] single
      - [ X ] dual

    GPS
      - [ x ] yes
      - [ ] no
      type:

    AHRS
      - [ x ] yes
      - [ ] no

    power source: Battery bank

    usb cable: yes

3. EFB app and version: (e.g., WingX Pro7 8.6.2) Foreflight 

    EFB platform: (e.g., iOS 9.2) IOS 11.1.2

    EFB hardware: (e.g., iPad Mini 2) Iphone 6s 64gb

4. Description of your issue:

more of a suggestion for the image than an issue:

/etc/httpd/httpd.conf comment out the line reading default router set to 192.168.10.1

By doing this, you can still connect to stratux, however it signals to IOS devices that this connection does not provide internet access and allows them to use cellular data for non-stratux communications.

If possible, enable "Replay Logs", reproduce the problem, and provide a copy of the logs in http://192.168.10.1/logs/stratux/ and http://192.168.10.1/logs/stratux.log.

**Comment by wa9als** [comment]
I just make the connection a static connection instead of automatic, and all the other stuff can use cellular.

**Comment by cyoung** [comment]
Causes issues with Android and other platforms when there is no default route.

We had it configured this way for a while for cellular access, but the feature wasn't worth the trouble.

Stratux is for use in flight. You won't have any decent cellular coverage.
