### ISSUE TITLE
description of issue

### ISSUE THREAD

**Issue by andreew81** [cyoung/stratux#763]
1. Stratux version:
2. Stratux config: single/dual SDR, GPS yes/no (type?), AHRS yes/no, battery, battery cable.
3. EFB app and version (e.g., WingX Pro7 8.6.2). EFB platform (e.g., iOS 9.2). EFB hardware (e.g., iPad Mini 2).
4. Description of your issue. If possible, enable "Replay Logs", reproduce the problem, and provide a copy of the logs in http://192.168.10.1/logs/stratux/ and http://192.168.10.1/logs/stratux.log.

**Comment by cyoung** [comment]
Do you have a link for the SDRs you're using?

**Comment by Helno** [comment]
Where you able to the the GPS reliably working?
