### ISSUE TITLE
UDP/TCP ports: 4353, 10110, 4352, 2000, 23 

### ISSUE THREAD

**Issue by dgofman** [cyoung/stratux#775]
Hi, I am using Stratux version:  v1.4r5 and would like to integrate with XCSoar 6.5.
By default XCSoar supporting UDP/TCP ports: 4353, 10110, 4352, 2000, 23.
I found old tickets:
https://github.com/cyoung/stratux/issues/489
https://github.com/cyoung/stratux/issues/571
https://cloud.githubusercontent.com/assets/8769091/23965570/a163ca32-0975-11e7-9efd-55d3a1ee31a1.png

Where you described supporting FLARM ports, however, I don't this that option anymore.
Please can you add this feature back,

**Comment by cyoung** [comment]
We never added FLARM support to the main branch.

Try this fork: https://github.com/PepperJo/stratux.

**Comment by VirusPilot** [comment]
In fact this fork here is the "European" Stratux flavor:

https://github.com/b3nn0/stratux

It includes all previous FLARM developments in one fork.

**Comment by dgofman** [comment]
Yes, but my goal connecting startux and XCSoar. I am using your image and instruction from https://github.com/0sander/stratux_air_nav_pro  and cannot get Data. I tried to change a port to 4352 and ip address still no lack.
Please, can you help me?

**Comment by dgofman** [comment]
![Screenshot_20190609-131924_XCSoar](https://user-images.githubusercontent.com/147298/59163759-0097a880-8aba-11e9-8576-0212fba58d4d.jpg)
![Screenshot_20190609-132220_Chrome](https://user-images.githubusercontent.com/147298/59163773-2624b200-8aba-11e9-9d54-1019fbc542b8.jpg)
![Screenshot_20190609-132258_Chrome](https://user-images.githubusercontent.com/147298/59163777-3ccb0900-8aba-11e9-8c69-60c66bfbb34c.jpg)
