### ISSUE TITLE
ADS-B Weather Failover

### ISSUE THREAD

**Issue by gmint** [cyoung/stratux#776]
1. Stratux version: v1.5b2
2. Stratux config:

    SDR
      - [ ] single
      - [X] dual

    GPS
      - [X] yes
      - [ ] no
      type:

    AHRS
      - [X] yes
      - [ ] no

    power source: 12v adapter

    usb cable: about the fourth one I tried and was finally able to provide stable power.

3. EFB app and version: ForeFlight 11.4

    EFB platform: iOS 12.3

    EFB hardware: iPhone XR, iPad Air

4. Description of your issue: 

I’ve configured my stratux so that my iPad connects via Ethernet to the stratux, thus leaving the WiFi free to connect to my phone. As such, I’m often in a spot where I can receive ADS-B based weather as well as Internet based weather. However, on a recent flight I realized that this isn’t quite as helpful as it might seem since when the ADS-B reception was bad (a condition that will hopefully be alleviated by my recently purchased v3 UAT radio) I still wasn’t getting internet weather. I didn’t want to disconnect the stratux, because I still wanted a good GPS signal, but by doing that I was stuck with poor weather data. I realize that this is something that could/should probably be handled by ForeFlight, I was wondering if it might be feasible to have an option that would basically just disconnect the ADS-B based weather thus forcing ForeFlight to automatically fail over to internet based weather.

**Comment by cyoung** [comment]
>(...) any data sent from stratux triggers ForeFlight to use it as its only data source. So if the connection from your receiver were dropped when there were no UAT towers, that would mean losing the GPS and AHRS data feeds.

Issue speaks of reception problems that are likely the result of some other issue with the receiver. Leaving this to troubleshooting on Reddit.
