### ISSUE TITLE
description of issue

### ISSUE THREAD

**Issue by FreakwantFlyer** [cyoung/stratux#783]
1. Stratux version: Stratux Europe Edition 1.5b2-eu007 BETA
2. Stratux config: dual  SDR, GPS yes (type?), AHRS yes, battery 20.000 mah Powerbank, battery cable: High quality.
3. EFB app and version: SkyDaemon latest version. EFB platform: Android 9.0. EFB hardware: Xiaomi Mi Max 3.
4. Description of your issue. 
Tried two different phones, Xiaomi Mi Max 3 and Samsung Galaxy 10, on both platforms the user config data is not stored permanently. After each Power Off and Restart of Startux the configuration of Stratux has to be re-entered. Thanks!

If possible, enable "Replay Logs", reproduce the problem, and provide a copy of the logs in http://192.168.10.1/logs/stratux/ and http://192.168.10.1/logs/stratux.log.

**Comment by cyoung** [comment]
Which user config data?
