### ISSUE TITLE
ForeFlight v10.6 + Stratux v1.5b2 Not showing AHRS data "No attitude information" 

### ISSUE THREAD

**Issue by MLF19** [cyoung/stratux#792]
1. Stratux version: 1.5b2
2. Stratux config: 

    SDR
      - [ ] single
      - [X ] dual

    GPS
      - [ ] yes
      - [ X] no
      type:

    AHRS
      - [X ] yes
      - [ ] no

    power source:

    usb cable:  X

3. EFB app and version: (e.g., WingX Pro7 8.6.2)

ForeFlight V10.6

    EFB platform: (e.g., iOS 9.2)

iOS 10.3.3

    EFB hardware: (e.g., iPad Mini 2)

iPad 4th Generation 

4. Description of your issue:

Added AHRS. When I hit 192.168.10.1 Attitude indicator works but it does not see GPS solution. "GPS Solution: No Fix" which I think I read was to be expected when using internal GPS. When I open ForeFlight: "No Attitude Information" Though I am getting GPS derived ground speed and altitude and it shows the GPS source as IOS. 

If possible, enable "Replay Logs", reproduce the problem, and provide a copy of the logs in http://192.168.10.1/logs/stratux/ and http://192.168.10.1/logs/stratux.log.

A snippet of the logs. I see this "attempting" over and over again...

<pre style="color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; widows: auto; word-spacing: 0px; -webkit-tap-highlight-color: rgba(26, 26, 26, 0.301961); -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; word-wrap: break-word; white-space: pre-wrap;">MemStats.Sys=8.8 MB, totalNetworkMessagesSent=1,096
2016/02/26 01:34:37  - UAT/min 0/0 [maxSS=0.00%], ES/min 73/189, Total traffic targets tracked=4
2016/02/26 01:34:37  - Network data messages sent: 899 total, 899 nonqueueable.  Network data bytes sent: 22727 total, 22727 nonqueueable.
2016/02/26 01:34:37  - Last GPS fix: 16 minutes ago, GPS solution type: 0 using 0 satellites (0/0 seen/tracked), NACp: 0, est accuracy 999999.00 m
2016/02/26 01:34:37  - GPS vertical velocity: 0.00 ft/sec; GPS vertical accuracy: 999999 m
2016/02/26 01:34:37 - Last IMU read: now, Last BMP read: now
2016/02/26 01:34:39 UBX8 device detected on USB, or GPS serial connection in use. Attempting GLONASS and Galelio configuration.
2016/02/26 01:34:43 UBX8 device detected on USB, or GPS serial connection in use. Attempting GLONASS and Galelio configuration.
2016/02/26 01:34:47 UBX8 device detected on USB, or GPS serial connection in use. Attempting GLONASS and Galelio configuration.
2016/02/26 01:34:51 UBX8 device detected on USB, or GPS serial connection in use. Attempting GLONASS and Galelio configuration.
2016/02/26 01:34:55 UBX8 device detected on USB, or GPS serial connection in use. Attempting GLONASS and Galelio configuration.
2016/02/26 01:34:59 UBX8 device detected on USB, or GPS serial connection in use. Attempting GLONASS and Galelio configuration.
2016/02/26 01:35:03 UBX8 device detected on USB, or GPS serial connection in use. Attempting GLONASS and Galelio configuration.
2016/02/26 01:35:07 UBX8 device detected on USB, or GPS serial connection in use. Attempting GLONASS and Galelio configuration.
2016/02/26 01:35:07 stats [started: 16 minutes ago]
2016/02/26 01:35:07  - Disk bytes used = 1.5 GB (80.1 %), Disk bytes free = 371 MB (19.9 %)
2016/02/26 01:35:07  - CPUTemp=55.84 [49.39 - 56.38] deg C, MemStats.Alloc=3.1 MB, MemStats.Sys=8.8 MB, totalNetworkMessagesSent=1,120
2016/02/26 01:35:07  - UAT/min 0/0 [maxSS=0.00%], ES/min 220/220, Total traffic targets tracked=4
2016/02/26 01:35:07  - Network data messages sent: 911 total, 911 nonqueueable.  Network data bytes sent: 23027 total, 23027 nonqueueable.</pre>

**Comment by cyoung** [comment]
You need to install a GPS that connects to your Stratux. See http://stratux.me.

**Comment by MLF19** [comment]
Clearly I was under a false impression. Thanks!
