### ISSUE TITLE
Add P-Alt unit in GPS web page

### ISSUE THREAD

**Issue by pasniak** [cyoung/stratux#799]
1. Stratux version: 1.5

4. Description of your issue:
The P-alt value (or label) has no unit (feet or meters). I open Stratux status page from Android device's built-in browser.

**Comment by cyoung** [comment]
You don't see an apostrophe after the scalar value? If yes, that's the unit (feet). If no, there's a problem with the webui rendering on that browser.


https://github.com/cyoung/stratux/blob/master/web/plates/gps.html#L43

**Comment by pasniak** [comment]
yeah, when I squint it (') is there, I look at small cell phone screen. Poor sight... Ah those barbarian units :-)
