### ISSUE TITLE
Upgrade Ideas/Product Improvement

### ISSUE THREAD

**Issue by exilepc** [cyoung/stratux#804]
1. Stratux version: Current [v1.6r1]
2. Stratux config:

    SDR
      - [   ] single
      - [X] dual

    GPS
      - [X] yes
      - [   ] no
      type: Stratux v2.0

    AHRS
      - [X] yes
      - [   ] no

    power source: Battery+Plug

    usb cable: Random

3. EFB app and version: Foreflight Current

    EFB platform: iOS Current

    EFB hardware: iPad Mini 3 Verizon, iPad pro 10.5

4. Description of your awesome idea(s):
-Long timeouts on GPS and slow to start along with confusing logs: 2 ways to improve this, first add a real-time clock to the AHRS or set the boot date to the last known date (or at least set the date of the build). (Added use the SDR to get the PosTime from the ADS-B packet and set the system time to it if < than 90 minutes) 

-Add Li-Po Battery charging circuit to the AHRS allowing the user to add an internal backup battery for emergencies.

-Set SDR start-up to after GPS has gotten a lock unless GPS is not detected or user presses a gps skip/boot sdr now CMD button on the dashboard.

-Add shield added to the case to sit between the GPS and SDR.

-Auto expand the file system on first boot

-On dashboard display, Pi voltage and calculation based on known external battery size showing an ETA to empty

-Internal Antenna option for standard case

-Predictive fan use not after the temp is reached

-Complete data logging to SD card

-Add buzzer to AHRS to alert the user to issue (VIZ. GPS not detected but was detected before, SDR not detected but was detected before, Sudden Loss of GPS or SDR while inflight, Squawk of 7700, 7600 or 7500)

-SD Card health (think S>M>A>R>T data)

-Import the last known GPS location/azimuth to the system to all faster 

-Dark-Mode for the home screen

-Log/Display SDR Messages rate, GPS accuracy, temp and the like on to graph for testing/diag

-Actually have a 'Enable Device Logging' on the settings page

**Comment by Helno** [comment]
Pick a few of those out and give them a try yourself.
