### ISSUE TITLE
V1.6 image too large for 2gb SD Card

### ISSUE THREAD

**Issue by dnickerson** [cyoung/stratux#805]
1. Stratux version: stratux-v1.6r1-377d22b403.img
2. Stratux config:

    SDR
      - [ ] single
      - [ ] dual

    GPS
      - [ ] yes
      - [ ] no
      type:

    AHRS
      - [ ] yes
      - [ ] no

    power source:

    usb cable:

3. EFB app and version: (e.g., WingX Pro7 8.6.2)

    EFB platform: (e.g., iOS 9.2)

    EFB hardware: (e.g., iPad Mini 2)

4. Description of your issue:
I'm trying to write the stratux-v1.6r1-377d22b403.img image to a FAT32 formatted 2gb SD card and the v1.6 image is 2.0gb. The image size is about 45mb too large. Can you shrink the size of one of the partitions and reissue the image?
![Screenshot from 2020-01-29 11-03-49](https://user-images.githubusercontent.com/13767972/73379532-6d052900-4290-11ea-84f6-6f7a13e876c6.png)

If possible, enable "Replay Logs", reproduce the problem, and provide a copy of the logs in http://192.168.10.1/logs/stratux/ and http://192.168.10.1/logs/stratux.log.

**Comment by cyoung** [comment]
May shrink it in the future. I don't think 2GB are produced any more.
