### ISSUE TITLE
How EFB Data Access to Stratux

### ISSUE THREAD

**Issue by RusTus** [cyoung/stratux#806]
Just wondering how EFB's like ifly or naviator knows where to look for the udp packets from the Stratux.

Are they looking specifically to go to 192.168.10.1 or are they using the gateway of their subnet to rely on the Stratux being there to receive packets?

Or is there some other fancy way to scan for protocol requests?

Would be helpful for me and my project!

**Comment by cyoung** [comment]
[App vendor integration guide](https://github.com/cyoung/stratux/blob/master/notes/app-vendor-integration.md) should answer this, re-open if not.
