### ISSUE TITLE
old GPS over serial baudrate error

### ISSUE THREAD

**Issue by sueppchen** [cyoung/stratux#812]
1. Stratux version: 
1.6r1-eu015

2. Stratux config:

    SDR
      - [ ] single
      - [x] dual

    GPS
      - [x] yes
      - [ ] no
      type: Sirf STAR II as /dev/ttyAMA0

    AHRS
      - [x] yes
      - [ ] no

    power source: WALL adapter

    usb cable: short and strong

3. EFB app and version: (e.g., WingX Pro7 8.6.2)

    EFB platform: (e.g., iOS 9.2)

    EFB hardware: (e.g., iPad Mini 2)

4. Description of your issue:

old serial GPS not found (baudrateError)

in **main/gps.go: func initGPSSerial() bool {}**

the GPS is initialized with 4800baud
then it is tested if it is a SIRF IV or something other... 
if it is NOT a Sirf IV there will be send a few magic numbers and then the baudrate is set to 38400 but there is no test if the GPS-chip does understand the "change the baudrate message".

My old Sirf II does work well on 4800 and if I comment out the **else{}** of if _**isSirfIV {}**_
the Error has gone

**Comment by cyoung** [comment]
Sounds like you have found a solution that works for you. The older Sirf II isn't supported hardware, so I don't think we'll add any fixes to the code for this.
