### ISSUE TITLE
UPS HAT Board Battery Indication 

### ISSUE THREAD

**Issue by robduby76** [cyoung/stratux#815]
1. Stratux version:1.6r1
2. Stratux config:

    SDR
      - [ ] single
      - [x] dual

    GPS
      - [x] yes
      - [ ] no
      type:

    AHRS
      - [x] yes
      - [ ] no

    power source: UPS HAT board MakerFocus    B01MQYX4UX

    usb cable: for charging 

3. EFB app and version: FLYQ EFB 4.5.2

    EFB platform: iOS 13.5.1

    EFB hardware: iPhone 11 Pro Max 

4. Description of your issue: FlyQ EFB does not show battery life %. Is this a possibility with the UPS HAT I’m using

**Comment by Helno** [comment]
Stratux does not send this data to EFB's.
