### ISSUE TITLE
"level" the AHRS

### ISSUE THREAD

**Issue by bradanlane** [cyoung/stratux#83]
Is there a system level instruction that can be sent to the RY835AI to "level" the AHRS in pitch and roll?

I have mine sitting on a flat surface and it is reading approx 30 degrees of pitch and 1 degree of roll.

I rebooted it and it seems to have leveled. In looking at the code it appears to calibrate for some period of time at each start.

If there is no useful reason to re-level it after start, then this is a non-issue.

**Comment by cyoung** [comment]
Are you referring to the current AHRS implementation in v0.4r2? If so, leave it level for 60 seconds after startup and it will level itself.

**Comment by bradanlane** [comment]
OK, that explains what I saw after reboot. I'm not sure why is was wonky before.
