### ISSUE TITLE
Option to disable/enable AHRS

### ISSUE THREAD

**Issue by pasniak** [cyoung/stratux#835]
Is it possible to disable AHRS in the GUI? or via SSH? (I want to avoid Stratux disassembly/reassembly). My device receives many AHRS messages (0x4c/76). Maybe it would lower power consumption and WiFi traffic, too, if AHRS is not used? Maybe also allow disabling 0x65/101 (ForeFlight)?

1. Stratux version: 1.5b1

**Comment by cyoung** [comment]
http://192.168.10.1/ -> Settings -> AHRS Sensor.

Last we checked the power consumption from AHRS and its related processes was negligible. If you measure it and notice more than a 5% difference, please re-open the issue and note your findings here.

**Comment by pasniak** [comment]
I upgraded to 1.6r1 but I see no "AHRS Sensor" button anywhere... 
- in GPS/AHRS there is only Set leve/zero drift
- in Settings there is only Set AHRS Sensor Orientation and G Limits

**Comment by cyoung** [comment]
Ah, sorry. Enable developer mode by clicking 8 times within 3 seconds on the version number on the main status page (http://192.168.10.1/). Then check.
