### ISSUE TITLE
http://slack.stratux.me/ doesn't connect

### ISSUE THREAD

**Issue by pcarew** [cyoung/stratux#887]
I was looking to join the slack group, but the webpage http://slack.stratux.me/ won't connect
Is there another way to join the slack discussion?

**Comment by pp4life** [comment]
[stratuxadsb.slack.com](stratuxadsb.slack.com)

**Comment by pcarew** [comment]
Thanks for responding, but stratuxadsb.slack.com won't let me sign in as I don't already have an account on that forum.
Response: It looks like there isn’t an account on Stratux ADS-B tied to this email address

**Comment by pp4life** [comment]
Invite link I was able generate.

[https://join.slack.com/t/stratuxadsb/shared_invite/zt-2pe926hoj-~sehdIJ1JqZVz4VKb37chA](https://join.slack.com/t/stratuxadsb/shared_invite/zt-2pe926hoj-~sehdIJ1JqZVz4VKb37chA)

**Comment by pcarew** [comment]
Thank you, that worked.

**Comment by wa9als** [comment]
Sent from my iPhoneOn Aug 27, 2024, at 12:19, Paul Carew ***@***.***> wrote:﻿
Thank you, that worked.

Not for me. —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>
