### ISSUE TITLE
improper stratux shutdowns

### ISSUE THREAD

**Issue by skypuppy** [cyoung/stratux#93]
It occurred to me that we might have to manage the proper shutdown of the rPi(x) as they get more popular and in the hands of people who aren't familiar with the requirement to do so.  It might also help if some sort of certification is in stratux' future.
Here are the first 3 possibilities I could think of:
1. Add a "shutdown stratux and system" option to the 'web page' interface.  It's purpose is to pass a "shutdown -h now" command to the kernel.  Further, stress in user training that this MUST be performed rather than just turning off the power to the "stratux box."
2. Leave the code as-is.  Emphasize training to newbs on how to ssh into the rPi(x) to pass the shutdown command.  Yeah, like *that* will work on a non-computer person.
3. Add a bit of hardware to the stratux system that has a few minutes of backup battery time, a current (12 or 5 vdc) sensor to the stratux power-in that toggles a gpio port that external power has been lost and to execute a graceful shutdown if the user allows it (could be an emergency situation and the user desperately needs the gps or ahrs functions, but regardless do a proper shutdown when backup battery is nearly empty.

Other power sensors could be utilized in the future.  Like if on ship's power, delay powering up the stratux system until after that massive current drain of the engine starter is over with.  Brownouts can really hurt systems like ours.  I mean this is getting rather sophisticated for a $130 box, but we might want to keep it in the back of our minds for the future.  A pass-through battery power conditioner would be just the thing...

**Comment by cyoung** [comment]
Has been discussed before, don't want to open this conversation again. Make an app for it or something, should be a two liner.
