### ISSUE TITLE
Multiple Devices seen in ForeFlight

### ISSUE THREAD

**Issue by JohnOCFII** [cyoung/stratux#99]
I've been meaning to ask about this for a while.  In ForeFlight there are two devices that show up under the Settings --> Devices display. One is titled Stratux.  The other is FreeFlight.  If you drill into the Stratux item, there is a switch for Enabled or not, and nothing else.  The FreeFlight item shows all (most?) of the items I see when I'm using the Appareo Stratus 2.  Screen shots below.  Is this expected behavior?  Based on my experience with the Stratus, I'd expect only one device in the hierarchy.

![foreflight settings](https://cloud.githubusercontent.com/assets/7844212/10866994/81deb730-8019-11e5-89e5-b3d1225697c7.jpg)
![stratux item](https://cloud.githubusercontent.com/assets/7844212/10866995/857ab8d0-8019-11e5-9a95-83aa97575c51.jpg)
![freeflight item](https://cloud.githubusercontent.com/assets/7844212/10866996/89047568-8019-11e5-89d9-346f9eb8c0df.jpg)

**Comment by cyoung** [comment]
That's correct. It will only show two devices when you have AHRS enabled. The "Stratux" device is sending AHRS as a separate device since the FreeFlight GDL90 implementation, as far as I know, doesn't provide for a way to send AHRS data. Also it keeps us away from using "proprietary" formats.

**Comment by JohnOCFII** [comment]
Sounds good.  Thanks for the explanation.
